// RUN: %split_file %s %t
// RUN: /usr/bin/perl -e '$d=512; print "builtin.module attributes {ac.contract_epoch = \"0.1\"} {\n"; print "builtin.module {\n" for 1..$d; print "}\n" for 1..$d; print "}\n"' > %t/depth512.mlir
// RUN: /usr/bin/perl -e '$d=513; print "builtin.module attributes {ac.contract_epoch = \"0.1\"} {\n"; print "builtin.module {\n" for 1..$d; print "}\n" for 1..$d; print "}\n"' > %t/depth513.mlir
// RUN: /usr/bin/perl -e '$d=10000; print "builtin.module attributes {ac.contract_epoch = \"bad\"} {\n"; print "builtin.module {\n" for 1..$d; print "\"scf.yield\"() : () -> ()\n"; print "}\n" for 1..$d; print "}\n"' > %t/depth10000.mlir
// RUN: %acir_opt --verify-each=false %t/depth512.mlir >/dev/null
// RUN: %acir_opt --verify-each=false --normalize-ac-file %t/depth512.mlir >/dev/null
// RUN: %not %acir_opt --verify-each=false %t/depth513.mlir 2>&1 | %FileCheck %s --check-prefix=DEPTH --implicit-check-not='expected top-level' --implicit-check-not='stack'
// RUN: %not %acir_opt --verify-each=false --normalize-ac-file %t/depth513.mlir 2>&1 | %FileCheck %s --check-prefix=DEPTH --implicit-check-not='expected top-level' --implicit-check-not='stack'
// RUN: %not %acir_opt --verify-each=false %t/depth10000.mlir 2>&1 | %FileCheck %s --check-prefix=DEPTH --implicit-check-not='expected top-level' --implicit-check-not='stack'
// RUN: %not %acir_opt --verify-each=false --normalize-ac-file %t/depth10000.mlir 2>&1 | %FileCheck %s --check-prefix=DEPTH --implicit-check-not='expected top-level' --implicit-check-not='stack'

// DEPTH: whole-model region nesting exceeds ACIR v0.1 capability limit 512

//--- depth512.mlir
// Generated by the RUN line so the checked-in fixture remains reviewable.

//--- depth513.mlir
// Generated by the RUN line so the checked-in fixture remains reviewable.

//--- depth10000.mlir
// Generated by the RUN line so the checked-in fixture remains reviewable.
