// Generated by pycc (pyCircuit)
// Module: alu

module alu (
  input clk,
  input rst,
  input dv_alu0_valid,
  input [3:0] dv_alu0_func,
  input [63:0] dv_alu0_src1,
  input [63:0] dv_alu0_src2,
  input [6:0] dv_alu0_pdst,
  output dv_alu0_result_valid,
  output [6:0] dv_alu0_result_tag,
  output [63:0] dv_alu0_result_data
);

wire [63:0] pyc_add_15; // op=pyc.add
wire [63:0] pyc_and_17; // op=pyc.and
wire [63:0] pyc_comb_46; // op=pyc.comb
wire [63:0] pyc_constant_1; // op=pyc.constant
wire [3:0] pyc_constant_10; // op=pyc.constant
wire [3:0] pyc_constant_11; // op=pyc.constant
wire [3:0] pyc_constant_12; // op=pyc.constant
wire [3:0] pyc_constant_13; // op=pyc.constant
wire [3:0] pyc_constant_14; // op=pyc.constant
wire [63:0] pyc_constant_2; // op=pyc.constant
wire [3:0] pyc_constant_3; // op=pyc.constant
wire [3:0] pyc_constant_4; // op=pyc.constant
wire [3:0] pyc_constant_5; // op=pyc.constant
wire [3:0] pyc_constant_6; // op=pyc.constant
wire [3:0] pyc_constant_7; // op=pyc.constant
wire [3:0] pyc_constant_8; // op=pyc.constant
wire [3:0] pyc_constant_9; // op=pyc.constant
wire pyc_eq_22; // op=pyc.eq
wire pyc_eq_24; // op=pyc.eq
wire pyc_eq_26; // op=pyc.eq
wire pyc_eq_28; // op=pyc.eq
wire pyc_eq_30; // op=pyc.eq
wire pyc_eq_32; // op=pyc.eq
wire pyc_eq_34; // op=pyc.eq
wire pyc_eq_36; // op=pyc.eq
wire pyc_eq_38; // op=pyc.eq
wire pyc_eq_40; // op=pyc.eq
wire pyc_eq_42; // op=pyc.eq
wire pyc_eq_44; // op=pyc.eq
wire [63:0] pyc_mux_21; // op=pyc.mux
wire [63:0] pyc_mux_23; // op=pyc.mux
wire [63:0] pyc_mux_25; // op=pyc.mux
wire [63:0] pyc_mux_27; // op=pyc.mux
wire [63:0] pyc_mux_29; // op=pyc.mux
wire [63:0] pyc_mux_31; // op=pyc.mux
wire [63:0] pyc_mux_33; // op=pyc.mux
wire [63:0] pyc_mux_35; // op=pyc.mux
wire [63:0] pyc_mux_37; // op=pyc.mux
wire [63:0] pyc_mux_39; // op=pyc.mux
wire [63:0] pyc_mux_41; // op=pyc.mux
wire [63:0] pyc_mux_43; // op=pyc.mux
wire [63:0] pyc_mux_45; // op=pyc.mux
wire [63:0] pyc_or_18; // op=pyc.or
wire [63:0] pyc_sub_16; // op=pyc.sub
wire pyc_ult_20; // op=pyc.ult
wire [63:0] pyc_xor_19; // op=pyc.xor

// --- Combinational (netlist)
assign pyc_constant_1 = 64'd1;
assign pyc_constant_2 = 64'd0;
assign pyc_constant_3 = 4'd0;
assign pyc_constant_4 = 4'd1;
assign pyc_constant_5 = 4'd2;
assign pyc_constant_6 = 4'd3;
assign pyc_constant_7 = 4'd4;
assign pyc_constant_8 = 4'd5;
assign pyc_constant_9 = 4'd6;
assign pyc_constant_10 = 4'd7;
assign pyc_constant_11 = 4'd8;
assign pyc_constant_12 = 4'd9;
assign pyc_constant_13 = 4'd10;
assign pyc_constant_14 = 4'd11;
assign pyc_add_15 = (dv_alu0_src1 + dv_alu0_src2);
assign pyc_sub_16 = (dv_alu0_src1 - dv_alu0_src2);
assign pyc_and_17 = (dv_alu0_src1 & dv_alu0_src2);
assign pyc_or_18 = (dv_alu0_src1 | dv_alu0_src2);
assign pyc_xor_19 = (dv_alu0_src1 ^ dv_alu0_src2);
assign pyc_ult_20 = (dv_alu0_src1 < dv_alu0_src2);
assign pyc_mux_21 = (pyc_ult_20 ? pyc_constant_1 : pyc_constant_2);
assign pyc_eq_22 = (dv_alu0_func == pyc_constant_3);
assign pyc_mux_23 = (pyc_eq_22 ? pyc_add_15 : pyc_constant_2);
assign pyc_eq_24 = (dv_alu0_func == pyc_constant_4);
assign pyc_mux_25 = (pyc_eq_24 ? pyc_sub_16 : pyc_mux_23);
assign pyc_eq_26 = (dv_alu0_func == pyc_constant_5);
assign pyc_mux_27 = (pyc_eq_26 ? pyc_and_17 : pyc_mux_25);
assign pyc_eq_28 = (dv_alu0_func == pyc_constant_6);
assign pyc_mux_29 = (pyc_eq_28 ? pyc_or_18 : pyc_mux_27);
assign pyc_eq_30 = (dv_alu0_func == pyc_constant_7);
assign pyc_mux_31 = (pyc_eq_30 ? pyc_xor_19 : pyc_mux_29);
assign pyc_eq_32 = (dv_alu0_func == pyc_constant_8);
assign pyc_mux_33 = (pyc_eq_32 ? dv_alu0_src1 : pyc_mux_31);
assign pyc_eq_34 = (dv_alu0_func == pyc_constant_9);
assign pyc_mux_35 = (pyc_eq_34 ? dv_alu0_src1 : pyc_mux_33);
assign pyc_eq_36 = (dv_alu0_func == pyc_constant_10);
assign pyc_mux_37 = (pyc_eq_36 ? dv_alu0_src1 : pyc_mux_35);
assign pyc_eq_38 = (dv_alu0_func == pyc_constant_11);
assign pyc_mux_39 = (pyc_eq_38 ? pyc_mux_21 : pyc_mux_37);
assign pyc_eq_40 = (dv_alu0_func == pyc_constant_12);
assign pyc_mux_41 = (pyc_eq_40 ? pyc_mux_21 : pyc_mux_39);
assign pyc_eq_42 = (dv_alu0_func == pyc_constant_13);
assign pyc_mux_43 = (pyc_eq_42 ? dv_alu0_src2 : pyc_mux_41);
assign pyc_eq_44 = (dv_alu0_func == pyc_constant_14);
assign pyc_mux_45 = (pyc_eq_44 ? dv_alu0_src1 : pyc_mux_43);
assign pyc_comb_46 = pyc_mux_45;

assign dv_alu0_result_valid = dv_alu0_valid;
assign dv_alu0_result_tag = dv_alu0_pdst;
assign dv_alu0_result_data = pyc_comb_46;

endmodule

