// Generated by pycc (pyCircuit)
// Module: bru

module bru (
  input clk,
  input rst,
  input dv_bru_valid,
  input [2:0] dv_bru_func,
  input [63:0] dv_bru_src1,
  input [63:0] dv_bru_src2,
  input dv_bru_predicted,
  input [63:0] dv_bru_pc,
  input [63:0] dv_bru_offset,
  input [6:0] dv_bru_pdst,
  input [2:0] dv_bru_ckpt,
  output dv_bru_mispredict,
  output dv_bru_taken,
  output [63:0] dv_bru_target,
  output [2:0] dv_bru_ckpt_id,
  output dv_bru_result_valid,
  output [6:0] dv_bru_result_tag,
  output [63:0] dv_bru_result_data,
  output dv_bru_dealloc_valid
);

wire [63:0] pyc_add_32; // op=pyc.add
wire [63:0] pyc_add_33; // op=pyc.add
wire [63:0] pyc_add_35; // op=pyc.add
wire pyc_and_13; // op=pyc.and
wire pyc_and_31; // op=pyc.and
wire pyc_and_37; // op=pyc.and
wire pyc_and_39; // op=pyc.and
wire pyc_comb_40; // op=pyc.comb
wire pyc_comb_41; // op=pyc.comb
wire [63:0] pyc_comb_42; // op=pyc.comb
wire [63:0] pyc_comb_43; // op=pyc.comb
wire pyc_comb_44; // op=pyc.comb
wire pyc_comb_45; // op=pyc.comb
wire [2:0] pyc_constant_1; // op=pyc.constant
wire [2:0] pyc_constant_2; // op=pyc.constant
wire [2:0] pyc_constant_3; // op=pyc.constant
wire [2:0] pyc_constant_4; // op=pyc.constant
wire [2:0] pyc_constant_5; // op=pyc.constant
wire [2:0] pyc_constant_6; // op=pyc.constant
wire [2:0] pyc_constant_7; // op=pyc.constant
wire [2:0] pyc_constant_8; // op=pyc.constant
wire [63:0] pyc_constant_9; // op=pyc.constant
wire pyc_eq_10; // op=pyc.eq
wire pyc_eq_12; // op=pyc.eq
wire pyc_eq_14; // op=pyc.eq
wire pyc_eq_17; // op=pyc.eq
wire pyc_eq_19; // op=pyc.eq
wire pyc_eq_22; // op=pyc.eq
wire pyc_eq_24; // op=pyc.eq
wire pyc_eq_26; // op=pyc.eq
wire pyc_eq_28; // op=pyc.eq
wire pyc_mux_16; // op=pyc.mux
wire pyc_mux_18; // op=pyc.mux
wire pyc_mux_21; // op=pyc.mux
wire pyc_mux_23; // op=pyc.mux
wire pyc_mux_25; // op=pyc.mux
wire [63:0] pyc_mux_34; // op=pyc.mux
wire pyc_not_15; // op=pyc.not
wire pyc_not_20; // op=pyc.not
wire pyc_not_38; // op=pyc.not
wire pyc_or_27; // op=pyc.or
wire pyc_or_29; // op=pyc.or
wire pyc_or_36; // op=pyc.or
wire pyc_ult_11; // op=pyc.ult
wire pyc_xor_30; // op=pyc.xor

// --- Combinational (netlist)
assign pyc_constant_1 = 3'd0;
assign pyc_constant_2 = 3'd1;
assign pyc_constant_3 = 3'd2;
assign pyc_constant_4 = 3'd3;
assign pyc_constant_5 = 3'd4;
assign pyc_constant_6 = 3'd5;
assign pyc_constant_7 = 3'd6;
assign pyc_constant_8 = 3'd7;
assign pyc_constant_9 = 64'd4;
assign pyc_eq_10 = (dv_bru_src1 == dv_bru_src2);
assign pyc_ult_11 = (dv_bru_src1 < dv_bru_src2);
assign pyc_eq_12 = (dv_bru_func == pyc_constant_1);
assign pyc_and_13 = (pyc_eq_12 & pyc_eq_10);
assign pyc_eq_14 = (dv_bru_func == pyc_constant_2);
assign pyc_not_15 = (~pyc_eq_10);
assign pyc_mux_16 = (pyc_eq_14 ? pyc_not_15 : pyc_and_13);
assign pyc_eq_17 = (dv_bru_func == pyc_constant_3);
assign pyc_mux_18 = (pyc_eq_17 ? pyc_ult_11 : pyc_mux_16);
assign pyc_eq_19 = (dv_bru_func == pyc_constant_4);
assign pyc_not_20 = (~pyc_ult_11);
assign pyc_mux_21 = (pyc_eq_19 ? pyc_not_20 : pyc_mux_18);
assign pyc_eq_22 = (dv_bru_func == pyc_constant_5);
assign pyc_mux_23 = (pyc_eq_22 ? pyc_ult_11 : pyc_mux_21);
assign pyc_eq_24 = (dv_bru_func == pyc_constant_6);
assign pyc_mux_25 = (pyc_eq_24 ? pyc_not_20 : pyc_mux_23);
assign pyc_eq_26 = (dv_bru_func == pyc_constant_7);
assign pyc_or_27 = (pyc_eq_26 | pyc_mux_25);
assign pyc_eq_28 = (dv_bru_func == pyc_constant_8);
assign pyc_or_29 = (pyc_eq_28 | pyc_or_27);
assign pyc_xor_30 = (pyc_or_29 ^ dv_bru_predicted);
assign pyc_and_31 = (dv_bru_valid & pyc_xor_30);
assign pyc_add_32 = (dv_bru_pc + dv_bru_offset);
assign pyc_add_33 = (dv_bru_src1 + dv_bru_offset);
assign pyc_mux_34 = (pyc_eq_28 ? pyc_add_33 : pyc_add_32);
assign pyc_add_35 = (dv_bru_pc + pyc_constant_9);
assign pyc_or_36 = (pyc_eq_26 | pyc_eq_28);
assign pyc_and_37 = (dv_bru_valid & pyc_or_36);
assign pyc_not_38 = (~pyc_and_31);
assign pyc_and_39 = (dv_bru_valid & pyc_not_38);
assign pyc_comb_40 = pyc_or_29;
assign pyc_comb_41 = pyc_and_31;
assign pyc_comb_42 = pyc_mux_34;
assign pyc_comb_43 = pyc_add_35;
assign pyc_comb_44 = pyc_and_37;
assign pyc_comb_45 = pyc_and_39;

assign dv_bru_mispredict = pyc_comb_41;
assign dv_bru_taken = pyc_comb_40;
assign dv_bru_target = pyc_comb_42;
assign dv_bru_ckpt_id = dv_bru_ckpt;
assign dv_bru_result_valid = pyc_comb_44;
assign dv_bru_result_tag = dv_bru_pdst;
assign dv_bru_result_data = pyc_comb_43;
assign dv_bru_dealloc_valid = pyc_comb_45;

endmodule

