// Generated by pycc (pyCircuit)
// Module: cube_rs

module cube_rs (
  input clk,
  input rst,
  input dv_crs_dv0,
  input dv_crs_dv1,
  input dv_crs_dv2,
  input dv_crs_dv3,
  input [7:0] dv_crs_dop0,
  input [7:0] dv_crs_dop1,
  input [7:0] dv_crs_dop2,
  input [7:0] dv_crs_dop3,
  input [7:0] dv_crs_dts0_0,
  input [7:0] dv_crs_dts0_1,
  input [7:0] dv_crs_dts0_2,
  input [7:0] dv_crs_dts0_3,
  input [7:0] dv_crs_dts1_0,
  input [7:0] dv_crs_dts1_1,
  input [7:0] dv_crs_dts1_2,
  input [7:0] dv_crs_dts1_3,
  input dv_crs_dtr0_0,
  input dv_crs_dtr0_1,
  input dv_crs_dtr0_2,
  input dv_crs_dtr0_3,
  input dv_crs_dtr1_0,
  input dv_crs_dtr1_1,
  input dv_crs_dtr1_2,
  input dv_crs_dtr1_3,
  input [7:0] dv_crs_dtd0,
  input [7:0] dv_crs_dtd1,
  input [7:0] dv_crs_dtd2,
  input [7:0] dv_crs_dtd3,
  input dv_crs_tcb_v0,
  input dv_crs_tcb_v1,
  input dv_crs_tcb_v2,
  input dv_crs_tcb_v3,
  input [7:0] dv_crs_tcb_t0,
  input [7:0] dv_crs_tcb_t1,
  input [7:0] dv_crs_tcb_t2,
  input [7:0] dv_crs_tcb_t3,
  input dv_crs_flush,
  output dv_crs_issue_valid,
  output [1:0] dv_crs_issue_idx,
  output [7:0] dv_crs_issue_op,
  output [7:0] dv_crs_issue_ptdst,
  output dv_crs_full
);

wire [5:0] dv_crs_ac; // pyc.name="dv_crs_ac"
wire [5:0] dv_crs_ac__next; // pyc.name="dv_crs_ac__next"
wire [5:0] dv_crs_ag_0; // pyc.name="dv_crs_ag_0"
wire [5:0] dv_crs_ag_0__next; // pyc.name="dv_crs_ag_0__next"
wire [5:0] dv_crs_ag_1; // pyc.name="dv_crs_ag_1"
wire [5:0] dv_crs_ag_1__next; // pyc.name="dv_crs_ag_1__next"
wire [5:0] dv_crs_ag_2; // pyc.name="dv_crs_ag_2"
wire [5:0] dv_crs_ag_2__next; // pyc.name="dv_crs_ag_2__next"
wire [5:0] dv_crs_ag_3; // pyc.name="dv_crs_ag_3"
wire [5:0] dv_crs_ag_3__next; // pyc.name="dv_crs_ag_3__next"
wire [7:0] dv_crs_op_0; // pyc.name="dv_crs_op_0"
wire [7:0] dv_crs_op_0__next; // pyc.name="dv_crs_op_0__next"
wire [7:0] dv_crs_op_1; // pyc.name="dv_crs_op_1"
wire [7:0] dv_crs_op_1__next; // pyc.name="dv_crs_op_1__next"
wire [7:0] dv_crs_op_2; // pyc.name="dv_crs_op_2"
wire [7:0] dv_crs_op_2__next; // pyc.name="dv_crs_op_2__next"
wire [7:0] dv_crs_op_3; // pyc.name="dv_crs_op_3"
wire [7:0] dv_crs_op_3__next; // pyc.name="dv_crs_op_3__next"
wire [7:0] dv_crs_td_0; // pyc.name="dv_crs_td_0"
wire [7:0] dv_crs_td_0__next; // pyc.name="dv_crs_td_0__next"
wire [7:0] dv_crs_td_1; // pyc.name="dv_crs_td_1"
wire [7:0] dv_crs_td_1__next; // pyc.name="dv_crs_td_1__next"
wire [7:0] dv_crs_td_2; // pyc.name="dv_crs_td_2"
wire [7:0] dv_crs_td_2__next; // pyc.name="dv_crs_td_2__next"
wire [7:0] dv_crs_td_3; // pyc.name="dv_crs_td_3"
wire [7:0] dv_crs_td_3__next; // pyc.name="dv_crs_td_3__next"
wire dv_crs_tr0_0; // pyc.name="dv_crs_tr0_0"
wire dv_crs_tr0_0__next; // pyc.name="dv_crs_tr0_0__next"
wire dv_crs_tr0_1; // pyc.name="dv_crs_tr0_1"
wire dv_crs_tr0_1__next; // pyc.name="dv_crs_tr0_1__next"
wire dv_crs_tr0_2; // pyc.name="dv_crs_tr0_2"
wire dv_crs_tr0_2__next; // pyc.name="dv_crs_tr0_2__next"
wire dv_crs_tr0_3; // pyc.name="dv_crs_tr0_3"
wire dv_crs_tr0_3__next; // pyc.name="dv_crs_tr0_3__next"
wire dv_crs_tr1_0; // pyc.name="dv_crs_tr1_0"
wire dv_crs_tr1_0__next; // pyc.name="dv_crs_tr1_0__next"
wire dv_crs_tr1_1; // pyc.name="dv_crs_tr1_1"
wire dv_crs_tr1_1__next; // pyc.name="dv_crs_tr1_1__next"
wire dv_crs_tr1_2; // pyc.name="dv_crs_tr1_2"
wire dv_crs_tr1_2__next; // pyc.name="dv_crs_tr1_2__next"
wire dv_crs_tr1_3; // pyc.name="dv_crs_tr1_3"
wire dv_crs_tr1_3__next; // pyc.name="dv_crs_tr1_3__next"
wire [7:0] dv_crs_ts0_0; // pyc.name="dv_crs_ts0_0"
wire [7:0] dv_crs_ts0_0__next; // pyc.name="dv_crs_ts0_0__next"
wire [7:0] dv_crs_ts0_1; // pyc.name="dv_crs_ts0_1"
wire [7:0] dv_crs_ts0_1__next; // pyc.name="dv_crs_ts0_1__next"
wire [7:0] dv_crs_ts0_2; // pyc.name="dv_crs_ts0_2"
wire [7:0] dv_crs_ts0_2__next; // pyc.name="dv_crs_ts0_2__next"
wire [7:0] dv_crs_ts0_3; // pyc.name="dv_crs_ts0_3"
wire [7:0] dv_crs_ts0_3__next; // pyc.name="dv_crs_ts0_3__next"
wire [7:0] dv_crs_ts1_0; // pyc.name="dv_crs_ts1_0"
wire [7:0] dv_crs_ts1_0__next; // pyc.name="dv_crs_ts1_0__next"
wire [7:0] dv_crs_ts1_1; // pyc.name="dv_crs_ts1_1"
wire [7:0] dv_crs_ts1_1__next; // pyc.name="dv_crs_ts1_1__next"
wire [7:0] dv_crs_ts1_2; // pyc.name="dv_crs_ts1_2"
wire [7:0] dv_crs_ts1_2__next; // pyc.name="dv_crs_ts1_2__next"
wire [7:0] dv_crs_ts1_3; // pyc.name="dv_crs_ts1_3"
wire [7:0] dv_crs_ts1_3__next; // pyc.name="dv_crs_ts1_3__next"
wire dv_crs_v_0; // pyc.name="dv_crs_v_0"
wire dv_crs_v_0__next; // pyc.name="dv_crs_v_0__next"
wire dv_crs_v_1; // pyc.name="dv_crs_v_1"
wire dv_crs_v_1__next; // pyc.name="dv_crs_v_1__next"
wire dv_crs_v_2; // pyc.name="dv_crs_v_2"
wire dv_crs_v_2__next; // pyc.name="dv_crs_v_2__next"
wire dv_crs_v_3; // pyc.name="dv_crs_v_3"
wire dv_crs_v_3__next; // pyc.name="dv_crs_v_3__next"
wire [2:0] pyc_add_278; // op=pyc.add
wire [2:0] pyc_add_280; // op=pyc.add
wire [2:0] pyc_add_282; // op=pyc.add
wire [5:0] pyc_add_285; // op=pyc.add
wire pyc_and_101; // op=pyc.and
wire pyc_and_104; // op=pyc.and
wire pyc_and_106; // op=pyc.and
wire pyc_and_109; // op=pyc.and
wire pyc_and_111; // op=pyc.and
wire pyc_and_114; // op=pyc.and
wire pyc_and_116; // op=pyc.and
wire pyc_and_119; // op=pyc.and
wire pyc_and_121; // op=pyc.and
wire pyc_and_124; // op=pyc.and
wire pyc_and_126; // op=pyc.and
wire pyc_and_129; // op=pyc.and
wire pyc_and_131; // op=pyc.and
wire pyc_and_134; // op=pyc.and
wire pyc_and_136; // op=pyc.and
wire pyc_and_139; // op=pyc.and
wire pyc_and_141; // op=pyc.and
wire pyc_and_144; // op=pyc.and
wire pyc_and_146; // op=pyc.and
wire pyc_and_149; // op=pyc.and
wire pyc_and_151; // op=pyc.and
wire pyc_and_154; // op=pyc.and
wire pyc_and_156; // op=pyc.and
wire pyc_and_159; // op=pyc.and
wire pyc_and_161; // op=pyc.and
wire pyc_and_164; // op=pyc.and
wire pyc_and_166; // op=pyc.and
wire pyc_and_169; // op=pyc.and
wire pyc_and_171; // op=pyc.and
wire pyc_and_174; // op=pyc.and
wire pyc_and_176; // op=pyc.and
wire pyc_and_179; // op=pyc.and
wire pyc_and_181; // op=pyc.and
wire pyc_and_184; // op=pyc.and
wire pyc_and_186; // op=pyc.and
wire pyc_and_189; // op=pyc.and
wire pyc_and_191; // op=pyc.and
wire pyc_and_194; // op=pyc.and
wire pyc_and_196; // op=pyc.and
wire pyc_and_199; // op=pyc.and
wire pyc_and_201; // op=pyc.and
wire pyc_and_204; // op=pyc.and
wire pyc_and_206; // op=pyc.and
wire pyc_and_209; // op=pyc.and
wire pyc_and_211; // op=pyc.and
wire pyc_and_214; // op=pyc.and
wire pyc_and_216; // op=pyc.and
wire pyc_and_219; // op=pyc.and
wire pyc_and_221; // op=pyc.and
wire pyc_and_224; // op=pyc.and
wire pyc_and_226; // op=pyc.and
wire pyc_and_229; // op=pyc.and
wire pyc_and_231; // op=pyc.and
wire pyc_and_234; // op=pyc.and
wire pyc_and_236; // op=pyc.and
wire pyc_and_238; // op=pyc.and
wire pyc_and_239; // op=pyc.and
wire pyc_and_241; // op=pyc.and
wire pyc_and_242; // op=pyc.and
wire pyc_and_246; // op=pyc.and
wire pyc_and_250; // op=pyc.and
wire pyc_and_251; // op=pyc.and
wire pyc_and_255; // op=pyc.and
wire pyc_and_259; // op=pyc.and
wire pyc_and_260; // op=pyc.and
wire pyc_and_264; // op=pyc.and
wire pyc_and_305; // op=pyc.and
wire pyc_and_307; // op=pyc.and
wire pyc_and_309; // op=pyc.and
wire pyc_and_318; // op=pyc.and
wire pyc_and_320; // op=pyc.and
wire pyc_and_321; // op=pyc.and
wire pyc_and_323; // op=pyc.and
wire pyc_and_331; // op=pyc.and
wire pyc_and_333; // op=pyc.and
wire pyc_and_334; // op=pyc.and
wire pyc_and_336; // op=pyc.and
wire pyc_and_344; // op=pyc.and
wire pyc_and_346; // op=pyc.and
wire pyc_and_347; // op=pyc.and
wire pyc_and_349; // op=pyc.and
wire pyc_and_357; // op=pyc.and
wire pyc_and_360; // op=pyc.and
wire pyc_and_373; // op=pyc.and
wire pyc_and_386; // op=pyc.and
wire pyc_and_399; // op=pyc.and
wire pyc_and_411; // op=pyc.and
wire pyc_and_422; // op=pyc.and
wire pyc_and_433; // op=pyc.and
wire pyc_and_444; // op=pyc.and
wire pyc_and_455; // op=pyc.and
wire pyc_and_466; // op=pyc.and
wire pyc_and_477; // op=pyc.and
wire pyc_and_488; // op=pyc.and
wire pyc_and_499; // op=pyc.and
wire pyc_and_510; // op=pyc.and
wire pyc_and_521; // op=pyc.and
wire pyc_and_532; // op=pyc.and
wire pyc_and_79; // op=pyc.and
wire pyc_and_81; // op=pyc.and
wire pyc_and_84; // op=pyc.and
wire pyc_and_86; // op=pyc.and
wire pyc_and_89; // op=pyc.and
wire pyc_and_91; // op=pyc.and
wire pyc_and_94; // op=pyc.and
wire pyc_and_96; // op=pyc.and
wire pyc_and_99; // op=pyc.and
wire pyc_comb_12; // op=pyc.comb
wire pyc_comb_13; // op=pyc.comb
wire [7:0] pyc_comb_14; // op=pyc.comb
wire [5:0] pyc_comb_15; // op=pyc.comb
wire [1:0] pyc_comb_16; // op=pyc.comb
wire [5:0] pyc_comb_17; // op=pyc.comb
wire [1:0] pyc_comb_18; // op=pyc.comb
wire [1:0] pyc_comb_19; // op=pyc.comb
wire [1:0] pyc_comb_20; // op=pyc.comb
wire [2:0] pyc_comb_21; // op=pyc.comb
wire [5:0] pyc_comb_22; // op=pyc.comb
wire [3:0] pyc_comb_25; // op=pyc.comb
wire [3:0] pyc_comb_26; // op=pyc.comb
wire [5:0] pyc_comb_286; // op=pyc.comb
wire pyc_comb_287; // op=pyc.comb
wire pyc_comb_288; // op=pyc.comb
wire pyc_comb_289; // op=pyc.comb
wire pyc_comb_290; // op=pyc.comb
wire pyc_comb_291; // op=pyc.comb
wire pyc_comb_292; // op=pyc.comb
wire pyc_comb_293; // op=pyc.comb
wire pyc_comb_294; // op=pyc.comb
wire pyc_comb_295; // op=pyc.comb
wire [1:0] pyc_comb_296; // op=pyc.comb
wire pyc_comb_297; // op=pyc.comb
wire pyc_comb_298; // op=pyc.comb
wire pyc_comb_299; // op=pyc.comb
wire [7:0] pyc_comb_300; // op=pyc.comb
wire [7:0] pyc_comb_301; // op=pyc.comb
wire pyc_comb_302; // op=pyc.comb
wire [5:0] pyc_comb_303; // op=pyc.comb
wire pyc_comb_311; // op=pyc.comb
wire pyc_comb_312; // op=pyc.comb
wire pyc_comb_313; // op=pyc.comb
wire pyc_comb_314; // op=pyc.comb
wire pyc_comb_319; // op=pyc.comb
wire pyc_comb_32; // op=pyc.comb
wire pyc_comb_325; // op=pyc.comb
wire pyc_comb_326; // op=pyc.comb
wire pyc_comb_327; // op=pyc.comb
wire pyc_comb_33; // op=pyc.comb
wire pyc_comb_332; // op=pyc.comb
wire pyc_comb_338; // op=pyc.comb
wire pyc_comb_339; // op=pyc.comb
wire pyc_comb_34; // op=pyc.comb
wire pyc_comb_340; // op=pyc.comb
wire pyc_comb_345; // op=pyc.comb
wire pyc_comb_35; // op=pyc.comb
wire pyc_comb_351; // op=pyc.comb
wire pyc_comb_352; // op=pyc.comb
wire pyc_comb_353; // op=pyc.comb
wire pyc_comb_358; // op=pyc.comb
wire pyc_comb_362; // op=pyc.comb
wire pyc_comb_363; // op=pyc.comb
wire pyc_comb_364; // op=pyc.comb
wire pyc_comb_375; // op=pyc.comb
wire pyc_comb_376; // op=pyc.comb
wire pyc_comb_377; // op=pyc.comb
wire pyc_comb_388; // op=pyc.comb
wire pyc_comb_389; // op=pyc.comb
wire pyc_comb_390; // op=pyc.comb
wire pyc_comb_401; // op=pyc.comb
wire pyc_comb_402; // op=pyc.comb
wire pyc_comb_403; // op=pyc.comb
wire pyc_comb_413; // op=pyc.comb
wire pyc_comb_414; // op=pyc.comb
wire pyc_comb_424; // op=pyc.comb
wire pyc_comb_425; // op=pyc.comb
wire pyc_comb_435; // op=pyc.comb
wire pyc_comb_436; // op=pyc.comb
wire pyc_comb_446; // op=pyc.comb
wire pyc_comb_447; // op=pyc.comb
wire pyc_comb_457; // op=pyc.comb
wire pyc_comb_458; // op=pyc.comb
wire pyc_comb_468; // op=pyc.comb
wire pyc_comb_469; // op=pyc.comb
wire pyc_comb_479; // op=pyc.comb
wire pyc_comb_480; // op=pyc.comb
wire pyc_comb_490; // op=pyc.comb
wire pyc_comb_491; // op=pyc.comb
wire pyc_comb_501; // op=pyc.comb
wire pyc_comb_502; // op=pyc.comb
wire pyc_comb_512; // op=pyc.comb
wire pyc_comb_513; // op=pyc.comb
wire pyc_comb_523; // op=pyc.comb
wire pyc_comb_524; // op=pyc.comb
wire pyc_comb_534; // op=pyc.comb
wire pyc_comb_535; // op=pyc.comb
wire [7:0] pyc_comb_54; // op=pyc.comb
wire [7:0] pyc_comb_55; // op=pyc.comb
wire pyc_comb_65; // op=pyc.comb
wire pyc_comb_66; // op=pyc.comb
wire pyc_comb_67; // op=pyc.comb
wire pyc_comb_68; // op=pyc.comb
wire pyc_comb_69; // op=pyc.comb
wire pyc_comb_70; // op=pyc.comb
wire pyc_comb_71; // op=pyc.comb
wire pyc_comb_72; // op=pyc.comb
wire [3:0] pyc_concat_23; // op=pyc.concat
wire [3:0] pyc_concat_24; // op=pyc.concat
wire [7:0] pyc_concat_52; // op=pyc.concat
wire [7:0] pyc_concat_53; // op=pyc.concat
wire pyc_constant_1; // op=pyc.constant
wire [2:0] pyc_constant_10; // op=pyc.constant
wire [5:0] pyc_constant_11; // op=pyc.constant
wire pyc_constant_2; // op=pyc.constant
wire [7:0] pyc_constant_3; // op=pyc.constant
wire [5:0] pyc_constant_4; // op=pyc.constant
wire [1:0] pyc_constant_5; // op=pyc.constant
wire [5:0] pyc_constant_6; // op=pyc.constant
wire [1:0] pyc_constant_7; // op=pyc.constant
wire [1:0] pyc_constant_8; // op=pyc.constant
wire [1:0] pyc_constant_9; // op=pyc.constant
wire pyc_eq_103; // op=pyc.eq
wire pyc_eq_108; // op=pyc.eq
wire pyc_eq_113; // op=pyc.eq
wire pyc_eq_118; // op=pyc.eq
wire pyc_eq_123; // op=pyc.eq
wire pyc_eq_128; // op=pyc.eq
wire pyc_eq_133; // op=pyc.eq
wire pyc_eq_138; // op=pyc.eq
wire pyc_eq_143; // op=pyc.eq
wire pyc_eq_148; // op=pyc.eq
wire pyc_eq_153; // op=pyc.eq
wire pyc_eq_158; // op=pyc.eq
wire pyc_eq_163; // op=pyc.eq
wire pyc_eq_168; // op=pyc.eq
wire pyc_eq_173; // op=pyc.eq
wire pyc_eq_178; // op=pyc.eq
wire pyc_eq_183; // op=pyc.eq
wire pyc_eq_188; // op=pyc.eq
wire pyc_eq_193; // op=pyc.eq
wire pyc_eq_198; // op=pyc.eq
wire pyc_eq_203; // op=pyc.eq
wire pyc_eq_208; // op=pyc.eq
wire pyc_eq_213; // op=pyc.eq
wire pyc_eq_218; // op=pyc.eq
wire pyc_eq_223; // op=pyc.eq
wire pyc_eq_228; // op=pyc.eq
wire pyc_eq_233; // op=pyc.eq
wire pyc_eq_267; // op=pyc.eq
wire pyc_eq_270; // op=pyc.eq
wire pyc_eq_273; // op=pyc.eq
wire pyc_eq_304; // op=pyc.eq
wire pyc_eq_78; // op=pyc.eq
wire pyc_eq_83; // op=pyc.eq
wire pyc_eq_88; // op=pyc.eq
wire pyc_eq_93; // op=pyc.eq
wire pyc_eq_98; // op=pyc.eq
wire pyc_extract_28; // op=pyc.extract
wire pyc_extract_29; // op=pyc.extract
wire pyc_extract_30; // op=pyc.extract
wire pyc_extract_31; // op=pyc.extract
wire pyc_extract_57; // op=pyc.extract
wire pyc_extract_58; // op=pyc.extract
wire pyc_extract_59; // op=pyc.extract
wire pyc_extract_60; // op=pyc.extract
wire pyc_extract_61; // op=pyc.extract
wire pyc_extract_62; // op=pyc.extract
wire pyc_extract_63; // op=pyc.extract
wire pyc_extract_64; // op=pyc.extract
wire [5:0] pyc_mux_240; // op=pyc.mux
wire [1:0] pyc_mux_248; // op=pyc.mux
wire [5:0] pyc_mux_249; // op=pyc.mux
wire [1:0] pyc_mux_257; // op=pyc.mux
wire [5:0] pyc_mux_258; // op=pyc.mux
wire [1:0] pyc_mux_266; // op=pyc.mux
wire [7:0] pyc_mux_268; // op=pyc.mux
wire [7:0] pyc_mux_269; // op=pyc.mux
wire [7:0] pyc_mux_271; // op=pyc.mux
wire [7:0] pyc_mux_272; // op=pyc.mux
wire [7:0] pyc_mux_274; // op=pyc.mux
wire [7:0] pyc_mux_275; // op=pyc.mux
wire pyc_mux_310; // op=pyc.mux
wire pyc_mux_315; // op=pyc.mux
wire pyc_mux_324; // op=pyc.mux
wire pyc_mux_328; // op=pyc.mux
wire pyc_mux_337; // op=pyc.mux
wire pyc_mux_341; // op=pyc.mux
wire pyc_mux_350; // op=pyc.mux
wire pyc_mux_354; // op=pyc.mux
wire [7:0] pyc_mux_365; // op=pyc.mux
wire [5:0] pyc_mux_366; // op=pyc.mux
wire [7:0] pyc_mux_367; // op=pyc.mux
wire [7:0] pyc_mux_368; // op=pyc.mux
wire pyc_mux_369; // op=pyc.mux
wire [7:0] pyc_mux_370; // op=pyc.mux
wire pyc_mux_371; // op=pyc.mux
wire [7:0] pyc_mux_378; // op=pyc.mux
wire [5:0] pyc_mux_379; // op=pyc.mux
wire [7:0] pyc_mux_380; // op=pyc.mux
wire [7:0] pyc_mux_381; // op=pyc.mux
wire pyc_mux_382; // op=pyc.mux
wire [7:0] pyc_mux_383; // op=pyc.mux
wire pyc_mux_384; // op=pyc.mux
wire [7:0] pyc_mux_391; // op=pyc.mux
wire [5:0] pyc_mux_392; // op=pyc.mux
wire [7:0] pyc_mux_393; // op=pyc.mux
wire [7:0] pyc_mux_394; // op=pyc.mux
wire pyc_mux_395; // op=pyc.mux
wire [7:0] pyc_mux_396; // op=pyc.mux
wire pyc_mux_397; // op=pyc.mux
wire [7:0] pyc_mux_404; // op=pyc.mux
wire [5:0] pyc_mux_405; // op=pyc.mux
wire [7:0] pyc_mux_406; // op=pyc.mux
wire [7:0] pyc_mux_407; // op=pyc.mux
wire pyc_mux_408; // op=pyc.mux
wire [7:0] pyc_mux_409; // op=pyc.mux
wire pyc_mux_410; // op=pyc.mux
wire [7:0] pyc_mux_415; // op=pyc.mux
wire [5:0] pyc_mux_416; // op=pyc.mux
wire [7:0] pyc_mux_417; // op=pyc.mux
wire [7:0] pyc_mux_418; // op=pyc.mux
wire pyc_mux_419; // op=pyc.mux
wire [7:0] pyc_mux_420; // op=pyc.mux
wire pyc_mux_421; // op=pyc.mux
wire [7:0] pyc_mux_426; // op=pyc.mux
wire [5:0] pyc_mux_427; // op=pyc.mux
wire [7:0] pyc_mux_428; // op=pyc.mux
wire [7:0] pyc_mux_429; // op=pyc.mux
wire pyc_mux_430; // op=pyc.mux
wire [7:0] pyc_mux_431; // op=pyc.mux
wire pyc_mux_432; // op=pyc.mux
wire [7:0] pyc_mux_437; // op=pyc.mux
wire [5:0] pyc_mux_438; // op=pyc.mux
wire [7:0] pyc_mux_439; // op=pyc.mux
wire [7:0] pyc_mux_440; // op=pyc.mux
wire pyc_mux_441; // op=pyc.mux
wire [7:0] pyc_mux_442; // op=pyc.mux
wire pyc_mux_443; // op=pyc.mux
wire [7:0] pyc_mux_448; // op=pyc.mux
wire [5:0] pyc_mux_449; // op=pyc.mux
wire [7:0] pyc_mux_450; // op=pyc.mux
wire [7:0] pyc_mux_451; // op=pyc.mux
wire pyc_mux_452; // op=pyc.mux
wire [7:0] pyc_mux_453; // op=pyc.mux
wire pyc_mux_454; // op=pyc.mux
wire [7:0] pyc_mux_459; // op=pyc.mux
wire [5:0] pyc_mux_460; // op=pyc.mux
wire [7:0] pyc_mux_461; // op=pyc.mux
wire [7:0] pyc_mux_462; // op=pyc.mux
wire pyc_mux_463; // op=pyc.mux
wire [7:0] pyc_mux_464; // op=pyc.mux
wire pyc_mux_465; // op=pyc.mux
wire [7:0] pyc_mux_470; // op=pyc.mux
wire [5:0] pyc_mux_471; // op=pyc.mux
wire [7:0] pyc_mux_472; // op=pyc.mux
wire [7:0] pyc_mux_473; // op=pyc.mux
wire pyc_mux_474; // op=pyc.mux
wire [7:0] pyc_mux_475; // op=pyc.mux
wire pyc_mux_476; // op=pyc.mux
wire [7:0] pyc_mux_481; // op=pyc.mux
wire [5:0] pyc_mux_482; // op=pyc.mux
wire [7:0] pyc_mux_483; // op=pyc.mux
wire [7:0] pyc_mux_484; // op=pyc.mux
wire pyc_mux_485; // op=pyc.mux
wire [7:0] pyc_mux_486; // op=pyc.mux
wire pyc_mux_487; // op=pyc.mux
wire [7:0] pyc_mux_492; // op=pyc.mux
wire [5:0] pyc_mux_493; // op=pyc.mux
wire [7:0] pyc_mux_494; // op=pyc.mux
wire [7:0] pyc_mux_495; // op=pyc.mux
wire pyc_mux_496; // op=pyc.mux
wire [7:0] pyc_mux_497; // op=pyc.mux
wire pyc_mux_498; // op=pyc.mux
wire [7:0] pyc_mux_503; // op=pyc.mux
wire [5:0] pyc_mux_504; // op=pyc.mux
wire [7:0] pyc_mux_505; // op=pyc.mux
wire [7:0] pyc_mux_506; // op=pyc.mux
wire pyc_mux_507; // op=pyc.mux
wire [7:0] pyc_mux_508; // op=pyc.mux
wire pyc_mux_509; // op=pyc.mux
wire [7:0] pyc_mux_514; // op=pyc.mux
wire [5:0] pyc_mux_515; // op=pyc.mux
wire [7:0] pyc_mux_516; // op=pyc.mux
wire [7:0] pyc_mux_517; // op=pyc.mux
wire pyc_mux_518; // op=pyc.mux
wire [7:0] pyc_mux_519; // op=pyc.mux
wire pyc_mux_520; // op=pyc.mux
wire [7:0] pyc_mux_525; // op=pyc.mux
wire [5:0] pyc_mux_526; // op=pyc.mux
wire [7:0] pyc_mux_527; // op=pyc.mux
wire [7:0] pyc_mux_528; // op=pyc.mux
wire pyc_mux_529; // op=pyc.mux
wire [7:0] pyc_mux_530; // op=pyc.mux
wire pyc_mux_531; // op=pyc.mux
wire [7:0] pyc_mux_536; // op=pyc.mux
wire [5:0] pyc_mux_537; // op=pyc.mux
wire [7:0] pyc_mux_538; // op=pyc.mux
wire [7:0] pyc_mux_539; // op=pyc.mux
wire pyc_mux_540; // op=pyc.mux
wire [7:0] pyc_mux_541; // op=pyc.mux
wire pyc_mux_542; // op=pyc.mux
wire pyc_not_100; // op=pyc.not
wire pyc_not_105; // op=pyc.not
wire pyc_not_110; // op=pyc.not
wire pyc_not_115; // op=pyc.not
wire pyc_not_120; // op=pyc.not
wire pyc_not_125; // op=pyc.not
wire pyc_not_130; // op=pyc.not
wire pyc_not_135; // op=pyc.not
wire pyc_not_140; // op=pyc.not
wire pyc_not_145; // op=pyc.not
wire pyc_not_150; // op=pyc.not
wire pyc_not_155; // op=pyc.not
wire pyc_not_160; // op=pyc.not
wire pyc_not_165; // op=pyc.not
wire pyc_not_170; // op=pyc.not
wire pyc_not_175; // op=pyc.not
wire pyc_not_180; // op=pyc.not
wire pyc_not_185; // op=pyc.not
wire pyc_not_190; // op=pyc.not
wire pyc_not_195; // op=pyc.not
wire pyc_not_200; // op=pyc.not
wire pyc_not_205; // op=pyc.not
wire pyc_not_210; // op=pyc.not
wire pyc_not_215; // op=pyc.not
wire pyc_not_220; // op=pyc.not
wire pyc_not_225; // op=pyc.not
wire pyc_not_230; // op=pyc.not
wire pyc_not_235; // op=pyc.not
wire pyc_not_244; // op=pyc.not
wire pyc_not_253; // op=pyc.not
wire pyc_not_262; // op=pyc.not
wire pyc_not_284; // op=pyc.not
wire pyc_not_306; // op=pyc.not
wire pyc_not_308; // op=pyc.not
wire pyc_not_317; // op=pyc.not
wire pyc_not_322; // op=pyc.not
wire pyc_not_330; // op=pyc.not
wire pyc_not_335; // op=pyc.not
wire pyc_not_343; // op=pyc.not
wire pyc_not_348; // op=pyc.not
wire pyc_not_356; // op=pyc.not
wire pyc_not_359; // op=pyc.not
wire pyc_not_372; // op=pyc.not
wire pyc_not_385; // op=pyc.not
wire pyc_not_398; // op=pyc.not
wire pyc_not_80; // op=pyc.not
wire pyc_not_85; // op=pyc.not
wire pyc_not_90; // op=pyc.not
wire pyc_not_95; // op=pyc.not
wire pyc_or_102; // op=pyc.or
wire pyc_or_107; // op=pyc.or
wire pyc_or_112; // op=pyc.or
wire pyc_or_117; // op=pyc.or
wire pyc_or_122; // op=pyc.or
wire pyc_or_127; // op=pyc.or
wire pyc_or_132; // op=pyc.or
wire pyc_or_137; // op=pyc.or
wire pyc_or_142; // op=pyc.or
wire pyc_or_147; // op=pyc.or
wire pyc_or_152; // op=pyc.or
wire pyc_or_157; // op=pyc.or
wire pyc_or_162; // op=pyc.or
wire pyc_or_167; // op=pyc.or
wire pyc_or_172; // op=pyc.or
wire pyc_or_177; // op=pyc.or
wire pyc_or_182; // op=pyc.or
wire pyc_or_187; // op=pyc.or
wire pyc_or_192; // op=pyc.or
wire pyc_or_197; // op=pyc.or
wire pyc_or_202; // op=pyc.or
wire pyc_or_207; // op=pyc.or
wire pyc_or_212; // op=pyc.or
wire pyc_or_217; // op=pyc.or
wire pyc_or_222; // op=pyc.or
wire pyc_or_227; // op=pyc.or
wire pyc_or_232; // op=pyc.or
wire pyc_or_237; // op=pyc.or
wire pyc_or_245; // op=pyc.or
wire pyc_or_247; // op=pyc.or
wire pyc_or_254; // op=pyc.or
wire pyc_or_256; // op=pyc.or
wire pyc_or_263; // op=pyc.or
wire pyc_or_265; // op=pyc.or
wire pyc_or_316; // op=pyc.or
wire pyc_or_329; // op=pyc.or
wire pyc_or_342; // op=pyc.or
wire pyc_or_355; // op=pyc.or
wire pyc_or_361; // op=pyc.or
wire pyc_or_374; // op=pyc.or
wire pyc_or_387; // op=pyc.or
wire pyc_or_400; // op=pyc.or
wire pyc_or_412; // op=pyc.or
wire pyc_or_423; // op=pyc.or
wire pyc_or_434; // op=pyc.or
wire pyc_or_445; // op=pyc.or
wire pyc_or_456; // op=pyc.or
wire pyc_or_467; // op=pyc.or
wire pyc_or_478; // op=pyc.or
wire pyc_or_489; // op=pyc.or
wire pyc_or_500; // op=pyc.or
wire pyc_or_511; // op=pyc.or
wire pyc_or_522; // op=pyc.or
wire pyc_or_533; // op=pyc.or
wire pyc_or_82; // op=pyc.or
wire pyc_or_87; // op=pyc.or
wire pyc_or_92; // op=pyc.or
wire pyc_or_97; // op=pyc.or
wire [3:0] pyc_reg_27; // op=pyc.reg
wire [7:0] pyc_reg_36; // op=pyc.reg
wire [7:0] pyc_reg_37; // op=pyc.reg
wire [7:0] pyc_reg_38; // op=pyc.reg
wire [7:0] pyc_reg_39; // op=pyc.reg
wire [5:0] pyc_reg_40; // op=pyc.reg
wire [5:0] pyc_reg_41; // op=pyc.reg
wire [5:0] pyc_reg_42; // op=pyc.reg
wire [5:0] pyc_reg_43; // op=pyc.reg
wire [7:0] pyc_reg_44; // op=pyc.reg
wire [7:0] pyc_reg_45; // op=pyc.reg
wire [7:0] pyc_reg_46; // op=pyc.reg
wire [7:0] pyc_reg_47; // op=pyc.reg
wire [7:0] pyc_reg_48; // op=pyc.reg
wire [7:0] pyc_reg_49; // op=pyc.reg
wire [7:0] pyc_reg_50; // op=pyc.reg
wire [7:0] pyc_reg_51; // op=pyc.reg
wire [7:0] pyc_reg_56; // op=pyc.reg
wire [7:0] pyc_reg_73; // op=pyc.reg
wire [7:0] pyc_reg_74; // op=pyc.reg
wire [7:0] pyc_reg_75; // op=pyc.reg
wire [7:0] pyc_reg_76; // op=pyc.reg
wire [5:0] pyc_reg_77; // op=pyc.reg
wire pyc_ult_243; // op=pyc.ult
wire pyc_ult_252; // op=pyc.ult
wire pyc_ult_261; // op=pyc.ult
wire pyc_ult_283; // op=pyc.ult
wire [2:0] pyc_zext_276; // op=pyc.zext
wire [2:0] pyc_zext_277; // op=pyc.zext
wire [2:0] pyc_zext_279; // op=pyc.zext
wire [2:0] pyc_zext_281; // op=pyc.zext

// --- Combinational (netlist)
assign dv_crs_ac__next = pyc_comb_303;
assign dv_crs_ag_0 = pyc_reg_40;
assign dv_crs_ag_0__next = pyc_mux_366;
assign dv_crs_ag_0__next = pyc_mux_504;
assign dv_crs_ag_0__next = pyc_mux_460;
assign dv_crs_ag_0__next = pyc_mux_416;
assign dv_crs_ag_1 = pyc_reg_41;
assign dv_crs_ag_1__next = pyc_mux_379;
assign dv_crs_ag_1__next = pyc_mux_515;
assign dv_crs_ag_1__next = pyc_mux_471;
assign dv_crs_ag_1__next = pyc_mux_427;
assign dv_crs_ag_2 = pyc_reg_42;
assign dv_crs_ag_2__next = pyc_mux_438;
assign dv_crs_ag_2__next = pyc_mux_392;
assign dv_crs_ag_2__next = pyc_mux_526;
assign dv_crs_ag_2__next = pyc_mux_482;
assign dv_crs_ag_3 = pyc_reg_43;
assign dv_crs_ag_3__next = pyc_mux_493;
assign dv_crs_ag_3__next = pyc_mux_405;
assign dv_crs_ag_3__next = pyc_mux_449;
assign dv_crs_ag_3__next = pyc_mux_537;
assign dv_crs_op_0 = pyc_reg_36;
assign dv_crs_op_0__next = pyc_mux_459;
assign dv_crs_op_0__next = pyc_mux_365;
assign dv_crs_op_0__next = pyc_mux_503;
assign dv_crs_op_0__next = pyc_mux_415;
assign dv_crs_op_1 = pyc_reg_37;
assign dv_crs_op_1__next = pyc_mux_378;
assign dv_crs_op_1__next = pyc_mux_470;
assign dv_crs_op_1__next = pyc_mux_514;
assign dv_crs_op_1__next = pyc_mux_426;
assign dv_crs_op_2 = pyc_reg_38;
assign dv_crs_op_2__next = pyc_mux_437;
assign dv_crs_op_2__next = pyc_mux_391;
assign dv_crs_op_2__next = pyc_mux_481;
assign dv_crs_op_2__next = pyc_mux_525;
assign dv_crs_op_3 = pyc_reg_39;
assign dv_crs_op_3__next = pyc_mux_448;
assign dv_crs_op_3__next = pyc_mux_404;
assign dv_crs_op_3__next = pyc_mux_492;
assign dv_crs_op_3__next = pyc_mux_536;
assign dv_crs_td_0 = pyc_reg_73;
assign dv_crs_td_0__next = pyc_mux_505;
assign dv_crs_td_0__next = pyc_mux_367;
assign dv_crs_td_0__next = pyc_mux_461;
assign dv_crs_td_0__next = pyc_mux_417;
assign dv_crs_td_1 = pyc_reg_74;
assign dv_crs_td_1__next = pyc_mux_516;
assign dv_crs_td_1__next = pyc_mux_472;
assign dv_crs_td_1__next = pyc_mux_428;
assign dv_crs_td_1__next = pyc_mux_380;
assign dv_crs_td_2 = pyc_reg_75;
assign dv_crs_td_2__next = pyc_mux_393;
assign dv_crs_td_2__next = pyc_mux_527;
assign dv_crs_td_2__next = pyc_mux_439;
assign dv_crs_td_2__next = pyc_mux_483;
assign dv_crs_td_3 = pyc_reg_76;
assign dv_crs_td_3__next = pyc_mux_494;
assign dv_crs_td_3__next = pyc_mux_450;
assign dv_crs_td_3__next = pyc_mux_406;
assign dv_crs_td_3__next = pyc_mux_538;
assign dv_crs_tr0_0__next = pyc_mux_463;
assign dv_crs_tr0_0__next = pyc_comb_314;
assign dv_crs_tr0_0__next = pyc_mux_369;
assign dv_crs_tr0_0__next = pyc_mux_419;
assign dv_crs_tr0_0__next = pyc_mux_507;
assign dv_crs_tr0_1__next = pyc_mux_430;
assign dv_crs_tr0_1__next = pyc_mux_518;
assign dv_crs_tr0_1__next = pyc_mux_474;
assign dv_crs_tr0_1__next = pyc_mux_382;
assign dv_crs_tr0_1__next = pyc_comb_327;
assign dv_crs_tr0_2__next = pyc_mux_529;
assign dv_crs_tr0_2__next = pyc_mux_395;
assign dv_crs_tr0_2__next = pyc_mux_441;
assign dv_crs_tr0_2__next = pyc_comb_340;
assign dv_crs_tr0_2__next = pyc_mux_485;
assign dv_crs_tr0_3__next = pyc_comb_353;
assign dv_crs_tr0_3__next = pyc_mux_540;
assign dv_crs_tr0_3__next = pyc_mux_408;
assign dv_crs_tr0_3__next = pyc_mux_452;
assign dv_crs_tr0_3__next = pyc_mux_496;
assign dv_crs_tr1_0__next = pyc_mux_465;
assign dv_crs_tr1_0__next = pyc_mux_421;
assign dv_crs_tr1_0__next = pyc_mux_371;
assign dv_crs_tr1_0__next = pyc_mux_509;
assign dv_crs_tr1_0__next = pyc_mux_315;
assign dv_crs_tr1_1__next = pyc_mux_520;
assign dv_crs_tr1_1__next = pyc_mux_328;
assign dv_crs_tr1_1__next = pyc_mux_384;
assign dv_crs_tr1_1__next = pyc_mux_432;
assign dv_crs_tr1_1__next = pyc_mux_476;
assign dv_crs_tr1_2__next = pyc_mux_397;
assign dv_crs_tr1_2__next = pyc_mux_341;
assign dv_crs_tr1_2__next = pyc_mux_443;
assign dv_crs_tr1_2__next = pyc_mux_531;
assign dv_crs_tr1_2__next = pyc_mux_487;
assign dv_crs_tr1_3__next = pyc_mux_498;
assign dv_crs_tr1_3__next = pyc_mux_542;
assign dv_crs_tr1_3__next = pyc_mux_354;
assign dv_crs_tr1_3__next = pyc_mux_454;
assign dv_crs_tr1_3__next = pyc_mux_410;
assign dv_crs_ts0_0 = pyc_reg_44;
assign dv_crs_ts0_0__next = pyc_mux_462;
assign dv_crs_ts0_0__next = pyc_mux_368;
assign dv_crs_ts0_0__next = pyc_mux_506;
assign dv_crs_ts0_0__next = pyc_mux_418;
assign dv_crs_ts0_1 = pyc_reg_45;
assign dv_crs_ts0_1__next = pyc_mux_473;
assign dv_crs_ts0_1__next = pyc_mux_429;
assign dv_crs_ts0_1__next = pyc_mux_381;
assign dv_crs_ts0_1__next = pyc_mux_517;
assign dv_crs_ts0_2 = pyc_reg_46;
assign dv_crs_ts0_2__next = pyc_mux_440;
assign dv_crs_ts0_2__next = pyc_mux_484;
assign dv_crs_ts0_2__next = pyc_mux_528;
assign dv_crs_ts0_2__next = pyc_mux_394;
assign dv_crs_ts0_3 = pyc_reg_47;
assign dv_crs_ts0_3__next = pyc_mux_407;
assign dv_crs_ts0_3__next = pyc_mux_539;
assign dv_crs_ts0_3__next = pyc_mux_451;
assign dv_crs_ts0_3__next = pyc_mux_495;
assign dv_crs_ts1_0 = pyc_reg_48;
assign dv_crs_ts1_0__next = pyc_mux_508;
assign dv_crs_ts1_0__next = pyc_mux_464;
assign dv_crs_ts1_0__next = pyc_mux_370;
assign dv_crs_ts1_0__next = pyc_mux_420;
assign dv_crs_ts1_1 = pyc_reg_49;
assign dv_crs_ts1_1__next = pyc_mux_383;
assign dv_crs_ts1_1__next = pyc_mux_431;
assign dv_crs_ts1_1__next = pyc_mux_475;
assign dv_crs_ts1_1__next = pyc_mux_519;
assign dv_crs_ts1_2 = pyc_reg_50;
assign dv_crs_ts1_2__next = pyc_mux_442;
assign dv_crs_ts1_2__next = pyc_mux_486;
assign dv_crs_ts1_2__next = pyc_mux_396;
assign dv_crs_ts1_2__next = pyc_mux_530;
assign dv_crs_ts1_3 = pyc_reg_51;
assign dv_crs_ts1_3__next = pyc_mux_409;
assign dv_crs_ts1_3__next = pyc_mux_497;
assign dv_crs_ts1_3__next = pyc_mux_541;
assign dv_crs_ts1_3__next = pyc_mux_453;
assign dv_crs_v_0__next = pyc_comb_414;
assign dv_crs_v_0__next = pyc_comb_319;
assign dv_crs_v_0__next = pyc_comb_502;
assign dv_crs_v_0__next = pyc_comb_458;
assign dv_crs_v_0__next = pyc_comb_364;
assign dv_crs_v_1__next = pyc_comb_469;
assign dv_crs_v_1__next = pyc_comb_425;
assign dv_crs_v_1__next = pyc_comb_513;
assign dv_crs_v_1__next = pyc_comb_332;
assign dv_crs_v_1__next = pyc_comb_377;
assign dv_crs_v_2__next = pyc_comb_436;
assign dv_crs_v_2__next = pyc_comb_524;
assign dv_crs_v_2__next = pyc_comb_345;
assign dv_crs_v_2__next = pyc_comb_390;
assign dv_crs_v_2__next = pyc_comb_480;
assign dv_crs_v_3__next = pyc_comb_358;
assign dv_crs_v_3__next = pyc_comb_535;
assign dv_crs_v_3__next = pyc_comb_491;
assign dv_crs_v_3__next = pyc_comb_403;
assign dv_crs_v_3__next = pyc_comb_447;
assign pyc_constant_1 = 1'd1;
assign pyc_constant_2 = 1'd0;
assign pyc_constant_3 = 8'd0;
assign pyc_constant_4 = 6'd0;
assign pyc_constant_5 = 2'd0;
assign pyc_constant_6 = 6'd63;
assign pyc_constant_7 = 2'd1;
assign pyc_constant_8 = 2'd2;
assign pyc_constant_9 = 2'd3;
assign pyc_constant_10 = 3'd4;
assign pyc_constant_11 = 6'd1;
assign pyc_comb_12 = pyc_constant_1;
assign pyc_comb_13 = pyc_constant_2;
assign pyc_comb_14 = pyc_constant_3;
assign pyc_comb_15 = pyc_constant_4;
assign pyc_comb_16 = pyc_constant_5;
assign pyc_comb_17 = pyc_constant_6;
assign pyc_comb_18 = pyc_constant_7;
assign pyc_comb_19 = pyc_constant_8;
assign pyc_comb_20 = pyc_constant_9;
assign pyc_comb_21 = pyc_constant_10;
assign pyc_comb_22 = pyc_constant_11;
assign pyc_concat_23 = {dv_crs_v_3__next, dv_crs_v_2__next, dv_crs_v_1__next, dv_crs_v_0__next};
assign pyc_concat_24 = {pyc_comb_13, pyc_comb_13, pyc_comb_13, pyc_comb_13};
assign pyc_comb_25 = pyc_concat_23;
assign pyc_comb_26 = pyc_concat_24;
assign dv_crs_ac = pyc_reg_77;
assign pyc_eq_78 = (dv_crs_tcb_t0 == dv_crs_ts0_0);
assign pyc_and_79 = (dv_crs_tcb_v0 & pyc_eq_78);
assign pyc_not_80 = (~pyc_comb_65);
assign pyc_and_81 = (pyc_and_79 & pyc_not_80);
assign pyc_or_82 = (pyc_comb_65 | pyc_and_81);
assign pyc_eq_83 = (dv_crs_tcb_t1 == dv_crs_ts0_0);
assign pyc_and_84 = (dv_crs_tcb_v1 & pyc_eq_83);
assign pyc_not_85 = (~pyc_or_82);
assign pyc_and_86 = (pyc_and_84 & pyc_not_85);
assign pyc_or_87 = (pyc_or_82 | pyc_and_86);
assign pyc_eq_88 = (dv_crs_tcb_t2 == dv_crs_ts0_0);
assign pyc_and_89 = (dv_crs_tcb_v2 & pyc_eq_88);
assign pyc_not_90 = (~pyc_or_87);
assign pyc_and_91 = (pyc_and_89 & pyc_not_90);
assign pyc_or_92 = (pyc_or_87 | pyc_and_91);
assign pyc_eq_93 = (dv_crs_tcb_t3 == dv_crs_ts0_0);
assign pyc_and_94 = (dv_crs_tcb_v3 & pyc_eq_93);
assign pyc_not_95 = (~pyc_or_92);
assign pyc_and_96 = (pyc_and_94 & pyc_not_95);
assign pyc_or_97 = (pyc_or_92 | pyc_and_96);
assign pyc_eq_98 = (dv_crs_tcb_t0 == dv_crs_ts1_0);
assign pyc_and_99 = (dv_crs_tcb_v0 & pyc_eq_98);
assign pyc_not_100 = (~pyc_comb_69);
assign pyc_and_101 = (pyc_and_99 & pyc_not_100);
assign pyc_or_102 = (pyc_comb_69 | pyc_and_101);
assign pyc_eq_103 = (dv_crs_tcb_t1 == dv_crs_ts1_0);
assign pyc_and_104 = (dv_crs_tcb_v1 & pyc_eq_103);
assign pyc_not_105 = (~pyc_or_102);
assign pyc_and_106 = (pyc_and_104 & pyc_not_105);
assign pyc_or_107 = (pyc_or_102 | pyc_and_106);
assign pyc_eq_108 = (dv_crs_tcb_t2 == dv_crs_ts1_0);
assign pyc_and_109 = (dv_crs_tcb_v2 & pyc_eq_108);
assign pyc_not_110 = (~pyc_or_107);
assign pyc_and_111 = (pyc_and_109 & pyc_not_110);
assign pyc_or_112 = (pyc_or_107 | pyc_and_111);
assign pyc_eq_113 = (dv_crs_tcb_t3 == dv_crs_ts1_0);
assign pyc_and_114 = (dv_crs_tcb_v3 & pyc_eq_113);
assign pyc_not_115 = (~pyc_or_112);
assign pyc_and_116 = (pyc_and_114 & pyc_not_115);
assign pyc_or_117 = (pyc_or_112 | pyc_and_116);
assign pyc_eq_118 = (dv_crs_tcb_t0 == dv_crs_ts0_1);
assign pyc_and_119 = (dv_crs_tcb_v0 & pyc_eq_118);
assign pyc_not_120 = (~pyc_comb_66);
assign pyc_and_121 = (pyc_and_119 & pyc_not_120);
assign pyc_or_122 = (pyc_comb_66 | pyc_and_121);
assign pyc_eq_123 = (dv_crs_tcb_t1 == dv_crs_ts0_1);
assign pyc_and_124 = (dv_crs_tcb_v1 & pyc_eq_123);
assign pyc_not_125 = (~pyc_or_122);
assign pyc_and_126 = (pyc_and_124 & pyc_not_125);
assign pyc_or_127 = (pyc_or_122 | pyc_and_126);
assign pyc_eq_128 = (dv_crs_tcb_t2 == dv_crs_ts0_1);
assign pyc_and_129 = (dv_crs_tcb_v2 & pyc_eq_128);
assign pyc_not_130 = (~pyc_or_127);
assign pyc_and_131 = (pyc_and_129 & pyc_not_130);
assign pyc_or_132 = (pyc_or_127 | pyc_and_131);
assign pyc_eq_133 = (dv_crs_tcb_t3 == dv_crs_ts0_1);
assign pyc_and_134 = (dv_crs_tcb_v3 & pyc_eq_133);
assign pyc_not_135 = (~pyc_or_132);
assign pyc_and_136 = (pyc_and_134 & pyc_not_135);
assign pyc_or_137 = (pyc_or_132 | pyc_and_136);
assign pyc_eq_138 = (dv_crs_tcb_t0 == dv_crs_ts1_1);
assign pyc_and_139 = (dv_crs_tcb_v0 & pyc_eq_138);
assign pyc_not_140 = (~pyc_comb_70);
assign pyc_and_141 = (pyc_and_139 & pyc_not_140);
assign pyc_or_142 = (pyc_comb_70 | pyc_and_141);
assign pyc_eq_143 = (dv_crs_tcb_t1 == dv_crs_ts1_1);
assign pyc_and_144 = (dv_crs_tcb_v1 & pyc_eq_143);
assign pyc_not_145 = (~pyc_or_142);
assign pyc_and_146 = (pyc_and_144 & pyc_not_145);
assign pyc_or_147 = (pyc_or_142 | pyc_and_146);
assign pyc_eq_148 = (dv_crs_tcb_t2 == dv_crs_ts1_1);
assign pyc_and_149 = (dv_crs_tcb_v2 & pyc_eq_148);
assign pyc_not_150 = (~pyc_or_147);
assign pyc_and_151 = (pyc_and_149 & pyc_not_150);
assign pyc_or_152 = (pyc_or_147 | pyc_and_151);
assign pyc_eq_153 = (dv_crs_tcb_t3 == dv_crs_ts1_1);
assign pyc_and_154 = (dv_crs_tcb_v3 & pyc_eq_153);
assign pyc_not_155 = (~pyc_or_152);
assign pyc_and_156 = (pyc_and_154 & pyc_not_155);
assign pyc_or_157 = (pyc_or_152 | pyc_and_156);
assign pyc_eq_158 = (dv_crs_tcb_t0 == dv_crs_ts0_2);
assign pyc_and_159 = (dv_crs_tcb_v0 & pyc_eq_158);
assign pyc_not_160 = (~pyc_comb_67);
assign pyc_and_161 = (pyc_and_159 & pyc_not_160);
assign pyc_or_162 = (pyc_comb_67 | pyc_and_161);
assign pyc_eq_163 = (dv_crs_tcb_t1 == dv_crs_ts0_2);
assign pyc_and_164 = (dv_crs_tcb_v1 & pyc_eq_163);
assign pyc_not_165 = (~pyc_or_162);
assign pyc_and_166 = (pyc_and_164 & pyc_not_165);
assign pyc_or_167 = (pyc_or_162 | pyc_and_166);
assign pyc_eq_168 = (dv_crs_tcb_t2 == dv_crs_ts0_2);
assign pyc_and_169 = (dv_crs_tcb_v2 & pyc_eq_168);
assign pyc_not_170 = (~pyc_or_167);
assign pyc_and_171 = (pyc_and_169 & pyc_not_170);
assign pyc_or_172 = (pyc_or_167 | pyc_and_171);
assign pyc_eq_173 = (dv_crs_tcb_t3 == dv_crs_ts0_2);
assign pyc_and_174 = (dv_crs_tcb_v3 & pyc_eq_173);
assign pyc_not_175 = (~pyc_or_172);
assign pyc_and_176 = (pyc_and_174 & pyc_not_175);
assign pyc_or_177 = (pyc_or_172 | pyc_and_176);
assign pyc_eq_178 = (dv_crs_tcb_t0 == dv_crs_ts1_2);
assign pyc_and_179 = (dv_crs_tcb_v0 & pyc_eq_178);
assign pyc_not_180 = (~pyc_comb_71);
assign pyc_and_181 = (pyc_and_179 & pyc_not_180);
assign pyc_or_182 = (pyc_comb_71 | pyc_and_181);
assign pyc_eq_183 = (dv_crs_tcb_t1 == dv_crs_ts1_2);
assign pyc_and_184 = (dv_crs_tcb_v1 & pyc_eq_183);
assign pyc_not_185 = (~pyc_or_182);
assign pyc_and_186 = (pyc_and_184 & pyc_not_185);
assign pyc_or_187 = (pyc_or_182 | pyc_and_186);
assign pyc_eq_188 = (dv_crs_tcb_t2 == dv_crs_ts1_2);
assign pyc_and_189 = (dv_crs_tcb_v2 & pyc_eq_188);
assign pyc_not_190 = (~pyc_or_187);
assign pyc_and_191 = (pyc_and_189 & pyc_not_190);
assign pyc_or_192 = (pyc_or_187 | pyc_and_191);
assign pyc_eq_193 = (dv_crs_tcb_t3 == dv_crs_ts1_2);
assign pyc_and_194 = (dv_crs_tcb_v3 & pyc_eq_193);
assign pyc_not_195 = (~pyc_or_192);
assign pyc_and_196 = (pyc_and_194 & pyc_not_195);
assign pyc_or_197 = (pyc_or_192 | pyc_and_196);
assign pyc_eq_198 = (dv_crs_tcb_t0 == dv_crs_ts0_3);
assign pyc_and_199 = (dv_crs_tcb_v0 & pyc_eq_198);
assign pyc_not_200 = (~pyc_comb_68);
assign pyc_and_201 = (pyc_and_199 & pyc_not_200);
assign pyc_or_202 = (pyc_comb_68 | pyc_and_201);
assign pyc_eq_203 = (dv_crs_tcb_t1 == dv_crs_ts0_3);
assign pyc_and_204 = (dv_crs_tcb_v1 & pyc_eq_203);
assign pyc_not_205 = (~pyc_or_202);
assign pyc_and_206 = (pyc_and_204 & pyc_not_205);
assign pyc_or_207 = (pyc_or_202 | pyc_and_206);
assign pyc_eq_208 = (dv_crs_tcb_t2 == dv_crs_ts0_3);
assign pyc_and_209 = (dv_crs_tcb_v2 & pyc_eq_208);
assign pyc_not_210 = (~pyc_or_207);
assign pyc_and_211 = (pyc_and_209 & pyc_not_210);
assign pyc_or_212 = (pyc_or_207 | pyc_and_211);
assign pyc_eq_213 = (dv_crs_tcb_t3 == dv_crs_ts0_3);
assign pyc_and_214 = (dv_crs_tcb_v3 & pyc_eq_213);
assign pyc_not_215 = (~pyc_or_212);
assign pyc_and_216 = (pyc_and_214 & pyc_not_215);
assign pyc_or_217 = (pyc_or_212 | pyc_and_216);
assign pyc_eq_218 = (dv_crs_tcb_t0 == dv_crs_ts1_3);
assign pyc_and_219 = (dv_crs_tcb_v0 & pyc_eq_218);
assign pyc_not_220 = (~pyc_comb_72);
assign pyc_and_221 = (pyc_and_219 & pyc_not_220);
assign pyc_or_222 = (pyc_comb_72 | pyc_and_221);
assign pyc_eq_223 = (dv_crs_tcb_t1 == dv_crs_ts1_3);
assign pyc_and_224 = (dv_crs_tcb_v1 & pyc_eq_223);
assign pyc_not_225 = (~pyc_or_222);
assign pyc_and_226 = (pyc_and_224 & pyc_not_225);
assign pyc_or_227 = (pyc_or_222 | pyc_and_226);
assign pyc_eq_228 = (dv_crs_tcb_t2 == dv_crs_ts1_3);
assign pyc_and_229 = (dv_crs_tcb_v2 & pyc_eq_228);
assign pyc_not_230 = (~pyc_or_227);
assign pyc_and_231 = (pyc_and_229 & pyc_not_230);
assign pyc_or_232 = (pyc_or_227 | pyc_and_231);
assign pyc_eq_233 = (dv_crs_tcb_t3 == dv_crs_ts1_3);
assign pyc_and_234 = (dv_crs_tcb_v3 & pyc_eq_233);
assign pyc_not_235 = (~pyc_or_232);
assign pyc_and_236 = (pyc_and_234 & pyc_not_235);
assign pyc_or_237 = (pyc_or_232 | pyc_and_236);
assign pyc_and_238 = (pyc_or_97 & pyc_or_117);
assign pyc_and_239 = (pyc_comb_32 & pyc_and_238);
assign pyc_mux_240 = (pyc_and_239 ? dv_crs_ag_0 : pyc_comb_17);
assign pyc_and_241 = (pyc_or_137 & pyc_or_157);
assign pyc_and_242 = (pyc_comb_33 & pyc_and_241);
assign pyc_ult_243 = (dv_crs_ag_1 < pyc_mux_240);
assign pyc_not_244 = (~pyc_and_239);
assign pyc_or_245 = (pyc_ult_243 | pyc_not_244);
assign pyc_and_246 = (pyc_and_242 & pyc_or_245);
assign pyc_or_247 = (pyc_and_246 | pyc_and_239);
assign pyc_mux_248 = (pyc_and_246 ? pyc_comb_18 : pyc_comb_16);
assign pyc_mux_249 = (pyc_and_246 ? dv_crs_ag_1 : pyc_mux_240);
assign pyc_and_250 = (pyc_or_177 & pyc_or_197);
assign pyc_and_251 = (pyc_comb_34 & pyc_and_250);
assign pyc_ult_252 = (dv_crs_ag_2 < pyc_mux_249);
assign pyc_not_253 = (~pyc_or_247);
assign pyc_or_254 = (pyc_ult_252 | pyc_not_253);
assign pyc_and_255 = (pyc_and_251 & pyc_or_254);
assign pyc_or_256 = (pyc_and_255 | pyc_or_247);
assign pyc_mux_257 = (pyc_and_255 ? pyc_comb_19 : pyc_mux_248);
assign pyc_mux_258 = (pyc_and_255 ? dv_crs_ag_2 : pyc_mux_249);
assign pyc_and_259 = (pyc_or_217 & pyc_or_237);
assign pyc_and_260 = (pyc_comb_35 & pyc_and_259);
assign pyc_ult_261 = (dv_crs_ag_3 < pyc_mux_258);
assign pyc_not_262 = (~pyc_or_256);
assign pyc_or_263 = (pyc_ult_261 | pyc_not_262);
assign pyc_and_264 = (pyc_and_260 & pyc_or_263);
assign pyc_or_265 = (pyc_and_264 | pyc_or_256);
assign pyc_mux_266 = (pyc_and_264 ? pyc_comb_20 : pyc_mux_257);
assign pyc_eq_267 = (pyc_mux_266 == pyc_comb_18);
assign pyc_mux_268 = (pyc_eq_267 ? dv_crs_op_1 : dv_crs_op_0);
assign pyc_mux_269 = (pyc_eq_267 ? dv_crs_td_1 : dv_crs_td_0);
assign pyc_eq_270 = (pyc_mux_266 == pyc_comb_19);
assign pyc_mux_271 = (pyc_eq_270 ? dv_crs_op_2 : pyc_mux_268);
assign pyc_mux_272 = (pyc_eq_270 ? dv_crs_td_2 : pyc_mux_269);
assign pyc_eq_273 = (pyc_mux_266 == pyc_comb_20);
assign pyc_mux_274 = (pyc_eq_273 ? dv_crs_op_3 : pyc_mux_271);
assign pyc_mux_275 = (pyc_eq_273 ? dv_crs_td_3 : pyc_mux_272);
assign pyc_zext_276 = {{2{1'b0}}, pyc_comb_32};
assign pyc_zext_277 = {{2{1'b0}}, pyc_comb_33};
assign pyc_add_278 = (pyc_zext_276 + pyc_zext_277);
assign pyc_zext_279 = {{2{1'b0}}, pyc_comb_34};
assign pyc_add_280 = (pyc_add_278 + pyc_zext_279);
assign pyc_zext_281 = {{2{1'b0}}, pyc_comb_35};
assign pyc_add_282 = (pyc_add_280 + pyc_zext_281);
assign pyc_ult_283 = (pyc_add_282 < pyc_comb_21);
assign pyc_not_284 = (~pyc_ult_283);
assign pyc_add_285 = (dv_crs_ac + pyc_comb_22);
assign pyc_comb_286 = dv_crs_ac;
assign pyc_comb_287 = pyc_or_97;
assign pyc_comb_288 = pyc_or_117;
assign pyc_comb_289 = pyc_or_137;
assign pyc_comb_290 = pyc_or_157;
assign pyc_comb_291 = pyc_or_177;
assign pyc_comb_292 = pyc_or_197;
assign pyc_comb_293 = pyc_or_217;
assign pyc_comb_294 = pyc_or_237;
assign pyc_comb_295 = pyc_or_265;
assign pyc_comb_296 = pyc_mux_266;
assign pyc_comb_297 = pyc_eq_267;
assign pyc_comb_298 = pyc_eq_270;
assign pyc_comb_299 = pyc_eq_273;
assign pyc_comb_300 = pyc_mux_274;
assign pyc_comb_301 = pyc_mux_275;
assign pyc_comb_302 = pyc_not_284;
assign pyc_comb_303 = pyc_add_285;
assign pyc_eq_304 = (pyc_comb_296 == pyc_comb_16);
assign pyc_and_305 = (pyc_comb_295 & pyc_eq_304);
assign pyc_not_306 = (~dv_crs_flush);
assign pyc_and_307 = (pyc_and_305 & pyc_not_306);
assign pyc_not_308 = (~pyc_and_307);
assign pyc_and_309 = (pyc_comb_32 & pyc_not_308);
assign pyc_mux_310 = (pyc_and_309 ? pyc_comb_287 : pyc_comb_65);
assign pyc_comb_311 = pyc_not_306;
assign pyc_comb_312 = pyc_and_307;
assign pyc_comb_313 = pyc_and_309;
assign pyc_comb_314 = pyc_mux_310;
assign pyc_or_316 = (pyc_comb_312 | dv_crs_flush);
assign pyc_not_317 = (~pyc_or_316);
assign pyc_and_318 = (pyc_not_317 & pyc_comb_32);
assign pyc_comb_319 = pyc_and_318;
assign pyc_extract_28 = pyc_reg_27[0];
assign pyc_extract_29 = pyc_reg_27[1];
assign pyc_extract_30 = pyc_reg_27[2];
assign pyc_extract_31 = pyc_reg_27[3];
assign dv_crs_v_0 = pyc_extract_28;
assign dv_crs_v_1 = pyc_extract_29;
assign dv_crs_v_2 = pyc_extract_30;
assign dv_crs_v_3 = pyc_extract_31;
assign pyc_comb_32 = dv_crs_v_0;
assign pyc_comb_33 = dv_crs_v_1;
assign pyc_comb_34 = dv_crs_v_2;
assign pyc_comb_35 = dv_crs_v_3;
assign pyc_and_320 = (pyc_comb_295 & pyc_comb_297);
assign pyc_and_321 = (pyc_and_320 & pyc_comb_311);
assign pyc_not_322 = (~pyc_and_321);
assign pyc_and_323 = (pyc_comb_33 & pyc_not_322);
assign pyc_mux_324 = (pyc_and_323 ? pyc_comb_289 : pyc_comb_66);
assign pyc_comb_325 = pyc_and_321;
assign pyc_comb_326 = pyc_and_323;
assign pyc_comb_327 = pyc_mux_324;
assign pyc_or_329 = (pyc_comb_325 | dv_crs_flush);
assign pyc_not_330 = (~pyc_or_329);
assign pyc_and_331 = (pyc_not_330 & pyc_comb_33);
assign pyc_comb_332 = pyc_and_331;
assign pyc_and_333 = (pyc_comb_295 & pyc_comb_298);
assign pyc_and_334 = (pyc_and_333 & pyc_comb_311);
assign pyc_not_335 = (~pyc_and_334);
assign pyc_and_336 = (pyc_comb_34 & pyc_not_335);
assign pyc_mux_337 = (pyc_and_336 ? pyc_comb_291 : pyc_comb_67);
assign pyc_comb_338 = pyc_and_334;
assign pyc_comb_339 = pyc_and_336;
assign pyc_comb_340 = pyc_mux_337;
assign pyc_or_342 = (pyc_comb_338 | dv_crs_flush);
assign pyc_not_343 = (~pyc_or_342);
assign pyc_and_344 = (pyc_not_343 & pyc_comb_34);
assign pyc_comb_345 = pyc_and_344;
assign pyc_and_346 = (pyc_comb_295 & pyc_comb_299);
assign pyc_and_347 = (pyc_and_346 & pyc_comb_311);
assign pyc_not_348 = (~pyc_and_347);
assign pyc_and_349 = (pyc_comb_35 & pyc_not_348);
assign pyc_mux_350 = (pyc_and_349 ? pyc_comb_293 : pyc_comb_68);
assign pyc_comb_351 = pyc_and_347;
assign pyc_comb_352 = pyc_and_349;
assign pyc_comb_353 = pyc_mux_350;
assign pyc_or_355 = (pyc_comb_351 | dv_crs_flush);
assign pyc_not_356 = (~pyc_or_355);
assign pyc_and_357 = (pyc_not_356 & pyc_comb_35);
assign pyc_comb_358 = pyc_and_357;
assign pyc_not_359 = (~pyc_comb_32);
assign pyc_and_360 = (dv_crs_dv0 & pyc_not_359);
assign pyc_or_361 = (pyc_and_360 | pyc_comb_32);
assign pyc_comb_362 = pyc_not_359;
assign pyc_comb_363 = pyc_and_360;
assign pyc_comb_364 = pyc_or_361;
assign pyc_not_372 = (~pyc_comb_33);
assign pyc_and_373 = (dv_crs_dv0 & pyc_not_372);
assign pyc_or_374 = (pyc_and_373 | pyc_comb_33);
assign pyc_comb_375 = pyc_not_372;
assign pyc_comb_376 = pyc_and_373;
assign pyc_comb_377 = pyc_or_374;
assign pyc_not_385 = (~pyc_comb_34);
assign pyc_and_386 = (dv_crs_dv0 & pyc_not_385);
assign pyc_or_387 = (pyc_and_386 | pyc_comb_34);
assign pyc_comb_388 = pyc_not_385;
assign pyc_comb_389 = pyc_and_386;
assign pyc_comb_390 = pyc_or_387;
assign pyc_not_398 = (~pyc_comb_35);
assign pyc_and_399 = (dv_crs_dv0 & pyc_not_398);
assign pyc_or_400 = (pyc_and_399 | pyc_comb_35);
assign pyc_comb_401 = pyc_not_398;
assign pyc_comb_402 = pyc_and_399;
assign pyc_comb_403 = pyc_or_400;
assign pyc_and_411 = (dv_crs_dv1 & pyc_comb_362);
assign pyc_or_412 = (pyc_and_411 | pyc_comb_32);
assign pyc_comb_413 = pyc_and_411;
assign pyc_comb_414 = pyc_or_412;
assign pyc_and_422 = (dv_crs_dv1 & pyc_comb_375);
assign pyc_or_423 = (pyc_and_422 | pyc_comb_33);
assign pyc_comb_424 = pyc_and_422;
assign pyc_comb_425 = pyc_or_423;
assign pyc_and_433 = (dv_crs_dv1 & pyc_comb_388);
assign pyc_or_434 = (pyc_and_433 | pyc_comb_34);
assign pyc_comb_435 = pyc_and_433;
assign pyc_comb_436 = pyc_or_434;
assign pyc_and_444 = (dv_crs_dv1 & pyc_comb_401);
assign pyc_or_445 = (pyc_and_444 | pyc_comb_35);
assign pyc_comb_446 = pyc_and_444;
assign pyc_comb_447 = pyc_or_445;
assign pyc_and_455 = (dv_crs_dv2 & pyc_comb_362);
assign pyc_or_456 = (pyc_and_455 | pyc_comb_32);
assign pyc_comb_457 = pyc_and_455;
assign pyc_comb_458 = pyc_or_456;
assign pyc_and_466 = (dv_crs_dv2 & pyc_comb_375);
assign pyc_or_467 = (pyc_and_466 | pyc_comb_33);
assign pyc_comb_468 = pyc_and_466;
assign pyc_comb_469 = pyc_or_467;
assign pyc_and_477 = (dv_crs_dv2 & pyc_comb_388);
assign pyc_or_478 = (pyc_and_477 | pyc_comb_34);
assign pyc_comb_479 = pyc_and_477;
assign pyc_comb_480 = pyc_or_478;
assign pyc_and_488 = (dv_crs_dv2 & pyc_comb_401);
assign pyc_or_489 = (pyc_and_488 | pyc_comb_35);
assign pyc_comb_490 = pyc_and_488;
assign pyc_comb_491 = pyc_or_489;
assign pyc_and_499 = (dv_crs_dv3 & pyc_comb_362);
assign pyc_or_500 = (pyc_and_499 | pyc_comb_32);
assign pyc_comb_501 = pyc_and_499;
assign pyc_comb_502 = pyc_or_500;
assign pyc_and_510 = (dv_crs_dv3 & pyc_comb_375);
assign pyc_or_511 = (pyc_and_510 | pyc_comb_33);
assign pyc_comb_512 = pyc_and_510;
assign pyc_comb_513 = pyc_or_511;
assign pyc_and_521 = (dv_crs_dv3 & pyc_comb_388);
assign pyc_or_522 = (pyc_and_521 | pyc_comb_34);
assign pyc_comb_523 = pyc_and_521;
assign pyc_comb_524 = pyc_or_522;
assign pyc_and_532 = (dv_crs_dv3 & pyc_comb_401);
assign pyc_or_533 = (pyc_and_532 | pyc_comb_35);
assign pyc_comb_534 = pyc_and_532;
assign pyc_comb_535 = pyc_or_533;
assign pyc_concat_52 = {dv_crs_tr1_3__next, dv_crs_tr1_2__next, dv_crs_tr1_1__next, dv_crs_tr1_0__next, dv_crs_tr0_3__next, dv_crs_tr0_2__next, dv_crs_tr0_1__next, dv_crs_tr0_0__next};
assign pyc_concat_53 = {pyc_comb_13, pyc_comb_13, pyc_comb_13, pyc_comb_13, pyc_comb_13, pyc_comb_13, pyc_comb_13, pyc_comb_13};
assign pyc_comb_54 = pyc_concat_52;
assign pyc_comb_55 = pyc_concat_53;
assign pyc_extract_57 = pyc_reg_56[0];
assign pyc_extract_58 = pyc_reg_56[1];
assign pyc_extract_59 = pyc_reg_56[2];
assign pyc_extract_60 = pyc_reg_56[3];
assign pyc_extract_61 = pyc_reg_56[4];
assign pyc_extract_62 = pyc_reg_56[5];
assign pyc_extract_63 = pyc_reg_56[6];
assign pyc_extract_64 = pyc_reg_56[7];
assign dv_crs_tr0_0 = pyc_extract_57;
assign dv_crs_tr0_1 = pyc_extract_58;
assign dv_crs_tr0_2 = pyc_extract_59;
assign dv_crs_tr0_3 = pyc_extract_60;
assign dv_crs_tr1_0 = pyc_extract_61;
assign dv_crs_tr1_1 = pyc_extract_62;
assign dv_crs_tr1_2 = pyc_extract_63;
assign dv_crs_tr1_3 = pyc_extract_64;
assign pyc_comb_65 = dv_crs_tr0_0;
assign pyc_comb_66 = dv_crs_tr0_1;
assign pyc_comb_67 = dv_crs_tr0_2;
assign pyc_comb_68 = dv_crs_tr0_3;
assign pyc_comb_69 = dv_crs_tr1_0;
assign pyc_comb_70 = dv_crs_tr1_1;
assign pyc_comb_71 = dv_crs_tr1_2;
assign pyc_comb_72 = dv_crs_tr1_3;
assign pyc_mux_315 = (pyc_comb_313 ? pyc_comb_288 : pyc_comb_69);
assign pyc_mux_328 = (pyc_comb_326 ? pyc_comb_290 : pyc_comb_70);
assign pyc_mux_341 = (pyc_comb_339 ? pyc_comb_292 : pyc_comb_71);
assign pyc_mux_354 = (pyc_comb_352 ? pyc_comb_294 : pyc_comb_72);
assign pyc_mux_365 = (pyc_comb_363 ? dv_crs_dop0 : dv_crs_op_0);
assign pyc_mux_366 = (pyc_comb_363 ? pyc_comb_286 : dv_crs_ag_0);
assign pyc_mux_367 = (pyc_comb_363 ? dv_crs_dtd0 : dv_crs_td_0);
assign pyc_mux_368 = (pyc_comb_363 ? dv_crs_dts0_0 : dv_crs_ts0_0);
assign pyc_mux_369 = (pyc_comb_363 ? dv_crs_dtr0_0 : pyc_comb_65);
assign pyc_mux_370 = (pyc_comb_363 ? dv_crs_dts1_0 : dv_crs_ts1_0);
assign pyc_mux_371 = (pyc_comb_363 ? dv_crs_dtr1_0 : pyc_comb_69);
assign pyc_mux_378 = (pyc_comb_376 ? dv_crs_dop0 : dv_crs_op_1);
assign pyc_mux_379 = (pyc_comb_376 ? pyc_comb_286 : dv_crs_ag_1);
assign pyc_mux_380 = (pyc_comb_376 ? dv_crs_dtd0 : dv_crs_td_1);
assign pyc_mux_381 = (pyc_comb_376 ? dv_crs_dts0_0 : dv_crs_ts0_1);
assign pyc_mux_382 = (pyc_comb_376 ? dv_crs_dtr0_0 : pyc_comb_66);
assign pyc_mux_383 = (pyc_comb_376 ? dv_crs_dts1_0 : dv_crs_ts1_1);
assign pyc_mux_384 = (pyc_comb_376 ? dv_crs_dtr1_0 : pyc_comb_70);
assign pyc_mux_391 = (pyc_comb_389 ? dv_crs_dop0 : dv_crs_op_2);
assign pyc_mux_392 = (pyc_comb_389 ? pyc_comb_286 : dv_crs_ag_2);
assign pyc_mux_393 = (pyc_comb_389 ? dv_crs_dtd0 : dv_crs_td_2);
assign pyc_mux_394 = (pyc_comb_389 ? dv_crs_dts0_0 : dv_crs_ts0_2);
assign pyc_mux_395 = (pyc_comb_389 ? dv_crs_dtr0_0 : pyc_comb_67);
assign pyc_mux_396 = (pyc_comb_389 ? dv_crs_dts1_0 : dv_crs_ts1_2);
assign pyc_mux_397 = (pyc_comb_389 ? dv_crs_dtr1_0 : pyc_comb_71);
assign pyc_mux_404 = (pyc_comb_402 ? dv_crs_dop0 : dv_crs_op_3);
assign pyc_mux_405 = (pyc_comb_402 ? pyc_comb_286 : dv_crs_ag_3);
assign pyc_mux_406 = (pyc_comb_402 ? dv_crs_dtd0 : dv_crs_td_3);
assign pyc_mux_407 = (pyc_comb_402 ? dv_crs_dts0_0 : dv_crs_ts0_3);
assign pyc_mux_408 = (pyc_comb_402 ? dv_crs_dtr0_0 : pyc_comb_68);
assign pyc_mux_409 = (pyc_comb_402 ? dv_crs_dts1_0 : dv_crs_ts1_3);
assign pyc_mux_410 = (pyc_comb_402 ? dv_crs_dtr1_0 : pyc_comb_72);
assign pyc_mux_415 = (pyc_comb_413 ? dv_crs_dop1 : dv_crs_op_0);
assign pyc_mux_416 = (pyc_comb_413 ? pyc_comb_286 : dv_crs_ag_0);
assign pyc_mux_417 = (pyc_comb_413 ? dv_crs_dtd1 : dv_crs_td_0);
assign pyc_mux_418 = (pyc_comb_413 ? dv_crs_dts0_1 : dv_crs_ts0_0);
assign pyc_mux_419 = (pyc_comb_413 ? dv_crs_dtr0_1 : pyc_comb_65);
assign pyc_mux_420 = (pyc_comb_413 ? dv_crs_dts1_1 : dv_crs_ts1_0);
assign pyc_mux_421 = (pyc_comb_413 ? dv_crs_dtr1_1 : pyc_comb_69);
assign pyc_mux_426 = (pyc_comb_424 ? dv_crs_dop1 : dv_crs_op_1);
assign pyc_mux_427 = (pyc_comb_424 ? pyc_comb_286 : dv_crs_ag_1);
assign pyc_mux_428 = (pyc_comb_424 ? dv_crs_dtd1 : dv_crs_td_1);
assign pyc_mux_429 = (pyc_comb_424 ? dv_crs_dts0_1 : dv_crs_ts0_1);
assign pyc_mux_430 = (pyc_comb_424 ? dv_crs_dtr0_1 : pyc_comb_66);
assign pyc_mux_431 = (pyc_comb_424 ? dv_crs_dts1_1 : dv_crs_ts1_1);
assign pyc_mux_432 = (pyc_comb_424 ? dv_crs_dtr1_1 : pyc_comb_70);
assign pyc_mux_437 = (pyc_comb_435 ? dv_crs_dop1 : dv_crs_op_2);
assign pyc_mux_438 = (pyc_comb_435 ? pyc_comb_286 : dv_crs_ag_2);
assign pyc_mux_439 = (pyc_comb_435 ? dv_crs_dtd1 : dv_crs_td_2);
assign pyc_mux_440 = (pyc_comb_435 ? dv_crs_dts0_1 : dv_crs_ts0_2);
assign pyc_mux_441 = (pyc_comb_435 ? dv_crs_dtr0_1 : pyc_comb_67);
assign pyc_mux_442 = (pyc_comb_435 ? dv_crs_dts1_1 : dv_crs_ts1_2);
assign pyc_mux_443 = (pyc_comb_435 ? dv_crs_dtr1_1 : pyc_comb_71);
assign pyc_mux_448 = (pyc_comb_446 ? dv_crs_dop1 : dv_crs_op_3);
assign pyc_mux_449 = (pyc_comb_446 ? pyc_comb_286 : dv_crs_ag_3);
assign pyc_mux_450 = (pyc_comb_446 ? dv_crs_dtd1 : dv_crs_td_3);
assign pyc_mux_451 = (pyc_comb_446 ? dv_crs_dts0_1 : dv_crs_ts0_3);
assign pyc_mux_452 = (pyc_comb_446 ? dv_crs_dtr0_1 : pyc_comb_68);
assign pyc_mux_453 = (pyc_comb_446 ? dv_crs_dts1_1 : dv_crs_ts1_3);
assign pyc_mux_454 = (pyc_comb_446 ? dv_crs_dtr1_1 : pyc_comb_72);
assign pyc_mux_459 = (pyc_comb_457 ? dv_crs_dop2 : dv_crs_op_0);
assign pyc_mux_460 = (pyc_comb_457 ? pyc_comb_286 : dv_crs_ag_0);
assign pyc_mux_461 = (pyc_comb_457 ? dv_crs_dtd2 : dv_crs_td_0);
assign pyc_mux_462 = (pyc_comb_457 ? dv_crs_dts0_2 : dv_crs_ts0_0);
assign pyc_mux_463 = (pyc_comb_457 ? dv_crs_dtr0_2 : pyc_comb_65);
assign pyc_mux_464 = (pyc_comb_457 ? dv_crs_dts1_2 : dv_crs_ts1_0);
assign pyc_mux_465 = (pyc_comb_457 ? dv_crs_dtr1_2 : pyc_comb_69);
assign pyc_mux_470 = (pyc_comb_468 ? dv_crs_dop2 : dv_crs_op_1);
assign pyc_mux_471 = (pyc_comb_468 ? pyc_comb_286 : dv_crs_ag_1);
assign pyc_mux_472 = (pyc_comb_468 ? dv_crs_dtd2 : dv_crs_td_1);
assign pyc_mux_473 = (pyc_comb_468 ? dv_crs_dts0_2 : dv_crs_ts0_1);
assign pyc_mux_474 = (pyc_comb_468 ? dv_crs_dtr0_2 : pyc_comb_66);
assign pyc_mux_475 = (pyc_comb_468 ? dv_crs_dts1_2 : dv_crs_ts1_1);
assign pyc_mux_476 = (pyc_comb_468 ? dv_crs_dtr1_2 : pyc_comb_70);
assign pyc_mux_481 = (pyc_comb_479 ? dv_crs_dop2 : dv_crs_op_2);
assign pyc_mux_482 = (pyc_comb_479 ? pyc_comb_286 : dv_crs_ag_2);
assign pyc_mux_483 = (pyc_comb_479 ? dv_crs_dtd2 : dv_crs_td_2);
assign pyc_mux_484 = (pyc_comb_479 ? dv_crs_dts0_2 : dv_crs_ts0_2);
assign pyc_mux_485 = (pyc_comb_479 ? dv_crs_dtr0_2 : pyc_comb_67);
assign pyc_mux_486 = (pyc_comb_479 ? dv_crs_dts1_2 : dv_crs_ts1_2);
assign pyc_mux_487 = (pyc_comb_479 ? dv_crs_dtr1_2 : pyc_comb_71);
assign pyc_mux_492 = (pyc_comb_490 ? dv_crs_dop2 : dv_crs_op_3);
assign pyc_mux_493 = (pyc_comb_490 ? pyc_comb_286 : dv_crs_ag_3);
assign pyc_mux_494 = (pyc_comb_490 ? dv_crs_dtd2 : dv_crs_td_3);
assign pyc_mux_495 = (pyc_comb_490 ? dv_crs_dts0_2 : dv_crs_ts0_3);
assign pyc_mux_496 = (pyc_comb_490 ? dv_crs_dtr0_2 : pyc_comb_68);
assign pyc_mux_497 = (pyc_comb_490 ? dv_crs_dts1_2 : dv_crs_ts1_3);
assign pyc_mux_498 = (pyc_comb_490 ? dv_crs_dtr1_2 : pyc_comb_72);
assign pyc_mux_503 = (pyc_comb_501 ? dv_crs_dop3 : dv_crs_op_0);
assign pyc_mux_504 = (pyc_comb_501 ? pyc_comb_286 : dv_crs_ag_0);
assign pyc_mux_505 = (pyc_comb_501 ? dv_crs_dtd3 : dv_crs_td_0);
assign pyc_mux_506 = (pyc_comb_501 ? dv_crs_dts0_3 : dv_crs_ts0_0);
assign pyc_mux_507 = (pyc_comb_501 ? dv_crs_dtr0_3 : pyc_comb_65);
assign pyc_mux_508 = (pyc_comb_501 ? dv_crs_dts1_3 : dv_crs_ts1_0);
assign pyc_mux_509 = (pyc_comb_501 ? dv_crs_dtr1_3 : pyc_comb_69);
assign pyc_mux_514 = (pyc_comb_512 ? dv_crs_dop3 : dv_crs_op_1);
assign pyc_mux_515 = (pyc_comb_512 ? pyc_comb_286 : dv_crs_ag_1);
assign pyc_mux_516 = (pyc_comb_512 ? dv_crs_dtd3 : dv_crs_td_1);
assign pyc_mux_517 = (pyc_comb_512 ? dv_crs_dts0_3 : dv_crs_ts0_1);
assign pyc_mux_518 = (pyc_comb_512 ? dv_crs_dtr0_3 : pyc_comb_66);
assign pyc_mux_519 = (pyc_comb_512 ? dv_crs_dts1_3 : dv_crs_ts1_1);
assign pyc_mux_520 = (pyc_comb_512 ? dv_crs_dtr1_3 : pyc_comb_70);
assign pyc_mux_525 = (pyc_comb_523 ? dv_crs_dop3 : dv_crs_op_2);
assign pyc_mux_526 = (pyc_comb_523 ? pyc_comb_286 : dv_crs_ag_2);
assign pyc_mux_527 = (pyc_comb_523 ? dv_crs_dtd3 : dv_crs_td_2);
assign pyc_mux_528 = (pyc_comb_523 ? dv_crs_dts0_3 : dv_crs_ts0_2);
assign pyc_mux_529 = (pyc_comb_523 ? dv_crs_dtr0_3 : pyc_comb_67);
assign pyc_mux_530 = (pyc_comb_523 ? dv_crs_dts1_3 : dv_crs_ts1_2);
assign pyc_mux_531 = (pyc_comb_523 ? dv_crs_dtr1_3 : pyc_comb_71);
assign pyc_mux_536 = (pyc_comb_534 ? dv_crs_dop3 : dv_crs_op_3);
assign pyc_mux_537 = (pyc_comb_534 ? pyc_comb_286 : dv_crs_ag_3);
assign pyc_mux_538 = (pyc_comb_534 ? dv_crs_dtd3 : dv_crs_td_3);
assign pyc_mux_539 = (pyc_comb_534 ? dv_crs_dts0_3 : dv_crs_ts0_3);
assign pyc_mux_540 = (pyc_comb_534 ? dv_crs_dtr0_3 : pyc_comb_68);
assign pyc_mux_541 = (pyc_comb_534 ? dv_crs_dts1_3 : dv_crs_ts1_3);
assign pyc_mux_542 = (pyc_comb_534 ? dv_crs_dtr1_3 : pyc_comb_72);

// --- Sequential primitives
pyc_reg #(.WIDTH(4)) pyc_reg_27_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(pyc_comb_25),
  .init(pyc_comb_26),
  .q(pyc_reg_27)
);
pyc_reg #(.WIDTH(8)) pyc_reg_36_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_op_0__next),
  .init(pyc_comb_14),
  .q(pyc_reg_36)
);
pyc_reg #(.WIDTH(8)) pyc_reg_37_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_op_1__next),
  .init(pyc_comb_14),
  .q(pyc_reg_37)
);
pyc_reg #(.WIDTH(8)) pyc_reg_38_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_op_2__next),
  .init(pyc_comb_14),
  .q(pyc_reg_38)
);
pyc_reg #(.WIDTH(8)) pyc_reg_39_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_op_3__next),
  .init(pyc_comb_14),
  .q(pyc_reg_39)
);
pyc_reg #(.WIDTH(6)) pyc_reg_40_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ag_0__next),
  .init(pyc_comb_15),
  .q(pyc_reg_40)
);
pyc_reg #(.WIDTH(6)) pyc_reg_41_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ag_1__next),
  .init(pyc_comb_15),
  .q(pyc_reg_41)
);
pyc_reg #(.WIDTH(6)) pyc_reg_42_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ag_2__next),
  .init(pyc_comb_15),
  .q(pyc_reg_42)
);
pyc_reg #(.WIDTH(6)) pyc_reg_43_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ag_3__next),
  .init(pyc_comb_15),
  .q(pyc_reg_43)
);
pyc_reg #(.WIDTH(8)) pyc_reg_44_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ts0_0__next),
  .init(pyc_comb_14),
  .q(pyc_reg_44)
);
pyc_reg #(.WIDTH(8)) pyc_reg_45_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ts0_1__next),
  .init(pyc_comb_14),
  .q(pyc_reg_45)
);
pyc_reg #(.WIDTH(8)) pyc_reg_46_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ts0_2__next),
  .init(pyc_comb_14),
  .q(pyc_reg_46)
);
pyc_reg #(.WIDTH(8)) pyc_reg_47_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ts0_3__next),
  .init(pyc_comb_14),
  .q(pyc_reg_47)
);
pyc_reg #(.WIDTH(8)) pyc_reg_48_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ts1_0__next),
  .init(pyc_comb_14),
  .q(pyc_reg_48)
);
pyc_reg #(.WIDTH(8)) pyc_reg_49_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ts1_1__next),
  .init(pyc_comb_14),
  .q(pyc_reg_49)
);
pyc_reg #(.WIDTH(8)) pyc_reg_50_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ts1_2__next),
  .init(pyc_comb_14),
  .q(pyc_reg_50)
);
pyc_reg #(.WIDTH(8)) pyc_reg_51_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ts1_3__next),
  .init(pyc_comb_14),
  .q(pyc_reg_51)
);
pyc_reg #(.WIDTH(8)) pyc_reg_56_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(pyc_comb_54),
  .init(pyc_comb_55),
  .q(pyc_reg_56)
);
pyc_reg #(.WIDTH(8)) pyc_reg_73_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_td_0__next),
  .init(pyc_comb_14),
  .q(pyc_reg_73)
);
pyc_reg #(.WIDTH(8)) pyc_reg_74_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_td_1__next),
  .init(pyc_comb_14),
  .q(pyc_reg_74)
);
pyc_reg #(.WIDTH(8)) pyc_reg_75_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_td_2__next),
  .init(pyc_comb_14),
  .q(pyc_reg_75)
);
pyc_reg #(.WIDTH(8)) pyc_reg_76_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_td_3__next),
  .init(pyc_comb_14),
  .q(pyc_reg_76)
);
pyc_reg #(.WIDTH(6)) pyc_reg_77_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_12),
  .d(dv_crs_ac__next),
  .init(pyc_comb_15),
  .q(pyc_reg_77)
);

assign dv_crs_issue_valid = pyc_comb_295;
assign dv_crs_issue_idx = pyc_comb_296;
assign dv_crs_issue_op = pyc_comb_300;
assign dv_crs_issue_ptdst = pyc_comb_301;
assign dv_crs_full = pyc_comb_302;

endmodule

