// Generated by pycc (pyCircuit)
// Module: davinci_top

module davinci_top (
  input clk,
  input rst,
  input dv_stall,
  input dv_icache_valid,
  input [63:0] dv_dmem_rdata,
  input dv_dmem_rvalid,
  input dv_bru_redirect,
  input [63:0] dv_bru_target,
  input [31:0] dv_icache_data0,
  input [31:0] dv_icache_data1,
  input [31:0] dv_icache_data2,
  input [31:0] dv_icache_data3,
  output [63:0] dv_pc,
  output dv_fetch_valid,
  output dv_dec_valid_0,
  output [1:0] dv_dec_domain_0,
  output [6:0] dv_ren_psrc1_0,
  output [6:0] dv_ren_psrc2_0,
  output [6:0] dv_ren_pdst_0,
  output dv_dec_valid_1,
  output [1:0] dv_dec_domain_1,
  output [6:0] dv_ren_psrc1_1,
  output [6:0] dv_ren_psrc2_1,
  output [6:0] dv_ren_pdst_1,
  output dv_dec_valid_2,
  output [1:0] dv_dec_domain_2,
  output [6:0] dv_ren_psrc1_2,
  output [6:0] dv_ren_psrc2_2,
  output [6:0] dv_ren_pdst_2,
  output dv_dec_valid_3,
  output [1:0] dv_dec_domain_3,
  output [6:0] dv_ren_psrc1_3,
  output [6:0] dv_ren_psrc2_3,
  output [6:0] dv_ren_pdst_3,
  output dv_ds_stall,
  output dv_srs_issue_valid,
  output dv_srs_full,
  output dv_alu0_result_valid,
  output [6:0] dv_alu0_result_tag,
  output [63:0] dv_alu0_result_data,
  output dv_md_busy,
  output dv_bru_mispredict,
  output dv_lsu_ld_result_valid,
  output dv_vrs_issue_valid,
  output dv_crs_issue_valid,
  output dv_mrs_issue_valid
);

wire pyc_and_31; // op=pyc.and
wire [63:0] pyc_comb_13; // op=pyc.comb
wire [7:0] pyc_comb_133; // op=pyc.comb
wire [7:0] pyc_comb_134; // op=pyc.comb
wire [7:0] pyc_comb_135; // op=pyc.comb
wire [7:0] pyc_comb_136; // op=pyc.comb
wire pyc_comb_14; // op=pyc.comb
wire [2:0] pyc_comb_15; // op=pyc.comb
wire [6:0] pyc_comb_16; // op=pyc.comb
wire [7:0] pyc_comb_17; // op=pyc.comb
wire [6:0] pyc_comb_18; // op=pyc.comb
wire [7:0] pyc_comb_19; // op=pyc.comb
wire [6:0] pyc_comb_20; // op=pyc.comb
wire [7:0] pyc_comb_21; // op=pyc.comb
wire [6:0] pyc_comb_22; // op=pyc.comb
wire [7:0] pyc_comb_23; // op=pyc.comb
wire [6:0] pyc_comb_24; // op=pyc.comb
wire [63:0] pyc_constant_1; // op=pyc.constant
wire [6:0] pyc_constant_10; // op=pyc.constant
wire [7:0] pyc_constant_11; // op=pyc.constant
wire [6:0] pyc_constant_12; // op=pyc.constant
wire pyc_constant_2; // op=pyc.constant
wire [2:0] pyc_constant_3; // op=pyc.constant
wire [6:0] pyc_constant_4; // op=pyc.constant
wire [7:0] pyc_constant_5; // op=pyc.constant
wire [6:0] pyc_constant_6; // op=pyc.constant
wire [7:0] pyc_constant_7; // op=pyc.constant
wire [6:0] pyc_constant_8; // op=pyc.constant
wire [7:0] pyc_constant_9; // op=pyc.constant
wire pyc_instance_100; // op=pyc.instance
wire [6:0] pyc_instance_101; // op=pyc.instance
wire [6:0] pyc_instance_102; // op=pyc.instance
wire [6:0] pyc_instance_103; // op=pyc.instance
wire pyc_instance_104; // op=pyc.instance
wire pyc_instance_105; // op=pyc.instance
wire [7:0] pyc_instance_106; // op=pyc.instance
wire [7:0] pyc_instance_107; // op=pyc.instance
wire pyc_instance_108; // op=pyc.instance
wire pyc_instance_109; // op=pyc.instance
wire [6:0] pyc_instance_110; // op=pyc.instance
wire [6:0] pyc_instance_111; // op=pyc.instance
wire [6:0] pyc_instance_112; // op=pyc.instance
wire pyc_instance_113; // op=pyc.instance
wire pyc_instance_114; // op=pyc.instance
wire [7:0] pyc_instance_115; // op=pyc.instance
wire [7:0] pyc_instance_116; // op=pyc.instance
wire pyc_instance_117; // op=pyc.instance
wire pyc_instance_118; // op=pyc.instance
wire [6:0] pyc_instance_119; // op=pyc.instance
wire [6:0] pyc_instance_120; // op=pyc.instance
wire [6:0] pyc_instance_121; // op=pyc.instance
wire pyc_instance_122; // op=pyc.instance
wire pyc_instance_123; // op=pyc.instance
wire [7:0] pyc_instance_124; // op=pyc.instance
wire [7:0] pyc_instance_125; // op=pyc.instance
wire pyc_instance_126; // op=pyc.instance
wire pyc_instance_127; // op=pyc.instance
wire [2:0] pyc_instance_128; // op=pyc.instance
wire pyc_instance_137; // op=pyc.instance
wire pyc_instance_138; // op=pyc.instance
wire pyc_instance_139; // op=pyc.instance
wire pyc_instance_140; // op=pyc.instance
wire pyc_instance_141; // op=pyc.instance
wire pyc_instance_142; // op=pyc.instance
wire pyc_instance_143; // op=pyc.instance
wire pyc_instance_144; // op=pyc.instance
wire pyc_instance_145; // op=pyc.instance
wire pyc_instance_146; // op=pyc.instance
wire pyc_instance_147; // op=pyc.instance
wire pyc_instance_148; // op=pyc.instance
wire pyc_instance_149; // op=pyc.instance
wire pyc_instance_150; // op=pyc.instance
wire pyc_instance_151; // op=pyc.instance
wire pyc_instance_152; // op=pyc.instance
wire pyc_instance_153; // op=pyc.instance
wire pyc_instance_154; // op=pyc.instance
wire pyc_instance_155; // op=pyc.instance
wire pyc_instance_156; // op=pyc.instance
wire pyc_instance_157; // op=pyc.instance
wire pyc_instance_158; // op=pyc.instance
wire pyc_instance_159; // op=pyc.instance
wire pyc_instance_160; // op=pyc.instance
wire [7:0] pyc_instance_161; // op=pyc.instance
wire [7:0] pyc_instance_162; // op=pyc.instance
wire [7:0] pyc_instance_163; // op=pyc.instance
wire [7:0] pyc_instance_164; // op=pyc.instance
wire [6:0] pyc_instance_165; // op=pyc.instance
wire [6:0] pyc_instance_166; // op=pyc.instance
wire [6:0] pyc_instance_167; // op=pyc.instance
wire [6:0] pyc_instance_168; // op=pyc.instance
wire [6:0] pyc_instance_169; // op=pyc.instance
wire [6:0] pyc_instance_170; // op=pyc.instance
wire [6:0] pyc_instance_171; // op=pyc.instance
wire [6:0] pyc_instance_172; // op=pyc.instance
wire [6:0] pyc_instance_173; // op=pyc.instance
wire [6:0] pyc_instance_174; // op=pyc.instance
wire [6:0] pyc_instance_175; // op=pyc.instance
wire [6:0] pyc_instance_176; // op=pyc.instance
wire pyc_instance_177; // op=pyc.instance
wire pyc_instance_178; // op=pyc.instance
wire pyc_instance_179; // op=pyc.instance
wire pyc_instance_180; // op=pyc.instance
wire pyc_instance_181; // op=pyc.instance
wire pyc_instance_182; // op=pyc.instance
wire pyc_instance_183; // op=pyc.instance
wire pyc_instance_184; // op=pyc.instance
wire [7:0] pyc_instance_185; // op=pyc.instance
wire [7:0] pyc_instance_186; // op=pyc.instance
wire [7:0] pyc_instance_187; // op=pyc.instance
wire [7:0] pyc_instance_188; // op=pyc.instance
wire [7:0] pyc_instance_189; // op=pyc.instance
wire [7:0] pyc_instance_190; // op=pyc.instance
wire [7:0] pyc_instance_191; // op=pyc.instance
wire [7:0] pyc_instance_192; // op=pyc.instance
wire pyc_instance_193; // op=pyc.instance
wire pyc_instance_194; // op=pyc.instance
wire pyc_instance_195; // op=pyc.instance
wire pyc_instance_196; // op=pyc.instance
wire pyc_instance_197; // op=pyc.instance
wire pyc_instance_198; // op=pyc.instance
wire [4:0] pyc_instance_199; // op=pyc.instance
wire [7:0] pyc_instance_200; // op=pyc.instance
wire [63:0] pyc_instance_201; // op=pyc.instance
wire [63:0] pyc_instance_202; // op=pyc.instance
wire [6:0] pyc_instance_203; // op=pyc.instance
wire [2:0] pyc_instance_204; // op=pyc.instance
wire pyc_instance_205; // op=pyc.instance
wire pyc_instance_207; // op=pyc.instance
wire [6:0] pyc_instance_208; // op=pyc.instance
wire [63:0] pyc_instance_209; // op=pyc.instance
wire pyc_instance_211; // op=pyc.instance
wire pyc_instance_212; // op=pyc.instance
wire [6:0] pyc_instance_213; // op=pyc.instance
wire [63:0] pyc_instance_214; // op=pyc.instance
wire pyc_instance_216; // op=pyc.instance
wire pyc_instance_217; // op=pyc.instance
wire [63:0] pyc_instance_218; // op=pyc.instance
wire [2:0] pyc_instance_219; // op=pyc.instance
wire pyc_instance_220; // op=pyc.instance
wire [6:0] pyc_instance_221; // op=pyc.instance
wire [63:0] pyc_instance_222; // op=pyc.instance
wire pyc_instance_223; // op=pyc.instance
wire pyc_instance_224; // op=pyc.instance
wire [4:0] pyc_instance_225; // op=pyc.instance
wire [7:0] pyc_instance_226; // op=pyc.instance
wire [6:0] pyc_instance_227; // op=pyc.instance
wire pyc_instance_228; // op=pyc.instance
wire [4:0] pyc_instance_229; // op=pyc.instance
wire [7:0] pyc_instance_230; // op=pyc.instance
wire [6:0] pyc_instance_231; // op=pyc.instance
wire pyc_instance_232; // op=pyc.instance
wire pyc_instance_233; // op=pyc.instance
wire [6:0] pyc_instance_234; // op=pyc.instance
wire [63:0] pyc_instance_235; // op=pyc.instance
wire pyc_instance_236; // op=pyc.instance
wire [3:0] pyc_instance_237; // op=pyc.instance
wire [7:0] pyc_instance_238; // op=pyc.instance
wire [7:0] pyc_instance_239; // op=pyc.instance
wire [7:0] pyc_instance_240; // op=pyc.instance
wire [7:0] pyc_instance_241; // op=pyc.instance
wire pyc_instance_242; // op=pyc.instance
wire pyc_instance_243; // op=pyc.instance
wire [1:0] pyc_instance_244; // op=pyc.instance
wire [7:0] pyc_instance_245; // op=pyc.instance
wire [7:0] pyc_instance_246; // op=pyc.instance
wire pyc_instance_247; // op=pyc.instance
wire pyc_instance_248; // op=pyc.instance
wire [3:0] pyc_instance_249; // op=pyc.instance
wire [63:0] pyc_instance_25; // op=pyc.instance
wire [7:0] pyc_instance_250; // op=pyc.instance
wire [7:0] pyc_instance_251; // op=pyc.instance
wire [6:0] pyc_instance_252; // op=pyc.instance
wire pyc_instance_253; // op=pyc.instance
wire pyc_instance_26; // op=pyc.instance
wire [63:0] pyc_instance_27; // op=pyc.instance
wire [63:0] pyc_instance_28; // op=pyc.instance
wire [63:0] pyc_instance_29; // op=pyc.instance
wire [63:0] pyc_instance_30; // op=pyc.instance
wire [6:0] pyc_instance_32; // op=pyc.instance
wire [4:0] pyc_instance_33; // op=pyc.instance
wire [4:0] pyc_instance_34; // op=pyc.instance
wire [4:0] pyc_instance_35; // op=pyc.instance
wire [2:0] pyc_instance_36; // op=pyc.instance
wire [6:0] pyc_instance_37; // op=pyc.instance
wire [1:0] pyc_instance_38; // op=pyc.instance
wire pyc_instance_39; // op=pyc.instance
wire pyc_instance_40; // op=pyc.instance
wire pyc_instance_41; // op=pyc.instance
wire pyc_instance_42; // op=pyc.instance
wire pyc_instance_43; // op=pyc.instance
wire pyc_instance_44; // op=pyc.instance
wire pyc_instance_45; // op=pyc.instance
wire pyc_instance_46; // op=pyc.instance
wire [6:0] pyc_instance_47; // op=pyc.instance
wire [4:0] pyc_instance_48; // op=pyc.instance
wire [4:0] pyc_instance_49; // op=pyc.instance
wire [4:0] pyc_instance_50; // op=pyc.instance
wire [2:0] pyc_instance_51; // op=pyc.instance
wire [6:0] pyc_instance_52; // op=pyc.instance
wire [1:0] pyc_instance_53; // op=pyc.instance
wire pyc_instance_54; // op=pyc.instance
wire pyc_instance_55; // op=pyc.instance
wire pyc_instance_56; // op=pyc.instance
wire pyc_instance_57; // op=pyc.instance
wire pyc_instance_58; // op=pyc.instance
wire pyc_instance_59; // op=pyc.instance
wire pyc_instance_60; // op=pyc.instance
wire pyc_instance_61; // op=pyc.instance
wire [6:0] pyc_instance_62; // op=pyc.instance
wire [4:0] pyc_instance_63; // op=pyc.instance
wire [4:0] pyc_instance_64; // op=pyc.instance
wire [4:0] pyc_instance_65; // op=pyc.instance
wire [2:0] pyc_instance_66; // op=pyc.instance
wire [6:0] pyc_instance_67; // op=pyc.instance
wire [1:0] pyc_instance_68; // op=pyc.instance
wire pyc_instance_69; // op=pyc.instance
wire pyc_instance_70; // op=pyc.instance
wire pyc_instance_71; // op=pyc.instance
wire pyc_instance_72; // op=pyc.instance
wire pyc_instance_73; // op=pyc.instance
wire pyc_instance_74; // op=pyc.instance
wire pyc_instance_75; // op=pyc.instance
wire pyc_instance_76; // op=pyc.instance
wire [6:0] pyc_instance_77; // op=pyc.instance
wire [4:0] pyc_instance_78; // op=pyc.instance
wire [4:0] pyc_instance_79; // op=pyc.instance
wire [4:0] pyc_instance_80; // op=pyc.instance
wire [2:0] pyc_instance_81; // op=pyc.instance
wire [6:0] pyc_instance_82; // op=pyc.instance
wire [1:0] pyc_instance_83; // op=pyc.instance
wire pyc_instance_84; // op=pyc.instance
wire pyc_instance_85; // op=pyc.instance
wire pyc_instance_86; // op=pyc.instance
wire pyc_instance_87; // op=pyc.instance
wire pyc_instance_88; // op=pyc.instance
wire pyc_instance_89; // op=pyc.instance
wire pyc_instance_90; // op=pyc.instance
wire pyc_instance_91; // op=pyc.instance
wire [6:0] pyc_instance_92; // op=pyc.instance
wire [6:0] pyc_instance_93; // op=pyc.instance
wire [6:0] pyc_instance_94; // op=pyc.instance
wire pyc_instance_95; // op=pyc.instance
wire pyc_instance_96; // op=pyc.instance
wire [7:0] pyc_instance_97; // op=pyc.instance
wire [7:0] pyc_instance_98; // op=pyc.instance
wire pyc_instance_99; // op=pyc.instance
wire [3:0] pyc_trunc_206; // op=pyc.trunc
wire [1:0] pyc_trunc_210; // op=pyc.trunc
wire [2:0] pyc_trunc_215; // op=pyc.trunc
wire [7:0] pyc_zext_129; // op=pyc.zext
wire [7:0] pyc_zext_130; // op=pyc.zext
wire [7:0] pyc_zext_131; // op=pyc.zext
wire [7:0] pyc_zext_132; // op=pyc.zext

// --- Combinational (netlist)
assign pyc_and_31 = (pyc_instance_26 & dv_icache_valid);
assign pyc_constant_1 = 64'd0;
assign pyc_constant_2 = 1'd0;
assign pyc_constant_3 = 3'd0;
assign pyc_constant_4 = 7'd32;
assign pyc_constant_5 = 8'd0;
assign pyc_constant_6 = 7'd33;
assign pyc_constant_7 = 8'd1;
assign pyc_constant_8 = 7'd34;
assign pyc_constant_9 = 8'd2;
assign pyc_constant_10 = 7'd35;
assign pyc_constant_11 = 8'd3;
assign pyc_constant_12 = 7'd0;
assign pyc_comb_13 = pyc_constant_1;
assign pyc_comb_14 = pyc_constant_2;
assign pyc_comb_15 = pyc_constant_3;
assign pyc_comb_16 = pyc_constant_4;
assign pyc_comb_17 = pyc_constant_5;
assign pyc_comb_18 = pyc_constant_6;
assign pyc_comb_19 = pyc_constant_7;
assign pyc_comb_20 = pyc_constant_8;
assign pyc_comb_21 = pyc_constant_9;
assign pyc_comb_22 = pyc_constant_10;
assign pyc_comb_23 = pyc_constant_11;
assign pyc_comb_24 = pyc_constant_12;
assign pyc_zext_129 = {{1{1'b0}}, pyc_instance_32};
assign pyc_zext_130 = {{1{1'b0}}, pyc_instance_47};
assign pyc_zext_131 = {{1{1'b0}}, pyc_instance_62};
assign pyc_zext_132 = {{1{1'b0}}, pyc_instance_77};
assign pyc_comb_133 = pyc_zext_129;
assign pyc_comb_134 = pyc_zext_130;
assign pyc_comb_135 = pyc_zext_131;
assign pyc_comb_136 = pyc_zext_132;
assign pyc_trunc_206 = pyc_instance_200[3:0];
assign pyc_trunc_210 = pyc_instance_200[1:0];
assign pyc_trunc_215 = pyc_instance_200[2:0];

// --- Submodules
dispatch dv_ds (
  .clk(clk),
  .rst(rst),
  .dv_ds_valid0(pyc_instance_100),
  .dv_ds_valid1(pyc_instance_109),
  .dv_ds_valid2(pyc_instance_118),
  .dv_ds_valid3(pyc_instance_127),
  .dv_ds_domain0(pyc_instance_38),
  .dv_ds_domain1(pyc_instance_53),
  .dv_ds_domain2(pyc_instance_68),
  .dv_ds_domain3(pyc_instance_83),
  .dv_ds_op0(pyc_comb_133),
  .dv_ds_op1(pyc_comb_134),
  .dv_ds_op2(pyc_comb_135),
  .dv_ds_op3(pyc_comb_136),
  .dv_ds_is_load0(pyc_comb_14),
  .dv_ds_is_load1(pyc_comb_14),
  .dv_ds_is_load2(pyc_comb_14),
  .dv_ds_is_load3(pyc_comb_14),
  .dv_ds_is_store0(pyc_comb_14),
  .dv_ds_is_store1(pyc_comb_14),
  .dv_ds_is_store2(pyc_comb_14),
  .dv_ds_is_store3(pyc_comb_14),
  .dv_ds_is_vec0(pyc_comb_14),
  .dv_ds_is_vec1(pyc_comb_14),
  .dv_ds_is_vec2(pyc_comb_14),
  .dv_ds_is_vec3(pyc_comb_14),
  .dv_ds_psrc1_0(pyc_instance_92),
  .dv_ds_psrc1_1(pyc_instance_101),
  .dv_ds_psrc1_2(pyc_instance_110),
  .dv_ds_psrc1_3(pyc_instance_119),
  .dv_ds_psrc2_0(pyc_instance_93),
  .dv_ds_psrc2_1(pyc_instance_102),
  .dv_ds_psrc2_2(pyc_instance_111),
  .dv_ds_psrc2_3(pyc_instance_120),
  .dv_ds_pdst0(pyc_instance_94),
  .dv_ds_pdst1(pyc_instance_103),
  .dv_ds_pdst2(pyc_instance_112),
  .dv_ds_pdst3(pyc_instance_121),
  .dv_ds_rdy1_0(pyc_instance_95),
  .dv_ds_rdy1_1(pyc_instance_104),
  .dv_ds_rdy1_2(pyc_instance_113),
  .dv_ds_rdy1_3(pyc_instance_122),
  .dv_ds_rdy2_0(pyc_instance_96),
  .dv_ds_rdy2_1(pyc_instance_105),
  .dv_ds_rdy2_2(pyc_instance_114),
  .dv_ds_rdy2_3(pyc_instance_123),
  .dv_ds_ptsrc0(pyc_instance_97),
  .dv_ds_ptsrc1(pyc_instance_106),
  .dv_ds_ptsrc2(pyc_instance_115),
  .dv_ds_ptsrc3(pyc_instance_124),
  .dv_ds_ptdst0(pyc_instance_98),
  .dv_ds_ptdst1(pyc_instance_107),
  .dv_ds_ptdst2(pyc_instance_116),
  .dv_ds_ptdst3(pyc_instance_125),
  .dv_ds_trdy0(pyc_instance_99),
  .dv_ds_trdy1(pyc_instance_108),
  .dv_ds_trdy2(pyc_instance_117),
  .dv_ds_trdy3(pyc_instance_126),
  .dv_ds_srs_full(pyc_comb_14),
  .dv_ds_lrs_full(pyc_comb_14),
  .dv_ds_vrs_full(pyc_comb_14),
  .dv_ds_crs_full(pyc_comb_14),
  .dv_ds_mrs_full(pyc_comb_14),
  .dv_ds_to_srs0(pyc_instance_137),
  .dv_ds_to_srs1(pyc_instance_138),
  .dv_ds_to_srs2(pyc_instance_139),
  .dv_ds_to_srs3(pyc_instance_140),
  .dv_ds_to_lrs0(pyc_instance_141),
  .dv_ds_to_lrs1(pyc_instance_142),
  .dv_ds_to_lrs2(pyc_instance_143),
  .dv_ds_to_lrs3(pyc_instance_144),
  .dv_ds_to_vrs0(pyc_instance_145),
  .dv_ds_to_vrs1(pyc_instance_146),
  .dv_ds_to_vrs2(pyc_instance_147),
  .dv_ds_to_vrs3(pyc_instance_148),
  .dv_ds_to_crs0(pyc_instance_149),
  .dv_ds_to_crs1(pyc_instance_150),
  .dv_ds_to_crs2(pyc_instance_151),
  .dv_ds_to_crs3(pyc_instance_152),
  .dv_ds_to_mrs0(pyc_instance_153),
  .dv_ds_to_mrs1(pyc_instance_154),
  .dv_ds_to_mrs2(pyc_instance_155),
  .dv_ds_to_mrs3(pyc_instance_156),
  .dv_ds_out_valid0(pyc_instance_157),
  .dv_ds_out_valid1(pyc_instance_158),
  .dv_ds_out_valid2(pyc_instance_159),
  .dv_ds_out_valid3(pyc_instance_160),
  .dv_ds_out_op0(pyc_instance_161),
  .dv_ds_out_op1(pyc_instance_162),
  .dv_ds_out_op2(pyc_instance_163),
  .dv_ds_out_op3(pyc_instance_164),
  .dv_ds_out_psrc1_0(pyc_instance_165),
  .dv_ds_out_psrc1_1(pyc_instance_166),
  .dv_ds_out_psrc1_2(pyc_instance_167),
  .dv_ds_out_psrc1_3(pyc_instance_168),
  .dv_ds_out_psrc2_0(pyc_instance_169),
  .dv_ds_out_psrc2_1(pyc_instance_170),
  .dv_ds_out_psrc2_2(pyc_instance_171),
  .dv_ds_out_psrc2_3(pyc_instance_172),
  .dv_ds_out_pdst0(pyc_instance_173),
  .dv_ds_out_pdst1(pyc_instance_174),
  .dv_ds_out_pdst2(pyc_instance_175),
  .dv_ds_out_pdst3(pyc_instance_176),
  .dv_ds_out_rdy1_0(pyc_instance_177),
  .dv_ds_out_rdy1_1(pyc_instance_178),
  .dv_ds_out_rdy1_2(pyc_instance_179),
  .dv_ds_out_rdy1_3(pyc_instance_180),
  .dv_ds_out_rdy2_0(pyc_instance_181),
  .dv_ds_out_rdy2_1(pyc_instance_182),
  .dv_ds_out_rdy2_2(pyc_instance_183),
  .dv_ds_out_rdy2_3(pyc_instance_184),
  .dv_ds_out_ptsrc0(pyc_instance_185),
  .dv_ds_out_ptsrc1(pyc_instance_186),
  .dv_ds_out_ptsrc2(pyc_instance_187),
  .dv_ds_out_ptsrc3(pyc_instance_188),
  .dv_ds_out_ptdst0(pyc_instance_189),
  .dv_ds_out_ptdst1(pyc_instance_190),
  .dv_ds_out_ptdst2(pyc_instance_191),
  .dv_ds_out_ptdst3(pyc_instance_192),
  .dv_ds_out_trdy0(pyc_instance_193),
  .dv_ds_out_trdy1(pyc_instance_194),
  .dv_ds_out_trdy2(pyc_instance_195),
  .dv_ds_out_trdy3(pyc_instance_196),
  .dv_ds_stall(pyc_instance_197)
);
scalar_rs dv_srs (
  .clk(clk),
  .rst(rst),
  .dv_srs_disp_valid0(pyc_instance_137),
  .dv_srs_disp_valid1(pyc_instance_138),
  .dv_srs_disp_valid2(pyc_instance_139),
  .dv_srs_disp_valid3(pyc_instance_140),
  .dv_srs_disp_op0(pyc_instance_161),
  .dv_srs_disp_op1(pyc_instance_162),
  .dv_srs_disp_op2(pyc_instance_163),
  .dv_srs_disp_op3(pyc_instance_164),
  .dv_srs_disp_psrc1_0(pyc_instance_165),
  .dv_srs_disp_psrc1_1(pyc_instance_166),
  .dv_srs_disp_psrc1_2(pyc_instance_167),
  .dv_srs_disp_psrc1_3(pyc_instance_168),
  .dv_srs_disp_rdy1_0(pyc_instance_177),
  .dv_srs_disp_rdy1_1(pyc_instance_178),
  .dv_srs_disp_rdy1_2(pyc_instance_179),
  .dv_srs_disp_rdy1_3(pyc_instance_180),
  .dv_srs_disp_data1_0(pyc_comb_13),
  .dv_srs_disp_data1_1(pyc_comb_13),
  .dv_srs_disp_data1_2(pyc_comb_13),
  .dv_srs_disp_data1_3(pyc_comb_13),
  .dv_srs_disp_psrc2_0(pyc_instance_169),
  .dv_srs_disp_psrc2_1(pyc_instance_170),
  .dv_srs_disp_psrc2_2(pyc_instance_171),
  .dv_srs_disp_psrc2_3(pyc_instance_172),
  .dv_srs_disp_rdy2_0(pyc_instance_181),
  .dv_srs_disp_rdy2_1(pyc_instance_182),
  .dv_srs_disp_rdy2_2(pyc_instance_183),
  .dv_srs_disp_rdy2_3(pyc_instance_184),
  .dv_srs_disp_data2_0(pyc_comb_13),
  .dv_srs_disp_data2_1(pyc_comb_13),
  .dv_srs_disp_data2_2(pyc_comb_13),
  .dv_srs_disp_data2_3(pyc_comb_13),
  .dv_srs_disp_pdst0(pyc_instance_173),
  .dv_srs_disp_pdst1(pyc_instance_174),
  .dv_srs_disp_pdst2(pyc_instance_175),
  .dv_srs_disp_pdst3(pyc_instance_176),
  .dv_srs_disp_ckpt0(pyc_comb_15),
  .dv_srs_disp_ckpt1(pyc_comb_15),
  .dv_srs_disp_ckpt2(pyc_comb_15),
  .dv_srs_disp_ckpt3(pyc_comb_15),
  .dv_srs_cdb_valid0(pyc_comb_14),
  .dv_srs_cdb_valid1(pyc_comb_14),
  .dv_srs_cdb_valid2(pyc_comb_14),
  .dv_srs_cdb_valid3(pyc_comb_14),
  .dv_srs_cdb_valid4(pyc_comb_14),
  .dv_srs_cdb_valid5(pyc_comb_14),
  .dv_srs_cdb_tag0(pyc_comb_24),
  .dv_srs_cdb_tag1(pyc_comb_24),
  .dv_srs_cdb_tag2(pyc_comb_24),
  .dv_srs_cdb_tag3(pyc_comb_24),
  .dv_srs_cdb_tag4(pyc_comb_24),
  .dv_srs_cdb_tag5(pyc_comb_24),
  .dv_srs_cdb_data0(pyc_comb_13),
  .dv_srs_cdb_data1(pyc_comb_13),
  .dv_srs_cdb_data2(pyc_comb_13),
  .dv_srs_cdb_data3(pyc_comb_13),
  .dv_srs_cdb_data4(pyc_comb_13),
  .dv_srs_cdb_data5(pyc_comb_13),
  .dv_srs_flush(dv_bru_redirect),
  .dv_srs_issue_valid(pyc_instance_198),
  .dv_srs_issue_idx(pyc_instance_199),
  .dv_srs_issue_op(pyc_instance_200),
  .dv_srs_issue_data1(pyc_instance_201),
  .dv_srs_issue_data2(pyc_instance_202),
  .dv_srs_issue_pdst(pyc_instance_203),
  .dv_srs_issue_ckpt(pyc_instance_204),
  .dv_srs_full(pyc_instance_205)
);
alu dv_alu0 (
  .clk(clk),
  .rst(rst),
  .dv_alu0_valid(pyc_instance_198),
  .dv_alu0_func(pyc_trunc_206),
  .dv_alu0_src1(pyc_instance_201),
  .dv_alu0_src2(pyc_instance_202),
  .dv_alu0_pdst(pyc_instance_203),
  .dv_alu0_result_valid(pyc_instance_207),
  .dv_alu0_result_tag(pyc_instance_208),
  .dv_alu0_result_data(pyc_instance_209)
);
muldiv dv_md (
  .clk(clk),
  .rst(rst),
  .dv_md_valid(pyc_instance_198),
  .dv_md_func(pyc_trunc_210),
  .dv_md_src1(pyc_instance_201),
  .dv_md_src2(pyc_instance_202),
  .dv_md_pdst(pyc_instance_203),
  .dv_md_busy(pyc_instance_211),
  .dv_md_result_valid(pyc_instance_212),
  .dv_md_result_tag(pyc_instance_213),
  .dv_md_result_data(pyc_instance_214)
);
bru dv_bru (
  .clk(clk),
  .rst(rst),
  .dv_bru_valid(pyc_instance_198),
  .dv_bru_func(pyc_trunc_215),
  .dv_bru_src1(pyc_instance_201),
  .dv_bru_src2(pyc_instance_202),
  .dv_bru_predicted(pyc_comb_14),
  .dv_bru_pc(pyc_instance_25),
  .dv_bru_offset(pyc_comb_13),
  .dv_bru_pdst(pyc_instance_203),
  .dv_bru_ckpt(pyc_instance_204),
  .dv_bru_mispredict(pyc_instance_216),
  .dv_bru_taken(pyc_instance_217),
  .dv_bru_target(pyc_instance_218),
  .dv_bru_ckpt_id(pyc_instance_219),
  .dv_bru_result_valid(pyc_instance_220),
  .dv_bru_result_tag(pyc_instance_221),
  .dv_bru_result_data(pyc_instance_222),
  .dv_bru_dealloc_valid(pyc_instance_223)
);
lsu_rs dv_lrs (
  .clk(clk),
  .rst(rst),
  .dv_lrs_dv0(pyc_instance_141),
  .dv_lrs_dv1(pyc_instance_142),
  .dv_lrs_dv2(pyc_instance_143),
  .dv_lrs_dv3(pyc_instance_144),
  .dv_lrs_dop0(pyc_instance_161),
  .dv_lrs_dop1(pyc_instance_162),
  .dv_lrs_dop2(pyc_instance_163),
  .dv_lrs_dop3(pyc_instance_164),
  .dv_lrs_dps1_0(pyc_instance_165),
  .dv_lrs_dps1_1(pyc_instance_166),
  .dv_lrs_dps1_2(pyc_instance_167),
  .dv_lrs_dps1_3(pyc_instance_168),
  .dv_lrs_dr1_0(pyc_instance_177),
  .dv_lrs_dr1_1(pyc_instance_178),
  .dv_lrs_dr1_2(pyc_instance_179),
  .dv_lrs_dr1_3(pyc_instance_180),
  .dv_lrs_dps2_0(pyc_instance_169),
  .dv_lrs_dps2_1(pyc_instance_170),
  .dv_lrs_dps2_2(pyc_instance_171),
  .dv_lrs_dps2_3(pyc_instance_172),
  .dv_lrs_dr2_0(pyc_instance_181),
  .dv_lrs_dr2_1(pyc_instance_182),
  .dv_lrs_dr2_2(pyc_instance_183),
  .dv_lrs_dr2_3(pyc_instance_184),
  .dv_lrs_dpd0(pyc_instance_173),
  .dv_lrs_dpd1(pyc_instance_174),
  .dv_lrs_dpd2(pyc_instance_175),
  .dv_lrs_dpd3(pyc_instance_176),
  .dv_lrs_dst0(pyc_comb_14),
  .dv_lrs_dst1(pyc_comb_14),
  .dv_lrs_dst2(pyc_comb_14),
  .dv_lrs_dst3(pyc_comb_14),
  .dv_lrs_cdb_v0(pyc_comb_14),
  .dv_lrs_cdb_v1(pyc_comb_14),
  .dv_lrs_cdb_v2(pyc_comb_14),
  .dv_lrs_cdb_v3(pyc_comb_14),
  .dv_lrs_cdb_v4(pyc_comb_14),
  .dv_lrs_cdb_v5(pyc_comb_14),
  .dv_lrs_cdb_t0(pyc_comb_24),
  .dv_lrs_cdb_t1(pyc_comb_24),
  .dv_lrs_cdb_t2(pyc_comb_24),
  .dv_lrs_cdb_t3(pyc_comb_24),
  .dv_lrs_cdb_t4(pyc_comb_24),
  .dv_lrs_cdb_t5(pyc_comb_24),
  .dv_lrs_flush(dv_bru_redirect),
  .dv_lrs_ld_issue_valid(pyc_instance_224),
  .dv_lrs_ld_issue_idx(pyc_instance_225),
  .dv_lrs_ld_issue_op(pyc_instance_226),
  .dv_lrs_ld_issue_pdst(pyc_instance_227),
  .dv_lrs_st_issue_valid(pyc_instance_228),
  .dv_lrs_st_issue_idx(pyc_instance_229),
  .dv_lrs_st_issue_op(pyc_instance_230),
  .dv_lrs_st_issue_pdst(pyc_instance_231),
  .dv_lrs_full(pyc_instance_232)
);
lsu dv_lsu (
  .clk(clk),
  .rst(rst),
  .dv_lsu_ld_valid(pyc_instance_224),
  .dv_lsu_ld_addr(pyc_comb_13),
  .dv_lsu_ld_pdst(pyc_instance_227),
  .dv_lsu_st_valid(pyc_instance_228),
  .dv_lsu_st_addr(pyc_comb_13),
  .dv_lsu_st_data(pyc_comb_13),
  .dv_lsu_ld_result_valid(pyc_instance_233),
  .dv_lsu_ld_result_tag(pyc_instance_234),
  .dv_lsu_ld_result_data(pyc_instance_235)
);
vec_rs dv_vrs (
  .clk(clk),
  .rst(rst),
  .dv_vrs_dv0(pyc_instance_145),
  .dv_vrs_dv1(pyc_instance_146),
  .dv_vrs_dv2(pyc_instance_147),
  .dv_vrs_dv3(pyc_instance_148),
  .dv_vrs_dop0(pyc_instance_161),
  .dv_vrs_dop1(pyc_instance_162),
  .dv_vrs_dop2(pyc_instance_163),
  .dv_vrs_dop3(pyc_instance_164),
  .dv_vrs_dts0_0(pyc_instance_185),
  .dv_vrs_dts0_1(pyc_instance_186),
  .dv_vrs_dts0_2(pyc_instance_187),
  .dv_vrs_dts0_3(pyc_instance_188),
  .dv_vrs_dts1_0(pyc_instance_185),
  .dv_vrs_dts1_1(pyc_instance_186),
  .dv_vrs_dts1_2(pyc_instance_187),
  .dv_vrs_dts1_3(pyc_instance_188),
  .dv_vrs_dtr0_0(pyc_instance_193),
  .dv_vrs_dtr0_1(pyc_instance_194),
  .dv_vrs_dtr0_2(pyc_instance_195),
  .dv_vrs_dtr0_3(pyc_instance_196),
  .dv_vrs_dtr1_0(pyc_instance_193),
  .dv_vrs_dtr1_1(pyc_instance_194),
  .dv_vrs_dtr1_2(pyc_instance_195),
  .dv_vrs_dtr1_3(pyc_instance_196),
  .dv_vrs_dtd0(pyc_instance_189),
  .dv_vrs_dtd1(pyc_instance_190),
  .dv_vrs_dtd2(pyc_instance_191),
  .dv_vrs_dtd3(pyc_instance_192),
  .dv_vrs_tcb_v0(pyc_comb_14),
  .dv_vrs_tcb_v1(pyc_comb_14),
  .dv_vrs_tcb_v2(pyc_comb_14),
  .dv_vrs_tcb_v3(pyc_comb_14),
  .dv_vrs_tcb_t0(pyc_comb_17),
  .dv_vrs_tcb_t1(pyc_comb_17),
  .dv_vrs_tcb_t2(pyc_comb_17),
  .dv_vrs_tcb_t3(pyc_comb_17),
  .dv_vrs_flush(dv_bru_redirect),
  .dv_vrs_issue_valid(pyc_instance_236),
  .dv_vrs_issue_idx(pyc_instance_237),
  .dv_vrs_issue_op(pyc_instance_238),
  .dv_vrs_issue_ptdst(pyc_instance_239),
  .dv_vrs_issue_ptsrc0(pyc_instance_240),
  .dv_vrs_issue_ptsrc1(pyc_instance_241),
  .dv_vrs_full(pyc_instance_242)
);
cube_rs dv_crs (
  .clk(clk),
  .rst(rst),
  .dv_crs_dv0(pyc_instance_149),
  .dv_crs_dv1(pyc_instance_150),
  .dv_crs_dv2(pyc_instance_151),
  .dv_crs_dv3(pyc_instance_152),
  .dv_crs_dop0(pyc_instance_161),
  .dv_crs_dop1(pyc_instance_162),
  .dv_crs_dop2(pyc_instance_163),
  .dv_crs_dop3(pyc_instance_164),
  .dv_crs_dts0_0(pyc_instance_185),
  .dv_crs_dts0_1(pyc_instance_186),
  .dv_crs_dts0_2(pyc_instance_187),
  .dv_crs_dts0_3(pyc_instance_188),
  .dv_crs_dts1_0(pyc_instance_185),
  .dv_crs_dts1_1(pyc_instance_186),
  .dv_crs_dts1_2(pyc_instance_187),
  .dv_crs_dts1_3(pyc_instance_188),
  .dv_crs_dtr0_0(pyc_instance_193),
  .dv_crs_dtr0_1(pyc_instance_194),
  .dv_crs_dtr0_2(pyc_instance_195),
  .dv_crs_dtr0_3(pyc_instance_196),
  .dv_crs_dtr1_0(pyc_instance_193),
  .dv_crs_dtr1_1(pyc_instance_194),
  .dv_crs_dtr1_2(pyc_instance_195),
  .dv_crs_dtr1_3(pyc_instance_196),
  .dv_crs_dtd0(pyc_instance_189),
  .dv_crs_dtd1(pyc_instance_190),
  .dv_crs_dtd2(pyc_instance_191),
  .dv_crs_dtd3(pyc_instance_192),
  .dv_crs_tcb_v0(pyc_comb_14),
  .dv_crs_tcb_v1(pyc_comb_14),
  .dv_crs_tcb_v2(pyc_comb_14),
  .dv_crs_tcb_v3(pyc_comb_14),
  .dv_crs_tcb_t0(pyc_comb_17),
  .dv_crs_tcb_t1(pyc_comb_17),
  .dv_crs_tcb_t2(pyc_comb_17),
  .dv_crs_tcb_t3(pyc_comb_17),
  .dv_crs_flush(dv_bru_redirect),
  .dv_crs_issue_valid(pyc_instance_243),
  .dv_crs_issue_idx(pyc_instance_244),
  .dv_crs_issue_op(pyc_instance_245),
  .dv_crs_issue_ptdst(pyc_instance_246),
  .dv_crs_full(pyc_instance_247)
);
mte_rs dv_mrs (
  .clk(clk),
  .rst(rst),
  .dv_mrs_dv0(pyc_instance_153),
  .dv_mrs_dv1(pyc_instance_154),
  .dv_mrs_dv2(pyc_instance_155),
  .dv_mrs_dv3(pyc_instance_156),
  .dv_mrs_dop0(pyc_instance_161),
  .dv_mrs_dop1(pyc_instance_162),
  .dv_mrs_dop2(pyc_instance_163),
  .dv_mrs_dop3(pyc_instance_164),
  .dv_mrs_dps0(pyc_instance_165),
  .dv_mrs_dps1(pyc_instance_166),
  .dv_mrs_dps2(pyc_instance_167),
  .dv_mrs_dps3(pyc_instance_168),
  .dv_mrs_dsr0(pyc_instance_177),
  .dv_mrs_dsr1(pyc_instance_178),
  .dv_mrs_dsr2(pyc_instance_179),
  .dv_mrs_dsr3(pyc_instance_180),
  .dv_mrs_dts0(pyc_instance_185),
  .dv_mrs_dts1(pyc_instance_186),
  .dv_mrs_dts2(pyc_instance_187),
  .dv_mrs_dts3(pyc_instance_188),
  .dv_mrs_dtr0(pyc_instance_193),
  .dv_mrs_dtr1(pyc_instance_194),
  .dv_mrs_dtr2(pyc_instance_195),
  .dv_mrs_dtr3(pyc_instance_196),
  .dv_mrs_dtd0(pyc_instance_189),
  .dv_mrs_dtd1(pyc_instance_190),
  .dv_mrs_dtd2(pyc_instance_191),
  .dv_mrs_dtd3(pyc_instance_192),
  .dv_mrs_dpsd0(pyc_instance_173),
  .dv_mrs_dpsd1(pyc_instance_174),
  .dv_mrs_dpsd2(pyc_instance_175),
  .dv_mrs_dpsd3(pyc_instance_176),
  .dv_mrs_cdb_v0(pyc_comb_14),
  .dv_mrs_cdb_v1(pyc_comb_14),
  .dv_mrs_cdb_v2(pyc_comb_14),
  .dv_mrs_cdb_v3(pyc_comb_14),
  .dv_mrs_cdb_v4(pyc_comb_14),
  .dv_mrs_cdb_v5(pyc_comb_14),
  .dv_mrs_cdb_t0(pyc_comb_24),
  .dv_mrs_cdb_t1(pyc_comb_24),
  .dv_mrs_cdb_t2(pyc_comb_24),
  .dv_mrs_cdb_t3(pyc_comb_24),
  .dv_mrs_cdb_t4(pyc_comb_24),
  .dv_mrs_cdb_t5(pyc_comb_24),
  .dv_mrs_tcb_v0(pyc_comb_14),
  .dv_mrs_tcb_v1(pyc_comb_14),
  .dv_mrs_tcb_v2(pyc_comb_14),
  .dv_mrs_tcb_v3(pyc_comb_14),
  .dv_mrs_tcb_t0(pyc_comb_17),
  .dv_mrs_tcb_t1(pyc_comb_17),
  .dv_mrs_tcb_t2(pyc_comb_17),
  .dv_mrs_tcb_t3(pyc_comb_17),
  .dv_mrs_flush(dv_bru_redirect),
  .dv_mrs_issue_valid(pyc_instance_248),
  .dv_mrs_issue_idx(pyc_instance_249),
  .dv_mrs_issue_op(pyc_instance_250),
  .dv_mrs_issue_ptdst(pyc_instance_251),
  .dv_mrs_issue_psdst(pyc_instance_252),
  .dv_mrs_full(pyc_instance_253)
);
fetch dv_fe (
  .clk(clk),
  .rst(rst),
  .dv_fe_stall(dv_stall),
  .dv_fe_redirect_valid(dv_bru_redirect),
  .dv_fe_redirect_target(dv_bru_target),
  .dv_fe_bpu_taken(pyc_comb_14),
  .dv_fe_bpu_target(pyc_comb_13),
  .dv_fe_pc(pyc_instance_25),
  .dv_fe_valid(pyc_instance_26),
  .dv_fe_ipc0(pyc_instance_27),
  .dv_fe_ipc1(pyc_instance_28),
  .dv_fe_ipc2(pyc_instance_29),
  .dv_fe_ipc3(pyc_instance_30)
);
decoder dv_dec (
  .clk(clk),
  .rst(rst),
  .dv_dec_valid0(pyc_and_31),
  .dv_dec_valid1(pyc_and_31),
  .dv_dec_valid2(pyc_and_31),
  .dv_dec_valid3(pyc_and_31),
  .dv_dec_instr0(dv_icache_data0),
  .dv_dec_instr1(dv_icache_data1),
  .dv_dec_instr2(dv_icache_data2),
  .dv_dec_instr3(dv_icache_data3),
  .dv_dec_opcode0(pyc_instance_32),
  .dv_dec_rd0(pyc_instance_33),
  .dv_dec_rs1_0(pyc_instance_34),
  .dv_dec_rs2_0(pyc_instance_35),
  .dv_dec_funct3_0(pyc_instance_36),
  .dv_dec_funct7_0(pyc_instance_37),
  .dv_dec_domain0(pyc_instance_38),
  .dv_dec_is_branch0(pyc_instance_39),
  .dv_dec_tile_move0(pyc_instance_40),
  .dv_dec_has_srd0(pyc_instance_41),
  .dv_dec_has_srs1_0(pyc_instance_42),
  .dv_dec_has_srs2_0(pyc_instance_43),
  .dv_dec_has_trd0(pyc_instance_44),
  .dv_dec_has_trs0(pyc_instance_45),
  .dv_dec_out_valid0(pyc_instance_46),
  .dv_dec_opcode1(pyc_instance_47),
  .dv_dec_rd1(pyc_instance_48),
  .dv_dec_rs1_1(pyc_instance_49),
  .dv_dec_rs2_1(pyc_instance_50),
  .dv_dec_funct3_1(pyc_instance_51),
  .dv_dec_funct7_1(pyc_instance_52),
  .dv_dec_domain1(pyc_instance_53),
  .dv_dec_is_branch1(pyc_instance_54),
  .dv_dec_tile_move1(pyc_instance_55),
  .dv_dec_has_srd1(pyc_instance_56),
  .dv_dec_has_srs1_1(pyc_instance_57),
  .dv_dec_has_srs2_1(pyc_instance_58),
  .dv_dec_has_trd1(pyc_instance_59),
  .dv_dec_has_trs1(pyc_instance_60),
  .dv_dec_out_valid1(pyc_instance_61),
  .dv_dec_opcode2(pyc_instance_62),
  .dv_dec_rd2(pyc_instance_63),
  .dv_dec_rs1_2(pyc_instance_64),
  .dv_dec_rs2_2(pyc_instance_65),
  .dv_dec_funct3_2(pyc_instance_66),
  .dv_dec_funct7_2(pyc_instance_67),
  .dv_dec_domain2(pyc_instance_68),
  .dv_dec_is_branch2(pyc_instance_69),
  .dv_dec_tile_move2(pyc_instance_70),
  .dv_dec_has_srd2(pyc_instance_71),
  .dv_dec_has_srs1_2(pyc_instance_72),
  .dv_dec_has_srs2_2(pyc_instance_73),
  .dv_dec_has_trd2(pyc_instance_74),
  .dv_dec_has_trs2(pyc_instance_75),
  .dv_dec_out_valid2(pyc_instance_76),
  .dv_dec_opcode3(pyc_instance_77),
  .dv_dec_rd3(pyc_instance_78),
  .dv_dec_rs1_3(pyc_instance_79),
  .dv_dec_rs2_3(pyc_instance_80),
  .dv_dec_funct3_3(pyc_instance_81),
  .dv_dec_funct7_3(pyc_instance_82),
  .dv_dec_domain3(pyc_instance_83),
  .dv_dec_is_branch3(pyc_instance_84),
  .dv_dec_tile_move3(pyc_instance_85),
  .dv_dec_has_srd3(pyc_instance_86),
  .dv_dec_has_srs1_3(pyc_instance_87),
  .dv_dec_has_srs2_3(pyc_instance_88),
  .dv_dec_has_trd3(pyc_instance_89),
  .dv_dec_has_trs3(pyc_instance_90),
  .dv_dec_out_valid3(pyc_instance_91)
);
rename dv_ren (
  .clk(clk),
  .rst(rst),
  .dv_ren_valid0(pyc_instance_46),
  .dv_ren_valid1(pyc_instance_61),
  .dv_ren_valid2(pyc_instance_76),
  .dv_ren_valid3(pyc_instance_91),
  .dv_ren_has_srd0(pyc_instance_41),
  .dv_ren_has_srd1(pyc_instance_56),
  .dv_ren_has_srd2(pyc_instance_71),
  .dv_ren_has_srd3(pyc_instance_86),
  .dv_ren_has_srs1_0(pyc_instance_41),
  .dv_ren_has_srs1_1(pyc_instance_56),
  .dv_ren_has_srs1_2(pyc_instance_71),
  .dv_ren_has_srs1_3(pyc_instance_86),
  .dv_ren_has_srs2_0(pyc_instance_41),
  .dv_ren_has_srs2_1(pyc_instance_56),
  .dv_ren_has_srs2_2(pyc_instance_71),
  .dv_ren_has_srs2_3(pyc_instance_86),
  .dv_ren_srd0(pyc_instance_33),
  .dv_ren_srd1(pyc_instance_48),
  .dv_ren_srd2(pyc_instance_63),
  .dv_ren_srd3(pyc_instance_78),
  .dv_ren_srs1_0(pyc_instance_34),
  .dv_ren_srs1_1(pyc_instance_49),
  .dv_ren_srs1_2(pyc_instance_64),
  .dv_ren_srs1_3(pyc_instance_79),
  .dv_ren_srs2_0(pyc_instance_35),
  .dv_ren_srs2_1(pyc_instance_50),
  .dv_ren_srs2_2(pyc_instance_65),
  .dv_ren_srs2_3(pyc_instance_80),
  .dv_ren_has_trd0(pyc_instance_44),
  .dv_ren_has_trd1(pyc_instance_59),
  .dv_ren_has_trd2(pyc_instance_74),
  .dv_ren_has_trd3(pyc_instance_89),
  .dv_ren_has_trs0(pyc_instance_45),
  .dv_ren_has_trs1(pyc_instance_60),
  .dv_ren_has_trs2(pyc_instance_75),
  .dv_ren_has_trs3(pyc_instance_90),
  .dv_ren_trd0(pyc_instance_33),
  .dv_ren_trd1(pyc_instance_48),
  .dv_ren_trd2(pyc_instance_63),
  .dv_ren_trd3(pyc_instance_78),
  .dv_ren_trs0(pyc_instance_34),
  .dv_ren_trs1(pyc_instance_49),
  .dv_ren_trs2(pyc_instance_64),
  .dv_ren_trs3(pyc_instance_79),
  .dv_ren_is_branch0(pyc_instance_39),
  .dv_ren_is_branch1(pyc_instance_54),
  .dv_ren_is_branch2(pyc_instance_69),
  .dv_ren_is_branch3(pyc_instance_84),
  .dv_ren_sfl_tag0(pyc_comb_16),
  .dv_ren_sfl_tag1(pyc_comb_18),
  .dv_ren_sfl_tag2(pyc_comb_20),
  .dv_ren_sfl_tag3(pyc_comb_22),
  .dv_ren_tfl_tag0(pyc_comb_17),
  .dv_ren_tfl_tag1(pyc_comb_19),
  .dv_ren_tfl_tag2(pyc_comb_21),
  .dv_ren_tfl_tag3(pyc_comb_23),
  .dv_ren_cdb_v0(pyc_comb_14),
  .dv_ren_cdb_v1(pyc_comb_14),
  .dv_ren_cdb_v2(pyc_comb_14),
  .dv_ren_cdb_v3(pyc_comb_14),
  .dv_ren_cdb_v4(pyc_comb_14),
  .dv_ren_cdb_v5(pyc_comb_14),
  .dv_ren_cdb_t0(pyc_comb_24),
  .dv_ren_cdb_t1(pyc_comb_24),
  .dv_ren_cdb_t2(pyc_comb_24),
  .dv_ren_cdb_t3(pyc_comb_24),
  .dv_ren_cdb_t4(pyc_comb_24),
  .dv_ren_cdb_t5(pyc_comb_24),
  .dv_ren_tcb_v0(pyc_comb_14),
  .dv_ren_tcb_v1(pyc_comb_14),
  .dv_ren_tcb_v2(pyc_comb_14),
  .dv_ren_tcb_v3(pyc_comb_14),
  .dv_ren_tcb_t0(pyc_comb_17),
  .dv_ren_tcb_t1(pyc_comb_17),
  .dv_ren_tcb_t2(pyc_comb_17),
  .dv_ren_tcb_t3(pyc_comb_17),
  .dv_ren_restore(dv_bru_redirect),
  .dv_ren_restore_ckpt(pyc_comb_15),
  .dv_ren_out_psrc1_0(pyc_instance_92),
  .dv_ren_out_psrc2_0(pyc_instance_93),
  .dv_ren_out_pdst_0(pyc_instance_94),
  .dv_ren_out_src1_rdy_0(pyc_instance_95),
  .dv_ren_out_src2_rdy_0(pyc_instance_96),
  .dv_ren_out_ptsrc_0(pyc_instance_97),
  .dv_ren_out_ptdst_0(pyc_instance_98),
  .dv_ren_out_tsrc_rdy_0(pyc_instance_99),
  .dv_ren_out_valid_0(pyc_instance_100),
  .dv_ren_out_psrc1_1(pyc_instance_101),
  .dv_ren_out_psrc2_1(pyc_instance_102),
  .dv_ren_out_pdst_1(pyc_instance_103),
  .dv_ren_out_src1_rdy_1(pyc_instance_104),
  .dv_ren_out_src2_rdy_1(pyc_instance_105),
  .dv_ren_out_ptsrc_1(pyc_instance_106),
  .dv_ren_out_ptdst_1(pyc_instance_107),
  .dv_ren_out_tsrc_rdy_1(pyc_instance_108),
  .dv_ren_out_valid_1(pyc_instance_109),
  .dv_ren_out_psrc1_2(pyc_instance_110),
  .dv_ren_out_psrc2_2(pyc_instance_111),
  .dv_ren_out_pdst_2(pyc_instance_112),
  .dv_ren_out_src1_rdy_2(pyc_instance_113),
  .dv_ren_out_src2_rdy_2(pyc_instance_114),
  .dv_ren_out_ptsrc_2(pyc_instance_115),
  .dv_ren_out_ptdst_2(pyc_instance_116),
  .dv_ren_out_tsrc_rdy_2(pyc_instance_117),
  .dv_ren_out_valid_2(pyc_instance_118),
  .dv_ren_out_psrc1_3(pyc_instance_119),
  .dv_ren_out_psrc2_3(pyc_instance_120),
  .dv_ren_out_pdst_3(pyc_instance_121),
  .dv_ren_out_src1_rdy_3(pyc_instance_122),
  .dv_ren_out_src2_rdy_3(pyc_instance_123),
  .dv_ren_out_ptsrc_3(pyc_instance_124),
  .dv_ren_out_ptdst_3(pyc_instance_125),
  .dv_ren_out_tsrc_rdy_3(pyc_instance_126),
  .dv_ren_out_valid_3(pyc_instance_127),
  .dv_ren_ckpt_id(pyc_instance_128)
);

assign dv_pc = pyc_instance_25;
assign dv_fetch_valid = pyc_and_31;
assign dv_dec_valid_0 = pyc_instance_46;
assign dv_dec_domain_0 = pyc_instance_38;
assign dv_ren_psrc1_0 = pyc_instance_92;
assign dv_ren_psrc2_0 = pyc_instance_93;
assign dv_ren_pdst_0 = pyc_instance_94;
assign dv_dec_valid_1 = pyc_instance_61;
assign dv_dec_domain_1 = pyc_instance_53;
assign dv_ren_psrc1_1 = pyc_instance_101;
assign dv_ren_psrc2_1 = pyc_instance_102;
assign dv_ren_pdst_1 = pyc_instance_103;
assign dv_dec_valid_2 = pyc_instance_76;
assign dv_dec_domain_2 = pyc_instance_68;
assign dv_ren_psrc1_2 = pyc_instance_110;
assign dv_ren_psrc2_2 = pyc_instance_111;
assign dv_ren_pdst_2 = pyc_instance_112;
assign dv_dec_valid_3 = pyc_instance_91;
assign dv_dec_domain_3 = pyc_instance_83;
assign dv_ren_psrc1_3 = pyc_instance_119;
assign dv_ren_psrc2_3 = pyc_instance_120;
assign dv_ren_pdst_3 = pyc_instance_121;
assign dv_ds_stall = pyc_instance_197;
assign dv_srs_issue_valid = pyc_instance_198;
assign dv_srs_full = pyc_instance_205;
assign dv_alu0_result_valid = pyc_instance_207;
assign dv_alu0_result_tag = pyc_instance_208;
assign dv_alu0_result_data = pyc_instance_209;
assign dv_md_busy = pyc_instance_211;
assign dv_bru_mispredict = pyc_instance_216;
assign dv_lsu_ld_result_valid = pyc_instance_233;
assign dv_vrs_issue_valid = pyc_instance_236;
assign dv_crs_issue_valid = pyc_instance_243;
assign dv_mrs_issue_valid = pyc_instance_248;

endmodule

