// Generated by pycc (pyCircuit)
// Module: decoder

module decoder (
  input clk,
  input rst,
  input dv_dec_valid0,
  input dv_dec_valid1,
  input dv_dec_valid2,
  input dv_dec_valid3,
  input [31:0] dv_dec_instr0,
  input [31:0] dv_dec_instr1,
  input [31:0] dv_dec_instr2,
  input [31:0] dv_dec_instr3,
  output [6:0] dv_dec_opcode0,
  output [4:0] dv_dec_rd0,
  output [4:0] dv_dec_rs1_0,
  output [4:0] dv_dec_rs2_0,
  output [2:0] dv_dec_funct3_0,
  output [6:0] dv_dec_funct7_0,
  output [1:0] dv_dec_domain0,
  output dv_dec_is_branch0,
  output dv_dec_tile_move0,
  output dv_dec_has_srd0,
  output dv_dec_has_srs1_0,
  output dv_dec_has_srs2_0,
  output dv_dec_has_trd0,
  output dv_dec_has_trs0,
  output dv_dec_out_valid0,
  output [6:0] dv_dec_opcode1,
  output [4:0] dv_dec_rd1,
  output [4:0] dv_dec_rs1_1,
  output [4:0] dv_dec_rs2_1,
  output [2:0] dv_dec_funct3_1,
  output [6:0] dv_dec_funct7_1,
  output [1:0] dv_dec_domain1,
  output dv_dec_is_branch1,
  output dv_dec_tile_move1,
  output dv_dec_has_srd1,
  output dv_dec_has_srs1_1,
  output dv_dec_has_srs2_1,
  output dv_dec_has_trd1,
  output dv_dec_has_trs1,
  output dv_dec_out_valid1,
  output [6:0] dv_dec_opcode2,
  output [4:0] dv_dec_rd2,
  output [4:0] dv_dec_rs1_2,
  output [4:0] dv_dec_rs2_2,
  output [2:0] dv_dec_funct3_2,
  output [6:0] dv_dec_funct7_2,
  output [1:0] dv_dec_domain2,
  output dv_dec_is_branch2,
  output dv_dec_tile_move2,
  output dv_dec_has_srd2,
  output dv_dec_has_srs1_2,
  output dv_dec_has_srs2_2,
  output dv_dec_has_trd2,
  output dv_dec_has_trs2,
  output dv_dec_out_valid2,
  output [6:0] dv_dec_opcode3,
  output [4:0] dv_dec_rd3,
  output [4:0] dv_dec_rs1_3,
  output [4:0] dv_dec_rs2_3,
  output [2:0] dv_dec_funct3_3,
  output [6:0] dv_dec_funct7_3,
  output [1:0] dv_dec_domain3,
  output dv_dec_is_branch3,
  output dv_dec_tile_move3,
  output dv_dec_has_srd3,
  output dv_dec_has_srs1_3,
  output dv_dec_has_srs2_3,
  output dv_dec_has_trd3,
  output dv_dec_has_trs3,
  output dv_dec_out_valid3
);

wire pyc_and_107; // op=pyc.and
wire pyc_and_109; // op=pyc.and
wire pyc_and_111; // op=pyc.and
wire pyc_and_115; // op=pyc.and
wire pyc_and_116; // op=pyc.and
wire pyc_and_118; // op=pyc.and
wire pyc_and_120; // op=pyc.and
wire pyc_and_23; // op=pyc.and
wire pyc_and_25; // op=pyc.and
wire pyc_and_27; // op=pyc.and
wire pyc_and_31; // op=pyc.and
wire pyc_and_32; // op=pyc.and
wire pyc_and_34; // op=pyc.and
wire pyc_and_36; // op=pyc.and
wire pyc_and_51; // op=pyc.and
wire pyc_and_53; // op=pyc.and
wire pyc_and_55; // op=pyc.and
wire pyc_and_59; // op=pyc.and
wire pyc_and_60; // op=pyc.and
wire pyc_and_62; // op=pyc.and
wire pyc_and_64; // op=pyc.and
wire pyc_and_79; // op=pyc.and
wire pyc_and_81; // op=pyc.and
wire pyc_and_83; // op=pyc.and
wire pyc_and_87; // op=pyc.and
wire pyc_and_88; // op=pyc.and
wire pyc_and_90; // op=pyc.and
wire pyc_and_92; // op=pyc.and
wire [6:0] pyc_comb_121; // op=pyc.comb
wire [4:0] pyc_comb_122; // op=pyc.comb
wire [2:0] pyc_comb_123; // op=pyc.comb
wire [4:0] pyc_comb_124; // op=pyc.comb
wire [4:0] pyc_comb_125; // op=pyc.comb
wire [6:0] pyc_comb_126; // op=pyc.comb
wire [1:0] pyc_comb_127; // op=pyc.comb
wire pyc_comb_128; // op=pyc.comb
wire pyc_comb_129; // op=pyc.comb
wire pyc_comb_130; // op=pyc.comb
wire pyc_comb_131; // op=pyc.comb
wire pyc_comb_132; // op=pyc.comb
wire [6:0] pyc_comb_133; // op=pyc.comb
wire [4:0] pyc_comb_134; // op=pyc.comb
wire [2:0] pyc_comb_135; // op=pyc.comb
wire [4:0] pyc_comb_136; // op=pyc.comb
wire [4:0] pyc_comb_137; // op=pyc.comb
wire [6:0] pyc_comb_138; // op=pyc.comb
wire [1:0] pyc_comb_139; // op=pyc.comb
wire pyc_comb_140; // op=pyc.comb
wire pyc_comb_141; // op=pyc.comb
wire pyc_comb_142; // op=pyc.comb
wire pyc_comb_143; // op=pyc.comb
wire pyc_comb_144; // op=pyc.comb
wire [6:0] pyc_comb_145; // op=pyc.comb
wire [4:0] pyc_comb_146; // op=pyc.comb
wire [2:0] pyc_comb_147; // op=pyc.comb
wire [4:0] pyc_comb_148; // op=pyc.comb
wire [4:0] pyc_comb_149; // op=pyc.comb
wire [6:0] pyc_comb_150; // op=pyc.comb
wire [1:0] pyc_comb_151; // op=pyc.comb
wire pyc_comb_152; // op=pyc.comb
wire pyc_comb_153; // op=pyc.comb
wire pyc_comb_154; // op=pyc.comb
wire pyc_comb_155; // op=pyc.comb
wire pyc_comb_156; // op=pyc.comb
wire [6:0] pyc_comb_157; // op=pyc.comb
wire [4:0] pyc_comb_158; // op=pyc.comb
wire [2:0] pyc_comb_159; // op=pyc.comb
wire [4:0] pyc_comb_160; // op=pyc.comb
wire [4:0] pyc_comb_161; // op=pyc.comb
wire [6:0] pyc_comb_162; // op=pyc.comb
wire [1:0] pyc_comb_163; // op=pyc.comb
wire pyc_comb_164; // op=pyc.comb
wire pyc_comb_165; // op=pyc.comb
wire pyc_comb_166; // op=pyc.comb
wire pyc_comb_167; // op=pyc.comb
wire pyc_comb_168; // op=pyc.comb
wire [1:0] pyc_constant_1; // op=pyc.constant
wire [1:0] pyc_constant_2; // op=pyc.constant
wire [1:0] pyc_constant_3; // op=pyc.constant
wire [1:0] pyc_constant_4; // op=pyc.constant
wire [4:0] pyc_constant_5; // op=pyc.constant
wire [6:0] pyc_constant_6; // op=pyc.constant
wire [6:0] pyc_constant_7; // op=pyc.constant
wire [6:0] pyc_constant_8; // op=pyc.constant
wire pyc_eq_100; // op=pyc.eq
wire pyc_eq_101; // op=pyc.eq
wire pyc_eq_103; // op=pyc.eq
wire pyc_eq_104; // op=pyc.eq
wire pyc_eq_106; // op=pyc.eq
wire pyc_eq_108; // op=pyc.eq
wire pyc_eq_110; // op=pyc.eq
wire pyc_eq_114; // op=pyc.eq
wire pyc_eq_16; // op=pyc.eq
wire pyc_eq_17; // op=pyc.eq
wire pyc_eq_19; // op=pyc.eq
wire pyc_eq_20; // op=pyc.eq
wire pyc_eq_22; // op=pyc.eq
wire pyc_eq_24; // op=pyc.eq
wire pyc_eq_26; // op=pyc.eq
wire pyc_eq_30; // op=pyc.eq
wire pyc_eq_44; // op=pyc.eq
wire pyc_eq_45; // op=pyc.eq
wire pyc_eq_47; // op=pyc.eq
wire pyc_eq_48; // op=pyc.eq
wire pyc_eq_50; // op=pyc.eq
wire pyc_eq_52; // op=pyc.eq
wire pyc_eq_54; // op=pyc.eq
wire pyc_eq_58; // op=pyc.eq
wire pyc_eq_72; // op=pyc.eq
wire pyc_eq_73; // op=pyc.eq
wire pyc_eq_75; // op=pyc.eq
wire pyc_eq_76; // op=pyc.eq
wire pyc_eq_78; // op=pyc.eq
wire pyc_eq_80; // op=pyc.eq
wire pyc_eq_82; // op=pyc.eq
wire pyc_eq_86; // op=pyc.eq
wire [4:0] pyc_extract_10; // op=pyc.extract
wire [4:0] pyc_extract_105; // op=pyc.extract
wire [2:0] pyc_extract_11; // op=pyc.extract
wire [4:0] pyc_extract_12; // op=pyc.extract
wire [4:0] pyc_extract_13; // op=pyc.extract
wire [6:0] pyc_extract_14; // op=pyc.extract
wire [1:0] pyc_extract_15; // op=pyc.extract
wire [4:0] pyc_extract_21; // op=pyc.extract
wire [6:0] pyc_extract_37; // op=pyc.extract
wire [4:0] pyc_extract_38; // op=pyc.extract
wire [2:0] pyc_extract_39; // op=pyc.extract
wire [4:0] pyc_extract_40; // op=pyc.extract
wire [4:0] pyc_extract_41; // op=pyc.extract
wire [6:0] pyc_extract_42; // op=pyc.extract
wire [1:0] pyc_extract_43; // op=pyc.extract
wire [4:0] pyc_extract_49; // op=pyc.extract
wire [6:0] pyc_extract_65; // op=pyc.extract
wire [4:0] pyc_extract_66; // op=pyc.extract
wire [2:0] pyc_extract_67; // op=pyc.extract
wire [4:0] pyc_extract_68; // op=pyc.extract
wire [4:0] pyc_extract_69; // op=pyc.extract
wire [6:0] pyc_extract_70; // op=pyc.extract
wire [1:0] pyc_extract_71; // op=pyc.extract
wire [4:0] pyc_extract_77; // op=pyc.extract
wire [6:0] pyc_extract_9; // op=pyc.extract
wire [6:0] pyc_extract_93; // op=pyc.extract
wire [4:0] pyc_extract_94; // op=pyc.extract
wire [2:0] pyc_extract_95; // op=pyc.extract
wire [4:0] pyc_extract_96; // op=pyc.extract
wire [4:0] pyc_extract_97; // op=pyc.extract
wire [6:0] pyc_extract_98; // op=pyc.extract
wire [1:0] pyc_extract_99; // op=pyc.extract
wire pyc_not_119; // op=pyc.not
wire pyc_not_35; // op=pyc.not
wire pyc_not_63; // op=pyc.not
wire pyc_not_91; // op=pyc.not
wire pyc_or_102; // op=pyc.or
wire pyc_or_112; // op=pyc.or
wire pyc_or_113; // op=pyc.or
wire pyc_or_117; // op=pyc.or
wire pyc_or_18; // op=pyc.or
wire pyc_or_28; // op=pyc.or
wire pyc_or_29; // op=pyc.or
wire pyc_or_33; // op=pyc.or
wire pyc_or_46; // op=pyc.or
wire pyc_or_56; // op=pyc.or
wire pyc_or_57; // op=pyc.or
wire pyc_or_61; // op=pyc.or
wire pyc_or_74; // op=pyc.or
wire pyc_or_84; // op=pyc.or
wire pyc_or_85; // op=pyc.or
wire pyc_or_89; // op=pyc.or

// --- Combinational (netlist)
assign pyc_constant_1 = 2'd0;
assign pyc_constant_2 = 2'd1;
assign pyc_constant_3 = 2'd2;
assign pyc_constant_4 = 2'd3;
assign pyc_constant_5 = 5'd24;
assign pyc_constant_6 = 7'd111;
assign pyc_constant_7 = 7'd103;
assign pyc_constant_8 = 7'd34;
assign pyc_extract_9 = dv_dec_instr0[6:0];
assign pyc_extract_10 = dv_dec_instr0[11:7];
assign pyc_extract_11 = dv_dec_instr0[14:12];
assign pyc_extract_12 = dv_dec_instr0[19:15];
assign pyc_extract_13 = dv_dec_instr0[24:20];
assign pyc_extract_14 = dv_dec_instr0[31:25];
assign pyc_extract_15 = dv_dec_instr0[6:5];
assign pyc_eq_16 = (pyc_extract_15 == pyc_constant_1);
assign pyc_eq_17 = (pyc_extract_15 == pyc_constant_2);
assign pyc_or_18 = (pyc_eq_16 | pyc_eq_17);
assign pyc_eq_19 = (pyc_extract_15 == pyc_constant_3);
assign pyc_eq_20 = (pyc_extract_15 == pyc_constant_4);
assign pyc_extract_21 = dv_dec_instr0[6:2];
assign pyc_eq_22 = (pyc_extract_21 == pyc_constant_5);
assign pyc_and_23 = (pyc_or_18 & pyc_eq_22);
assign pyc_eq_24 = (pyc_extract_9 == pyc_constant_6);
assign pyc_and_25 = (pyc_or_18 & pyc_eq_24);
assign pyc_eq_26 = (pyc_extract_9 == pyc_constant_7);
assign pyc_and_27 = (pyc_or_18 & pyc_eq_26);
assign pyc_or_28 = (pyc_and_23 | pyc_and_25);
assign pyc_or_29 = (pyc_or_28 | pyc_and_27);
assign pyc_eq_30 = (pyc_extract_14 == pyc_constant_8);
assign pyc_and_31 = (pyc_eq_19 & pyc_eq_30);
assign pyc_and_32 = (pyc_or_18 & dv_dec_valid0);
assign pyc_or_33 = (pyc_eq_19 | pyc_eq_20);
assign pyc_and_34 = (pyc_or_33 & dv_dec_valid0);
assign pyc_not_35 = (~pyc_and_31);
assign pyc_and_36 = (pyc_and_34 & pyc_not_35);
assign pyc_extract_37 = dv_dec_instr1[6:0];
assign pyc_extract_38 = dv_dec_instr1[11:7];
assign pyc_extract_39 = dv_dec_instr1[14:12];
assign pyc_extract_40 = dv_dec_instr1[19:15];
assign pyc_extract_41 = dv_dec_instr1[24:20];
assign pyc_extract_42 = dv_dec_instr1[31:25];
assign pyc_extract_43 = dv_dec_instr1[6:5];
assign pyc_eq_44 = (pyc_extract_43 == pyc_constant_1);
assign pyc_eq_45 = (pyc_extract_43 == pyc_constant_2);
assign pyc_or_46 = (pyc_eq_44 | pyc_eq_45);
assign pyc_eq_47 = (pyc_extract_43 == pyc_constant_3);
assign pyc_eq_48 = (pyc_extract_43 == pyc_constant_4);
assign pyc_extract_49 = dv_dec_instr1[6:2];
assign pyc_eq_50 = (pyc_extract_49 == pyc_constant_5);
assign pyc_and_51 = (pyc_or_46 & pyc_eq_50);
assign pyc_eq_52 = (pyc_extract_37 == pyc_constant_6);
assign pyc_and_53 = (pyc_or_46 & pyc_eq_52);
assign pyc_eq_54 = (pyc_extract_37 == pyc_constant_7);
assign pyc_and_55 = (pyc_or_46 & pyc_eq_54);
assign pyc_or_56 = (pyc_and_51 | pyc_and_53);
assign pyc_or_57 = (pyc_or_56 | pyc_and_55);
assign pyc_eq_58 = (pyc_extract_42 == pyc_constant_8);
assign pyc_and_59 = (pyc_eq_47 & pyc_eq_58);
assign pyc_and_60 = (pyc_or_46 & dv_dec_valid1);
assign pyc_or_61 = (pyc_eq_47 | pyc_eq_48);
assign pyc_and_62 = (pyc_or_61 & dv_dec_valid1);
assign pyc_not_63 = (~pyc_and_59);
assign pyc_and_64 = (pyc_and_62 & pyc_not_63);
assign pyc_extract_65 = dv_dec_instr2[6:0];
assign pyc_extract_66 = dv_dec_instr2[11:7];
assign pyc_extract_67 = dv_dec_instr2[14:12];
assign pyc_extract_68 = dv_dec_instr2[19:15];
assign pyc_extract_69 = dv_dec_instr2[24:20];
assign pyc_extract_70 = dv_dec_instr2[31:25];
assign pyc_extract_71 = dv_dec_instr2[6:5];
assign pyc_eq_72 = (pyc_extract_71 == pyc_constant_1);
assign pyc_eq_73 = (pyc_extract_71 == pyc_constant_2);
assign pyc_or_74 = (pyc_eq_72 | pyc_eq_73);
assign pyc_eq_75 = (pyc_extract_71 == pyc_constant_3);
assign pyc_eq_76 = (pyc_extract_71 == pyc_constant_4);
assign pyc_extract_77 = dv_dec_instr2[6:2];
assign pyc_eq_78 = (pyc_extract_77 == pyc_constant_5);
assign pyc_and_79 = (pyc_or_74 & pyc_eq_78);
assign pyc_eq_80 = (pyc_extract_65 == pyc_constant_6);
assign pyc_and_81 = (pyc_or_74 & pyc_eq_80);
assign pyc_eq_82 = (pyc_extract_65 == pyc_constant_7);
assign pyc_and_83 = (pyc_or_74 & pyc_eq_82);
assign pyc_or_84 = (pyc_and_79 | pyc_and_81);
assign pyc_or_85 = (pyc_or_84 | pyc_and_83);
assign pyc_eq_86 = (pyc_extract_70 == pyc_constant_8);
assign pyc_and_87 = (pyc_eq_75 & pyc_eq_86);
assign pyc_and_88 = (pyc_or_74 & dv_dec_valid2);
assign pyc_or_89 = (pyc_eq_75 | pyc_eq_76);
assign pyc_and_90 = (pyc_or_89 & dv_dec_valid2);
assign pyc_not_91 = (~pyc_and_87);
assign pyc_and_92 = (pyc_and_90 & pyc_not_91);
assign pyc_extract_93 = dv_dec_instr3[6:0];
assign pyc_extract_94 = dv_dec_instr3[11:7];
assign pyc_extract_95 = dv_dec_instr3[14:12];
assign pyc_extract_96 = dv_dec_instr3[19:15];
assign pyc_extract_97 = dv_dec_instr3[24:20];
assign pyc_extract_98 = dv_dec_instr3[31:25];
assign pyc_extract_99 = dv_dec_instr3[6:5];
assign pyc_eq_100 = (pyc_extract_99 == pyc_constant_1);
assign pyc_eq_101 = (pyc_extract_99 == pyc_constant_2);
assign pyc_or_102 = (pyc_eq_100 | pyc_eq_101);
assign pyc_eq_103 = (pyc_extract_99 == pyc_constant_3);
assign pyc_eq_104 = (pyc_extract_99 == pyc_constant_4);
assign pyc_extract_105 = dv_dec_instr3[6:2];
assign pyc_eq_106 = (pyc_extract_105 == pyc_constant_5);
assign pyc_and_107 = (pyc_or_102 & pyc_eq_106);
assign pyc_eq_108 = (pyc_extract_93 == pyc_constant_6);
assign pyc_and_109 = (pyc_or_102 & pyc_eq_108);
assign pyc_eq_110 = (pyc_extract_93 == pyc_constant_7);
assign pyc_and_111 = (pyc_or_102 & pyc_eq_110);
assign pyc_or_112 = (pyc_and_107 | pyc_and_109);
assign pyc_or_113 = (pyc_or_112 | pyc_and_111);
assign pyc_eq_114 = (pyc_extract_98 == pyc_constant_8);
assign pyc_and_115 = (pyc_eq_103 & pyc_eq_114);
assign pyc_and_116 = (pyc_or_102 & dv_dec_valid3);
assign pyc_or_117 = (pyc_eq_103 | pyc_eq_104);
assign pyc_and_118 = (pyc_or_117 & dv_dec_valid3);
assign pyc_not_119 = (~pyc_and_115);
assign pyc_and_120 = (pyc_and_118 & pyc_not_119);
assign pyc_comb_121 = pyc_extract_9;
assign pyc_comb_122 = pyc_extract_10;
assign pyc_comb_123 = pyc_extract_11;
assign pyc_comb_124 = pyc_extract_12;
assign pyc_comb_125 = pyc_extract_13;
assign pyc_comb_126 = pyc_extract_14;
assign pyc_comb_127 = pyc_extract_15;
assign pyc_comb_128 = pyc_or_29;
assign pyc_comb_129 = pyc_and_31;
assign pyc_comb_130 = pyc_and_32;
assign pyc_comb_131 = pyc_and_34;
assign pyc_comb_132 = pyc_and_36;
assign pyc_comb_133 = pyc_extract_37;
assign pyc_comb_134 = pyc_extract_38;
assign pyc_comb_135 = pyc_extract_39;
assign pyc_comb_136 = pyc_extract_40;
assign pyc_comb_137 = pyc_extract_41;
assign pyc_comb_138 = pyc_extract_42;
assign pyc_comb_139 = pyc_extract_43;
assign pyc_comb_140 = pyc_or_57;
assign pyc_comb_141 = pyc_and_59;
assign pyc_comb_142 = pyc_and_60;
assign pyc_comb_143 = pyc_and_62;
assign pyc_comb_144 = pyc_and_64;
assign pyc_comb_145 = pyc_extract_65;
assign pyc_comb_146 = pyc_extract_66;
assign pyc_comb_147 = pyc_extract_67;
assign pyc_comb_148 = pyc_extract_68;
assign pyc_comb_149 = pyc_extract_69;
assign pyc_comb_150 = pyc_extract_70;
assign pyc_comb_151 = pyc_extract_71;
assign pyc_comb_152 = pyc_or_85;
assign pyc_comb_153 = pyc_and_87;
assign pyc_comb_154 = pyc_and_88;
assign pyc_comb_155 = pyc_and_90;
assign pyc_comb_156 = pyc_and_92;
assign pyc_comb_157 = pyc_extract_93;
assign pyc_comb_158 = pyc_extract_94;
assign pyc_comb_159 = pyc_extract_95;
assign pyc_comb_160 = pyc_extract_96;
assign pyc_comb_161 = pyc_extract_97;
assign pyc_comb_162 = pyc_extract_98;
assign pyc_comb_163 = pyc_extract_99;
assign pyc_comb_164 = pyc_or_113;
assign pyc_comb_165 = pyc_and_115;
assign pyc_comb_166 = pyc_and_116;
assign pyc_comb_167 = pyc_and_118;
assign pyc_comb_168 = pyc_and_120;

assign dv_dec_opcode0 = pyc_comb_121;
assign dv_dec_rd0 = pyc_comb_122;
assign dv_dec_rs1_0 = pyc_comb_124;
assign dv_dec_rs2_0 = pyc_comb_125;
assign dv_dec_funct3_0 = pyc_comb_123;
assign dv_dec_funct7_0 = pyc_comb_126;
assign dv_dec_domain0 = pyc_comb_127;
assign dv_dec_is_branch0 = pyc_comb_128;
assign dv_dec_tile_move0 = pyc_comb_129;
assign dv_dec_has_srd0 = pyc_comb_130;
assign dv_dec_has_srs1_0 = pyc_comb_130;
assign dv_dec_has_srs2_0 = pyc_comb_130;
assign dv_dec_has_trd0 = pyc_comb_132;
assign dv_dec_has_trs0 = pyc_comb_131;
assign dv_dec_out_valid0 = dv_dec_valid0;
assign dv_dec_opcode1 = pyc_comb_133;
assign dv_dec_rd1 = pyc_comb_134;
assign dv_dec_rs1_1 = pyc_comb_136;
assign dv_dec_rs2_1 = pyc_comb_137;
assign dv_dec_funct3_1 = pyc_comb_135;
assign dv_dec_funct7_1 = pyc_comb_138;
assign dv_dec_domain1 = pyc_comb_139;
assign dv_dec_is_branch1 = pyc_comb_140;
assign dv_dec_tile_move1 = pyc_comb_141;
assign dv_dec_has_srd1 = pyc_comb_142;
assign dv_dec_has_srs1_1 = pyc_comb_142;
assign dv_dec_has_srs2_1 = pyc_comb_142;
assign dv_dec_has_trd1 = pyc_comb_144;
assign dv_dec_has_trs1 = pyc_comb_143;
assign dv_dec_out_valid1 = dv_dec_valid1;
assign dv_dec_opcode2 = pyc_comb_145;
assign dv_dec_rd2 = pyc_comb_146;
assign dv_dec_rs1_2 = pyc_comb_148;
assign dv_dec_rs2_2 = pyc_comb_149;
assign dv_dec_funct3_2 = pyc_comb_147;
assign dv_dec_funct7_2 = pyc_comb_150;
assign dv_dec_domain2 = pyc_comb_151;
assign dv_dec_is_branch2 = pyc_comb_152;
assign dv_dec_tile_move2 = pyc_comb_153;
assign dv_dec_has_srd2 = pyc_comb_154;
assign dv_dec_has_srs1_2 = pyc_comb_154;
assign dv_dec_has_srs2_2 = pyc_comb_154;
assign dv_dec_has_trd2 = pyc_comb_156;
assign dv_dec_has_trs2 = pyc_comb_155;
assign dv_dec_out_valid2 = dv_dec_valid2;
assign dv_dec_opcode3 = pyc_comb_157;
assign dv_dec_rd3 = pyc_comb_158;
assign dv_dec_rs1_3 = pyc_comb_160;
assign dv_dec_rs2_3 = pyc_comb_161;
assign dv_dec_funct3_3 = pyc_comb_159;
assign dv_dec_funct7_3 = pyc_comb_162;
assign dv_dec_domain3 = pyc_comb_163;
assign dv_dec_is_branch3 = pyc_comb_164;
assign dv_dec_tile_move3 = pyc_comb_165;
assign dv_dec_has_srd3 = pyc_comb_166;
assign dv_dec_has_srs1_3 = pyc_comb_166;
assign dv_dec_has_srs2_3 = pyc_comb_166;
assign dv_dec_has_trd3 = pyc_comb_168;
assign dv_dec_has_trs3 = pyc_comb_167;
assign dv_dec_out_valid3 = dv_dec_valid3;

endmodule

