// Generated by pycc (pyCircuit)
// Module: fetch

module fetch (
  input clk,
  input rst,
  input dv_fe_stall,
  input dv_fe_redirect_valid,
  input [63:0] dv_fe_redirect_target,
  input dv_fe_bpu_taken,
  input [63:0] dv_fe_bpu_target,
  output [63:0] dv_fe_pc,
  output dv_fe_valid,
  output [63:0] dv_fe_ipc0,
  output [63:0] dv_fe_ipc1,
  output [63:0] dv_fe_ipc2,
  output [63:0] dv_fe_ipc3
);

wire [63:0] dv_fe_pc_2; // pyc.name="dv_fe_pc"
wire [63:0] dv_fe_pc__next; // pyc.name="dv_fe_pc__next"
wire [63:0] pyc_add_17; // op=pyc.add
wire [63:0] pyc_add_18; // op=pyc.add
wire [63:0] pyc_add_19; // op=pyc.add
wire [63:0] pyc_add_20; // op=pyc.add
wire pyc_and_16; // op=pyc.and
wire [63:0] pyc_comb_10; // op=pyc.comb
wire [63:0] pyc_comb_11; // op=pyc.comb
wire [63:0] pyc_comb_12; // op=pyc.comb
wire [63:0] pyc_comb_24; // op=pyc.comb
wire pyc_comb_25; // op=pyc.comb
wire [63:0] pyc_comb_26; // op=pyc.comb
wire [63:0] pyc_comb_27; // op=pyc.comb
wire [63:0] pyc_comb_28; // op=pyc.comb
wire [63:0] pyc_comb_29; // op=pyc.comb
wire pyc_comb_7; // op=pyc.comb
wire [63:0] pyc_comb_8; // op=pyc.comb
wire [63:0] pyc_comb_9; // op=pyc.comb
wire pyc_constant_1; // op=pyc.constant
wire [63:0] pyc_constant_2; // op=pyc.constant
wire [63:0] pyc_constant_3; // op=pyc.constant
wire [63:0] pyc_constant_4; // op=pyc.constant
wire [63:0] pyc_constant_5; // op=pyc.constant
wire [63:0] pyc_constant_6; // op=pyc.constant
wire [63:0] pyc_mux_21; // op=pyc.mux
wire [63:0] pyc_mux_22; // op=pyc.mux
wire [63:0] pyc_mux_23; // op=pyc.mux
wire pyc_not_14; // op=pyc.not
wire pyc_not_15; // op=pyc.not
wire [63:0] pyc_reg_13; // op=pyc.reg

// --- Combinational (netlist)
assign pyc_constant_1 = 1'd1;
assign pyc_constant_2 = 64'd0;
assign pyc_constant_3 = 64'd4;
assign pyc_constant_4 = 64'd8;
assign pyc_constant_5 = 64'd12;
assign pyc_constant_6 = 64'd16;
assign pyc_comb_7 = pyc_constant_1;
assign pyc_comb_8 = pyc_constant_2;
assign pyc_comb_9 = pyc_constant_3;
assign pyc_comb_10 = pyc_constant_4;
assign pyc_comb_11 = pyc_constant_5;
assign pyc_comb_12 = pyc_constant_6;
assign dv_fe_pc_2 = pyc_reg_13;
assign pyc_not_14 = (~dv_fe_stall);
assign pyc_not_15 = (~dv_fe_redirect_valid);
assign pyc_and_16 = (pyc_not_14 & pyc_not_15);
assign pyc_add_17 = (dv_fe_pc_2 + pyc_comb_9);
assign pyc_add_18 = (dv_fe_pc_2 + pyc_comb_10);
assign pyc_add_19 = (dv_fe_pc_2 + pyc_comb_11);
assign pyc_add_20 = (dv_fe_pc_2 + pyc_comb_12);
assign pyc_mux_21 = (dv_fe_bpu_taken ? dv_fe_bpu_target : pyc_add_20);
assign pyc_mux_22 = (dv_fe_redirect_valid ? dv_fe_redirect_target : pyc_mux_21);
assign pyc_mux_23 = (dv_fe_stall ? dv_fe_pc_2 : pyc_mux_22);
assign pyc_comb_24 = dv_fe_pc_2;
assign pyc_comb_25 = pyc_and_16;
assign pyc_comb_26 = pyc_add_17;
assign pyc_comb_27 = pyc_add_18;
assign pyc_comb_28 = pyc_add_19;
assign pyc_comb_29 = pyc_mux_23;
assign dv_fe_pc__next = pyc_comb_29;

// --- Sequential primitives
pyc_reg #(.WIDTH(64)) pyc_reg_13_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_7),
  .d(dv_fe_pc__next),
  .init(pyc_comb_8),
  .q(pyc_reg_13)
);

assign dv_fe_pc = pyc_comb_24;
assign dv_fe_valid = pyc_comb_25;
assign dv_fe_ipc0 = pyc_comb_24;
assign dv_fe_ipc1 = pyc_comb_26;
assign dv_fe_ipc2 = pyc_comb_27;
assign dv_fe_ipc3 = pyc_comb_28;

endmodule

