// Generated by pycc (pyCircuit)
// Module: lsu

module lsu (
  input clk,
  input rst,
  input dv_lsu_ld_valid,
  input [63:0] dv_lsu_ld_addr,
  input [6:0] dv_lsu_ld_pdst,
  input dv_lsu_st_valid,
  input [63:0] dv_lsu_st_addr,
  input [63:0] dv_lsu_st_data,
  output dv_lsu_ld_result_valid,
  output [6:0] dv_lsu_ld_result_tag,
  output [63:0] dv_lsu_ld_result_data
);

wire [63:0] dv_lsu_lpa_0; // pyc.name="dv_lsu_lpa_0"
wire [63:0] dv_lsu_lpa_0__next; // pyc.name="dv_lsu_lpa_0__next"
wire [63:0] dv_lsu_lpa_1; // pyc.name="dv_lsu_lpa_1"
wire [63:0] dv_lsu_lpa_1__next; // pyc.name="dv_lsu_lpa_1__next"
wire [63:0] dv_lsu_lpa_2__next; // pyc.name="dv_lsu_lpa_2__next"
wire [6:0] dv_lsu_lpt_0; // pyc.name="dv_lsu_lpt_0"
wire [6:0] dv_lsu_lpt_0__next; // pyc.name="dv_lsu_lpt_0__next"
wire [6:0] dv_lsu_lpt_1; // pyc.name="dv_lsu_lpt_1"
wire [6:0] dv_lsu_lpt_1__next; // pyc.name="dv_lsu_lpt_1__next"
wire [6:0] dv_lsu_lpt_2; // pyc.name="dv_lsu_lpt_2"
wire [6:0] dv_lsu_lpt_2__next; // pyc.name="dv_lsu_lpt_2__next"
wire [6:0] dv_lsu_lpt_3; // pyc.name="dv_lsu_lpt_3"
wire [6:0] dv_lsu_lpt_3__next; // pyc.name="dv_lsu_lpt_3__next"
wire dv_lsu_lpv_0; // pyc.name="dv_lsu_lpv_0"
wire dv_lsu_lpv_0__next; // pyc.name="dv_lsu_lpv_0__next"
wire dv_lsu_lpv_1; // pyc.name="dv_lsu_lpv_1"
wire dv_lsu_lpv_1__next; // pyc.name="dv_lsu_lpv_1__next"
wire dv_lsu_lpv_2; // pyc.name="dv_lsu_lpv_2"
wire dv_lsu_lpv_2__next; // pyc.name="dv_lsu_lpv_2__next"
wire dv_lsu_lpv_3; // pyc.name="dv_lsu_lpv_3"
wire dv_lsu_lpv_3__next; // pyc.name="dv_lsu_lpv_3__next"
wire [63:0] dv_lsu_stba; // pyc.name="dv_lsu_stba"
wire [63:0] dv_lsu_stba__next; // pyc.name="dv_lsu_stba__next"
wire [63:0] dv_lsu_stbd; // pyc.name="dv_lsu_stbd"
wire [63:0] dv_lsu_stbd__next; // pyc.name="dv_lsu_stbd__next"
wire dv_lsu_stbv; // pyc.name="dv_lsu_stbv"
wire dv_lsu_stbv__next; // pyc.name="dv_lsu_stbv__next"
wire pyc_and_35; // op=pyc.and
wire [6:0] pyc_comb_10; // op=pyc.comb
wire pyc_comb_11; // op=pyc.comb
wire pyc_comb_13; // op=pyc.comb
wire pyc_comb_15; // op=pyc.comb
wire pyc_comb_17; // op=pyc.comb
wire [6:0] pyc_comb_20; // op=pyc.comb
wire [6:0] pyc_comb_22; // op=pyc.comb
wire [6:0] pyc_comb_24; // op=pyc.comb
wire [63:0] pyc_comb_27; // op=pyc.comb
wire [63:0] pyc_comb_29; // op=pyc.comb
wire [63:0] pyc_comb_38; // op=pyc.comb
wire [63:0] pyc_comb_39; // op=pyc.comb
wire pyc_comb_40; // op=pyc.comb
wire [63:0] pyc_comb_5; // op=pyc.comb
wire [6:0] pyc_comb_6; // op=pyc.comb
wire pyc_comb_7; // op=pyc.comb
wire pyc_comb_8; // op=pyc.comb
wire [63:0] pyc_comb_9; // op=pyc.comb
wire [63:0] pyc_constant_1; // op=pyc.constant
wire [6:0] pyc_constant_2; // op=pyc.constant
wire pyc_constant_3; // op=pyc.constant
wire pyc_constant_4; // op=pyc.constant
wire pyc_eq_34; // op=pyc.eq
wire [63:0] pyc_mux_36; // op=pyc.mux
wire [63:0] pyc_mux_41; // op=pyc.mux
wire [63:0] pyc_mux_42; // op=pyc.mux
wire pyc_or_37; // op=pyc.or
wire pyc_reg_12; // op=pyc.reg
wire pyc_reg_14; // op=pyc.reg
wire pyc_reg_16; // op=pyc.reg
wire pyc_reg_18; // op=pyc.reg
wire [6:0] pyc_reg_19; // op=pyc.reg
wire [6:0] pyc_reg_21; // op=pyc.reg
wire [6:0] pyc_reg_23; // op=pyc.reg
wire [6:0] pyc_reg_25; // op=pyc.reg
wire [63:0] pyc_reg_26; // op=pyc.reg
wire [63:0] pyc_reg_28; // op=pyc.reg
wire [63:0] pyc_reg_30; // op=pyc.reg
wire pyc_reg_31; // op=pyc.reg
wire [63:0] pyc_reg_32; // op=pyc.reg
wire [63:0] pyc_reg_33; // op=pyc.reg

// --- Combinational (netlist)
assign dv_lsu_lpt_3 = pyc_reg_25;
assign dv_lsu_lpv_3 = pyc_reg_18;
assign dv_lsu_stba = pyc_reg_32;
assign dv_lsu_stbv = pyc_reg_31;
assign dv_lsu_lpv_0 = pyc_reg_12;
assign dv_lsu_lpv_1__next = dv_lsu_lpv_0;
assign pyc_comb_13 = dv_lsu_lpv_1__next;
assign dv_lsu_lpv_1 = pyc_reg_14;
assign dv_lsu_lpv_2__next = dv_lsu_lpv_1;
assign pyc_comb_15 = dv_lsu_lpv_2__next;
assign dv_lsu_lpv_2 = pyc_reg_16;
assign dv_lsu_lpv_3__next = dv_lsu_lpv_2;
assign pyc_comb_17 = dv_lsu_lpv_3__next;
assign dv_lsu_lpt_0 = pyc_reg_19;
assign dv_lsu_lpt_1__next = dv_lsu_lpt_0;
assign pyc_comb_20 = dv_lsu_lpt_1__next;
assign dv_lsu_lpt_1 = pyc_reg_21;
assign dv_lsu_lpt_2__next = dv_lsu_lpt_1;
assign pyc_comb_22 = dv_lsu_lpt_2__next;
assign dv_lsu_lpt_2 = pyc_reg_23;
assign dv_lsu_lpt_3__next = dv_lsu_lpt_2;
assign pyc_comb_24 = dv_lsu_lpt_3__next;
assign dv_lsu_lpa_0 = pyc_reg_26;
assign dv_lsu_lpa_1__next = dv_lsu_lpa_0;
assign pyc_comb_27 = dv_lsu_lpa_1__next;
assign dv_lsu_lpa_1 = pyc_reg_28;
assign dv_lsu_lpa_2__next = dv_lsu_lpa_1;
assign pyc_comb_29 = dv_lsu_lpa_2__next;
assign pyc_constant_1 = 64'd0;
assign pyc_constant_2 = 7'd0;
assign pyc_constant_3 = 1'd0;
assign pyc_constant_4 = 1'd1;
assign dv_lsu_lpa_0__next = dv_lsu_ld_addr;
assign dv_lsu_lpt_0__next = dv_lsu_ld_pdst;
assign dv_lsu_lpv_0__next = dv_lsu_ld_valid;
assign pyc_comb_5 = pyc_constant_1;
assign pyc_comb_6 = pyc_constant_2;
assign pyc_comb_7 = pyc_constant_3;
assign pyc_comb_8 = pyc_constant_4;
assign pyc_comb_9 = dv_lsu_lpa_0__next;
assign pyc_comb_10 = dv_lsu_lpt_0__next;
assign pyc_comb_11 = dv_lsu_lpv_0__next;
assign dv_lsu_stbd = pyc_reg_33;
assign pyc_eq_34 = (dv_lsu_stba == dv_lsu_ld_addr);
assign pyc_and_35 = (dv_lsu_stbv & pyc_eq_34);
assign pyc_mux_36 = (pyc_and_35 ? dv_lsu_stbd : pyc_comb_5);
assign pyc_or_37 = (dv_lsu_st_valid | dv_lsu_stbv);
assign pyc_comb_38 = dv_lsu_stbd;
assign pyc_comb_39 = pyc_mux_36;
assign pyc_comb_40 = pyc_or_37;
assign dv_lsu_stbv__next = pyc_comb_40;
assign pyc_mux_41 = (dv_lsu_st_valid ? dv_lsu_st_addr : dv_lsu_stba);
assign dv_lsu_stba__next = pyc_mux_41;
assign pyc_mux_42 = (dv_lsu_st_valid ? dv_lsu_st_data : pyc_comb_38);
assign dv_lsu_stbd__next = pyc_mux_42;

// --- Sequential primitives
pyc_reg #(.WIDTH(1)) pyc_reg_12_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(pyc_comb_11),
  .init(pyc_comb_7),
  .q(pyc_reg_12)
);
pyc_reg #(.WIDTH(1)) pyc_reg_14_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(pyc_comb_13),
  .init(pyc_comb_7),
  .q(pyc_reg_14)
);
pyc_reg #(.WIDTH(1)) pyc_reg_16_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(pyc_comb_15),
  .init(pyc_comb_7),
  .q(pyc_reg_16)
);
pyc_reg #(.WIDTH(1)) pyc_reg_18_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(pyc_comb_17),
  .init(pyc_comb_7),
  .q(pyc_reg_18)
);
pyc_reg #(.WIDTH(7)) pyc_reg_19_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(pyc_comb_10),
  .init(pyc_comb_6),
  .q(pyc_reg_19)
);
pyc_reg #(.WIDTH(7)) pyc_reg_21_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(pyc_comb_20),
  .init(pyc_comb_6),
  .q(pyc_reg_21)
);
pyc_reg #(.WIDTH(7)) pyc_reg_23_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(pyc_comb_22),
  .init(pyc_comb_6),
  .q(pyc_reg_23)
);
pyc_reg #(.WIDTH(7)) pyc_reg_25_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(pyc_comb_24),
  .init(pyc_comb_6),
  .q(pyc_reg_25)
);
pyc_reg #(.WIDTH(64)) pyc_reg_26_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(pyc_comb_9),
  .init(pyc_comb_5),
  .q(pyc_reg_26)
);
pyc_reg #(.WIDTH(64)) pyc_reg_28_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(pyc_comb_27),
  .init(pyc_comb_5),
  .q(pyc_reg_28)
);
pyc_reg #(.WIDTH(64)) pyc_reg_30_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(pyc_comb_29),
  .init(pyc_comb_5),
  .q(pyc_reg_30)
);
pyc_reg #(.WIDTH(1)) pyc_reg_31_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(dv_lsu_stbv__next),
  .init(pyc_comb_7),
  .q(pyc_reg_31)
);
pyc_reg #(.WIDTH(64)) pyc_reg_32_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(dv_lsu_stba__next),
  .init(pyc_comb_5),
  .q(pyc_reg_32)
);
pyc_reg #(.WIDTH(64)) pyc_reg_33_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_8),
  .d(dv_lsu_stbd__next),
  .init(pyc_comb_5),
  .q(pyc_reg_33)
);

assign dv_lsu_ld_result_valid = dv_lsu_lpv_3;
assign dv_lsu_ld_result_tag = dv_lsu_lpt_3;
assign dv_lsu_ld_result_data = pyc_comb_39;

endmodule

