"""Deterministic v0.2 QueueProgram to typed gfsim C++ lowering."""

from __future__ import annotations

import ast
from dataclasses import dataclass

from ._queue_frontend import (
    Payload,
    QueueBinding,
    QueueFrontendError,
    QueueProgram,
    parse_queue_program,
)


def _cpp_type(acir_type: str) -> str:
    if acir_type == "i64":
        return "std::int64_t"
    if acir_type == "i1":
        return "bool"
    prefix = "!ac.struct<@types::@"
    if acir_type.startswith(prefix) and acir_type.endswith(">"):
        return acir_type[len(prefix) : -1]
    raise QueueFrontendError(f"ACLOWER-TYPE-MISMATCH: no C++ type for {acir_type}")


class _CppExpression:
    def __init__(self, argument: str) -> None:
        self.argument = argument

    def emit(self, node: ast.expr) -> str:
        if isinstance(node, ast.Name) and node.id == self.argument:
            return "item"
        if isinstance(node, ast.Constant) and type(node.value) in {int, bool}:
            if node.value is True:
                return "true"
            if node.value is False:
                return "false"
            return str(node.value)
        if isinstance(node, ast.Attribute):
            return f"{self.emit(node.value)}.{node.attr}"
        if isinstance(node, ast.BinOp) and isinstance(
            node.op, (ast.Add, ast.Sub, ast.Mult)
        ):
            operator = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*"}[
                type(node.op)
            ]
            return f"({self.emit(node.left)} {operator} {self.emit(node.right)})"
        raise QueueFrontendError(
            "ACLOWER-UNSUPPORTED-CONSTRUCT: lambda is outside C++ expression subset"
        )


def _policy_body(queue: QueueBinding) -> list[str]:
    assert queue.argument is not None and queue.expression is not None
    expression = _CppExpression(queue.argument)
    node = queue.expression
    if (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "with_fields"
        and not node.args
    ):
        lines = ["    auto result = item;"]
        for keyword in node.keywords:
            if keyword.arg is None:
                raise QueueFrontendError(
                    "ACLOWER-UNSUPPORTED-CONSTRUCT: field unpacking is forbidden"
                )
            lines.append(
                f"    result.{keyword.arg} = {expression.emit(keyword.value)};"
            )
        lines.extend(("    return result;",))
        return lines
    return [f"    return {expression.emit(node)};"]


@dataclass(frozen=True, slots=True)
class _ObjectIds:
    queues: dict[str, int]
    transforms: dict[str, int]
    sinks: tuple[int, ...]


def _object_ids(program: QueueProgram) -> _ObjectIds:
    next_id = 0
    queues: dict[str, int] = {}
    for queue in program.queues:
        queues[queue.name] = next_id
        next_id += 1
    transforms: dict[str, int] = {}
    for queue in program.queues:
        if queue.input_name is not None:
            transforms[queue.name] = next_id
            next_id += 1
    sinks = tuple(range(next_id, next_id + len(program.sinks)))
    return _ObjectIds(queues, transforms, sinks)


def lower_queue_program_to_cpp(program: QueueProgram) -> str:
    if program.scopes or program.routes or program.feedbacks or program.merges:
        raise QueueFrontendError(
            "ACLOWER-UNSUPPORTED-CONSTRUCT: initial gfsim slice supports serial "
            "source/transform/sink graphs"
        )
    ids = _object_ids(program)
    lines = [
        "// Generated by Agentic Circuit Queue/Var v0.2; do not edit.",
        '#include "gfsim/dispatch.h"',
        '#include "gfsim/object.h"',
        '#include "gfsim/queue.h"',
        '#include "gfsim/queue_blocks.h"',
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <limits>",
        "",
        "namespace ac_generated {",
        "",
    ]
    for payload in program.payloads:
        lines.extend(_emit_payload(payload))
    for queue in program.queues:
        if queue.input_name is None:
            continue
        payload = _cpp_type(queue.payload)
        lines.extend(
            (
                f"struct {queue.name}_policy {{",
                f"  {payload} operator()(const {payload} &item) const {{",
                *_policy_body(queue),
                "  }",
                "};",
                "",
            )
        )

    class_name = "".join(part.capitalize() for part in program.system.split("_"))
    lines.extend((f"class {class_name} final : public gfsim::Module {{", "public:"))
    lines.append(
        f'  {class_name}() : gfsim::Module("{program.system}", '
        "gfsim::kInvalidObjectId, nullptr),"
    )
    initializers: list[str] = []
    for queue in program.queues:
        payload = _cpp_type(queue.payload)
        initializers.append(
            f'{queue.name}_("{queue.name}", {ids.queues[queue.name]}, this, '
            f"{queue.depth}, std::numeric_limits<size_t>::max(), nullptr, "
            f"{queue.latency})"
        )
    for queue in program.queues:
        if queue.input_name is None:
            continue
        initializers.append(
            f'{queue.name}_block_("{queue.name}_transform", '
            f"{ids.transforms[queue.name]}, this, {queue.input_name}_, "
            f"{queue.name}_)"
        )
    for index, sink in enumerate(program.sinks):
        initializers.append(
            f'sink_{index}_("sink_{index}", {ids.sinks[index]}, this, '
            f"{sink.queue}_)"
        )
    for index, initializer in enumerate(initializers):
        suffix = "," if index + 1 < len(initializers) else ""
        lines.append(f"        {initializer}{suffix}")
    lines.extend(("  {", f'    setPath("/{program.system}");'))
    for queue in program.queues:
        lines.append(f"    attachChild({queue.name}_);")
    for queue in program.queues:
        if queue.input_name is not None:
            lines.append(f"    attachChild({queue.name}_block_);")
    for index, _ in enumerate(program.sinks):
        lines.append(f"    attachChild(sink_{index}_);")
    lines.extend(("  }", ""))
    source_queues = [queue for queue in program.queues if queue.input_name is None]
    for queue in source_queues:
        payload = _cpp_type(queue.payload)
        lines.append(
            f"  gfsim::SimQueue<{payload}> &{queue.name}() {{ return {queue.name}_; }}"
        )
    for index, sink in enumerate(program.sinks):
        payload = _cpp_type(next(q.payload for q in program.queues if q.name == sink.queue))
        lines.append(
            f"  const std::vector<{payload}> &sink_{index}_values() const {{ "
            f"return sink_{index}_.received(); }}"
        )
    object_count = len(program.queues) + len(ids.transforms) + len(ids.sinks)
    lines.extend(
        (
            "",
            f"  std::array<gfsim::DispatchRow, {object_count}> dispatch_rows() {{",
            f"    return std::array<gfsim::DispatchRow, {object_count}>{{",
        )
    )
    rows: list[str] = []
    for queue in program.queues:
        rows.append(f"gfsim::makeDispatchRow(&{queue.name}_)")
    for queue in program.queues:
        if queue.input_name is not None:
            rows.append(f"gfsim::makeDispatchRow(&{queue.name}_block_)")
    for index, _ in enumerate(program.sinks):
        rows.append(f"gfsim::makeDispatchRow(&sink_{index}_)")
    for index, row in enumerate(rows):
        suffix = "," if index + 1 < len(rows) else ""
        lines.append(f"        {row}{suffix}")
    lines.extend(("    };", "  }", "", "private:"))
    for queue in program.queues:
        lines.append(f"  gfsim::SimQueue<{_cpp_type(queue.payload)}> {queue.name}_;")
    for queue in program.queues:
        if queue.input_name is None:
            continue
        payload = _cpp_type(queue.payload)
        lines.append(
            f"  gfsim::QueueTransform<{payload}, {payload}, {queue.name}_policy> "
            f"{queue.name}_block_;"
        )
    for index, sink in enumerate(program.sinks):
        payload = _cpp_type(next(q.payload for q in program.queues if q.name == sink.queue))
        lines.append(f"  gfsim::QueueSink<{payload}> sink_{index}_;")
    lines.extend(("};", "", "} // namespace ac_generated", ""))
    return "\n".join(lines)


def _emit_payload(payload: Payload) -> list[str]:
    lines = [f"struct {payload.name} {{"]
    for name, typ in payload.fields:
        lines.append(f"  {_cpp_type(typ)} {name}{{}};")
    lines.extend(("};", ""))
    return lines


def lower_queue_source_to_cpp(text: str, system: str) -> str:
    return lower_queue_program_to_cpp(parse_queue_program(text, system))
